roles/matrix-server/tasks/main.yml
The setup-all should include the setup_well_known task as well
=> Add missing tag to task

roles/matrix-server/defaults/main.yml, roles/matrix-server/templates/mautrix-telegram/config.yaml.j2, roles/matrix-server/templates/nginx-conf.d/matrix-synapse.conf.j2
It used to allow user to logging with their own account to the bot
see: https://github.com/tulir/mautrix-telegram/wiki/Authentication#replacing-telegram-accounts-matrix-puppet-with-matrix-account for more informations
The endpoint is an uuid hash generated from the matrix_synapse_macaroon_secret_key so it is not easily guessable by a third party
=> Expose mautrix-telegram public endpoint through nginx

roles/matrix-server/defaults/main.yml
This brings the list in line with the new default as of https://github.com/matrix-org/synapse/pull/4207, otherwise 
https://github.com/vector-im/riot-web/issues/7717 can happen
=> Remove riot.im from list of trusted identity servers

roles/matrix-server/defaults/main.yml
tulir has released a new mautrix-telegram version !
Tested locally and it works correctly
=> Set default mautrix-telegram image to 0.4.0

roles/matrix-server/defaults/main.yml, roles/matrix-server/templates/mxisd/mxisd.yaml.j2
_mxisd_ supports several identity stores. Add support to configure two of them through role variables:
* synapseSql (storing identities directly in Synapse's database)
* LDAP
This removed the need to copy `mxisd.yaml.j2` to the inventory in case one wants to use LDAP as identity store. Note that the previous solution (copying `mxisd.yaml.j2`) was poor because of two reasons:
* The copy remains outdated in case the original is updated in future versions of this repo.
* The role's configuration should be in one place (configured only through role variables) instead of in multiple.
Configuring more identity stores through role variables can be supported in the future.
=> Support configuring mxisd's identity stores (two of them)

roles/matrix-server/templates/synapse/synapse.log.config.j2
This is the now recommended practice as of v0.34.0rc1
https://github.com/matrix-org/synapse/blob/develop/UPGRADE.rst#upgrading-to-v0340
Should work on Python 2 and 3 although I've only tested on Python 3
=> Add utf8 encoding option to log config

roles/matrix-server/defaults/main.yml, roles/matrix-server/tasks/setup/setup_riot_web.yml, roles/matrix-server/templates/riot-web/home.html.j2, roles/matrix-server/templates/systemd/matrix-riot-web.service.j2
* Add default template file for homepage HTML
* Add default riot-web config options for homepage
=> Enable support for custom HTML in riot-web homepage

roles/matrix-server/templates/env/env-mailer.j2
The documentation for the Postfix mailer image at https://hub.docker.com/r/panubo/postfix specifies the pupose of the `MAILNAME` environment variable as follows: 
> MAILNAME - set this to a legitimate FQDN hostname for this service (required).
This pull request changes the variable's value to hold the `hostname_matrix` configuration variable, which is a FQDN. In addition to being compliant to the image specification, setting a proper hostname avoids problems with strictly configured SMTP servers that require a FQDN. If it isn't set, the SMTP server may raise an error
> HELO command rejected: need fully-qualified hostname
and refuse delivery of the message. That's what happened in my installation and applying the patch of this pull request fixed the problem.
=> Set MAILNAME env variable to FQDN hostname for matrix-mailer

README.md, docs/configuring-playbook-bridge-appservice-irc.md, docs/configuring-playbook.md, group_vars/matrix-servers, roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/tasks/ext/appservice-irc/init.yml, roles/matrix-synapse/tasks/ext/appservice-irc/setup.yml, roles/matrix-synapse/tasks/ext/init.yml, roles/matrix-synapse/tasks/ext/setup.yml, roles/matrix-synapse/templates/ext/appservice-irc/systemd/matrix-appservice-irc.service.j2
I have tested this and everything works as expected on my personal server.
This uses [this](https://hub.docker.com/r/tedomum/matrix-appservice-irc/) docker image, and by extension [this](https://github.com/TeDomum/matrix-appservice-irc) fork of matrix-appservice-irc.
=> Add support for matrix-appservice-irc

roles/matrix-mxisd/defaults/main.yml, roles/matrix-mxisd/tasks/setup_mxisd.yml
The template can be set straight in the variable:
```
matrix_mxisd_threepid_medium_email_custom_invite_template: |
This is an
example template
```
=> Add support for custom MXISD templates

roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/ext/mautrix-telegram/systemd/matrix-mautrix-telegram.service.j2
This allows the out of matrix links to work when not using the built in nginx proxy
=> allow exposing mautrix_telegram port

roles/matrix-mxisd/defaults/main.yml
I made an indenting mistake in https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/108, causing generators to be put as a subkey of password. Oops.
=> Fix indenting of generators value

docs/configuring-dns.md, docs/configuring-playbook-dimension.md
1. Fix incorrect link in DNS configuration page
2. Make "Getting access token" in Dimension documentation more descriptive
=> Fix Dimension documentation

roles/matrix-dimension/defaults/main.yml
Today I lost few hours trying to figure out why my Dimension server does not connect to Matrix Federation server Docker container `matrix-synapse` as configured: `federationUrl: "http://matrix-synapse:8048"` The cause was `homeserver.name` in config: `matrix.HOSTNAME.COM`, but it needs to be just `HOSTNAME.COM`.
After changing name from `{{ matrix_server_fqn_matrix }}` to `{{ matrix_domain }}` Dimension started to work again for me.
=> Fix Matrix homeserver name in Dimension configuration

roles/matrix-dimension/defaults/main.yml, roles/matrix-dimension/templates/systemd/matrix-dimension.service.j2
I tried to add custom widget with website where SSL certificate was self signed. Dimension did not allow me to do that saying `error [DimensionWidgetService] unable to verify the first certificate`.
Found out that Node needs global parameter `NODE_TLS_REJECT_UNAUTHORIZED` set to `0` to stop checking SSL certificates validity. I know - it's a security issue, but if I really need to embed such websites, I can take this risk.
=> Add option to enable Dimension widgets serve sites with self signed certs

roles/matrix-synapse/tasks/self_check_federation_api.yml
When federation was intentionally disabled (via `matrix_synapse_federation_enabled: false`), self-check `ansible-playbook -i inventory/hosts setup.yml --tags=self-check` was failing when it got to the federation check. This PR modifies the self-check to test for working federation when `matrix_synapse_federation_enabled: true` and to test for no federation when `matrix_synapse_federation_enabled: false`.
=> Federation self-check respects matrix_synapse_federation_enabled

roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
This allows overriding the default value for `include_content`. Setting this to false allows homeserver admins to ensure that message content isn't sent in the clear through third party servers.
=> Allow configuring push content for matrix-synapse

roles/matrix-nginx-proxy/tasks/ssl/setup_ssl_lets_encrypt.yml
Currently the nginx reload cron fails on Debian 9 because the path to systemctl is /bin/systemctl rather than /usr/bin/systemctl.
CentOS 7 places systemctl in both /bin and /usr/bin, so we can just use /bin/systemctl as the full path.
=> Use common path for systemctl in lets encrypt cron

docs/prerequisites.md
When using Let's Encrypt SSL certificates, a cronjob is set up to
automatically renew them. Though it does require a `cron`-compatible
program on the server.
This fixes the error that is caused by the `/etc/cron.d` directory
not existing and the `ansible-cron` module trying to write out a
file there -- without checking if the directory exists first.
---
See #125: Since the `cron` program might be required (or not if the user has their own SSL certificates), I offer to first warn people off about it in the documentation.
=> Specify that cron is likely required on the server (fixes #125)

roles/matrix-riot-web/defaults/main.yml
I have tested this version a bit and have found no noticeable errors.
=> Update Riot Web from 1.0.5 to 1.0.6

roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/goofys/env-goofys.j2, roles/matrix-synapse/templates/goofys/systemd/matrix-goofys.service.j2
Goofys can work with more than just Amazon S3. _Hopefully_ this is all it takes to enable configuring a custom endpoint for custom endpoints like Minio.
=> Goofys Custom Endpoint Support

roles/matrix-dimension/defaults/main.yml
Media is pulled from client side, so we specify external Matrix DNS name as mediaUrl
=> Make Dimension communicate to Synapse through Docker network

roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
- matrix_enable_room_list_search - Controls whether searching the public room list is enabled.
- matrix_alias_creation_rules - Controls who's allowed to create aliases on this server.
- matrix_room_list_publication_rules - Controls who can publish and which rooms can be published in the public room list.
=> Add additional room config options

roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
Following conversations on Riot, this should enable re-enable URL previews by default.
=> Fixed default url preview settings

group_vars/matrix-servers, roles/matrix-riot-web/defaults/main.yml, roles/matrix-riot-web/templates/config.json.j2
This is kind of a hack put in place until homeservers have a way of advertising that they have disabled presence and makes Riot hide all the presence related info.
=> Set Riot's enable_presence_by_hs_url to false if presence is disabled

roles/matrix-base/templates/usr-local-bin/matrix-remove-all.j2
Use `matrix_docker_network` and `matrix_base_data_path` in `matrix-remove-all`
instead of hardcoded default values.
=> Remove hardcoded values in matrix-remove-all

roles/matrix-nginx-proxy/defaults/main.yml
Use an int conversion in the computation of the value of
`matrix_nginx_proxy_tmp_directory_size_mb`, to have the integer value
multiplied by 50 instead of having the string repeated 50 times.
=> Fix value of nginx-proxy tmpfs size

roles/matrix-corporal/defaults/main.yml, roles/matrix-corporal/templates/systemd/matrix-corporal.service.j2, roles/matrix-coturn/defaults/main.yml, roles/matrix-coturn/templates/systemd/matrix-coturn.service.j2, roles/matrix-dimension/defaults/main.yml, roles/matrix-dimension/templates/systemd/matrix-dimension.service.j2, roles/matrix-mailer/defaults/main.yml, roles/matrix-mailer/templates/systemd/matrix-mailer.service.j2, roles/matrix-mxisd/defaults/main.yml, roles/matrix-mxisd/templates/systemd/matrix-mxisd.service.j2, roles/matrix-nginx-proxy/defaults/main.yml, roles/matrix-nginx-proxy/templates/systemd/matrix-nginx-proxy.service.j2, roles/matrix-postgres/defaults/main.yml, roles/matrix-postgres/templates/systemd/matrix-postgres.service.j2, roles/matrix-riot-web/defaults/main.yml, roles/matrix-riot-web/templates/systemd/matrix-riot-web.service.j2, roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/systemd/matrix-synapse.service.j2
Untested, but submitting it to get your two cents.
I've been having to deal with a network setup where the external domain names cannot be resolved internally. Thus, I've been adding --add-host flags to the systemd files.
`--add-host` however, seems very much a very specific edge case, so I figured I should instead make it possible to add support for any extra docker arguments, so that any weird edge case can be worked around by users.
How does this seem?
=> Add the possibility to pass extra flags to the docker container

roles/matrix-riot-web/templates/config.json.j2, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
This prevents Ansible from sometimes failing to decrypt vault variables.
I've tried to be careful and only cast string values to string before to_json, not lists or booleans, yet also as much as possible so people can use vault variables as much as possible (who knows, usernames may be vault-worthy for some). Please double check if I didn't accidentally cast too much. Proper fix for #102.
=> string before to_json when string value is expected

examples/caddy/matrix-dimension, examples/caddy/matrix-synapse
The instruction that tells Caddy to make exceptions when proxying is `except`, instead of `without`, which trims the given prefix from the proxied URIs, as per https://caddyserver.com/docs/proxy
I also took the liberty to expand the examples' comments about TLS, including instructions about Caddy's built-in LE support.
=> Fix matrix-synapse example for Caddy

roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
With the leftover `|string` it was ending up as `start_tls: "False"` in `homeserver.yaml` which evaluates to `true`, causing unexpected
```
ldap_auth_provider - 420 - WARNING -  - Error during LDAP authentication: startTLS failed - protocolError
```
=> Fix matrix_synapse_ext_password_provider_ldap_start_tls (it's boolean)

docs/configuring-playbook-rest-auth.md
Well this does set it up so that the mxisd endpoint is reachable from the synapse container.
=> Provide a sample rest_auth_endpoint close to actual setup

roles/matrix-mxisd/defaults/main.yml
Else,
```
May 14 22:35:04 base docker[25166]: [main] ERROR App - You must specify at least one Base DN via the singular or plural config option                         
May 14 22:35:04 base docker[25166]: [main] ERROR App - Invalid or empty value for configuration item: ldap.connection.baseDNs
May 14 22:35:05 base systemd[1]: matrix-mxisd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT                                             
```
=> Fix case of the mxisd ldap.connection.baseDNs option in matrix_mxisd_configuration_extension_yaml comment

roles/matrix-common-after/tasks/start.yml
When an error happens in starting the server, it tells users to ` Try running systemctl status {{ item }} and systemctl -fu {{ item }}`, even though systemctl -fu doesn't exist, and it was meant to be journalctl.
It's a small fix, but finding out it was meant to be journalctl saved me a lot of grief, and it may help others too.
=> Fixed error message to direct users to the right debug command

roles/matrix-bridge-appservice-irc/defaults/main.yml
appservice-irc doesn't have permission to create files in its project directory, so the default config results in the following error message:
```
Jun 22 07:56:33 matrix matrix-appservice-irc[4517]: Loading config file /config/config.yaml
Jun 22 07:56:33 matrix matrix-appservice-irc[4517]: 2019-06-22T05:56:33.809Z '[FileStreamRotator] Failed to store log audit at:' '.0cf66abdbd2fe32c05e614547bf32513986ab836-audit
Jun 22 07:56:33 matrix matrix-appservice-irc[4517]:     at Error (native)
Jun 22 07:56:33 matrix matrix-appservice-irc[4517]:     at Object.fs.openSync (fs.js:642:18)
Jun 22 07:56:33 matrix matrix-appservice-irc[4517]:     at Object.fs.writeFileSync (fs.js:1356:33)
Jun 22 07:56:33 matrix matrix-appservice-irc[4517]:     at Object.FileStreamRotator.writeAuditLog …
```
=> Disable appservice-irc log files

CHANGELOG.md, docs/configuring-playbook-bridge-appservice-discord.md, group_vars/matrix_servers, roles/matrix-bridge-appservice-discord/defaults/main.yml, roles/matrix-bridge-appservice-discord/tasks/init.yml, roles/matrix-bridge-appservice-discord/tasks/setup_install.yml, roles/matrix-bridge-appservice-discord/tasks/validate_config.yml, roles/matrix-bridge-appservice-discord/templates/systemd/matrix-appservice-discord.service.j2, roles/matrix-bridge-appservice-irc/tasks/setup_install.yml
Well, `config.yaml` has been playbook-managed for a long time.
It's now extended to match the default sample config of the Discord
bridge.
With this patch, we also make `registration.yaml` playbook-managed,
which leads us to consistency with all other bridges.
Along with that, we introduce `./config` and `./data` separation,
like we do for the other bridges.
--------
Until now, the `config.yaml` file for the Discord bridge was managed by the playbook, but the `registration.yaml` file was not.
From now on, the playbook will keep both configuration files sync for you.
This means that if you were making manual changes to the `/matrix/appservice-discord/discord-registration.yaml` configuration file, those would be lost the next time you run the playbook.
The bridge now stores configuration in …
=> Make Discord bridge configuration playbook-managed

roles/matrix-base/tasks/setup_server_base.yml
This fixes the apt/apt-get warning
`N: Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'https://download.docker.com/linux/<distro> <version> InRelease' doesn't support architecture 'i386'`
when updating your system.
=> Fix apt message: docker doesn't support arch 'i386'

docs/configuring-playbook-email.md
I had some troubles with email because, as you correctly pointed out a few days ago, Google Cloud blocks port 25. For using an external SMTP server, I found that the Sendgrid free tier is pretty generous and hassle free, so I set it up on the friendserver I'm running. I'm documenting how to do it here because it took me a few tries to get all the configurations correct, and might be useful for other people using Google cloud.
=> Describe setting up SMTP server with Sendgrid

docs/configuring-playbook-bridge-appservice-slack.md, docs/configuring-playbook.md, group_vars/matrix_servers, roles/matrix-bridge-appservice-slack/defaults/main.yml, roles/matrix-bridge-appservice-slack/tasks/init.yml, roles/matrix-bridge-appservice-slack/tasks/main.yml, roles/matrix-bridge-appservice-slack/tasks/setup_install.yml, roles/matrix-bridge-appservice-slack/tasks/setup_uninstall.yml, roles/matrix-bridge-appservice-slack/tasks/validate_config.yml, roles/matrix-bridge-appservice-slack/templates/systemd/matrix-appservice-slack.service.j2, setup.yml
This is a role for using Matrix-Appservice-Slack.
There is no documentation yet, but to use it you need to define `slack_control_room_id` and `matrix_appservice_slack_enabled` in the inventory/host_vars/.../vars.yml file.
The `--tags=setup-all` and `start` work fine, but if you check the `journalctl -fu matrix-appservice-slack` you'll PROBABLY get a `Unhandled rejection Error: connect ECONNREFUSED` error. The matrix port connects to the homeserver itself, similar to the discord appservice and is right now set to 8008.
After I settle a few other projects, I hope to cycle back to this, but feel free to give it a whirl if you want!
=> WIP: Added Slack role

docs/configuring-playbook-own-webserver.md, examples/haproxy/Dockerfile, examples/haproxy/README.md, examples/haproxy/docker-compose.yml, examples/haproxy/haproxy.cfg, examples/haproxy/nginx.conf
This PR adds brief documentation on how to use HAproxy in front of Matrix and proposes a sample configuration for HAproxy and for a dummy Nginx container. 
It might be a corner case, but this was the case I had to solve for myself and it might be useful for someone as well.
=> Add haproxy doc

examples/apache/matrix-synapse.conf
Invitations weren't working for me until I added 'nocanon' to these additional places. Until then, invitations failed with "Invalid signature for server ..." errors, as in https://github.com/matrix-org/synapse/issues/3294 .
I didn't check whether the user_directory/search proxy line also needs it, I just assumed it should have it too.
The other two proxy lines in this example also include a 'retry=0' parameter. That's a separate issue; I haven't touched it here.
=> More Apache ProxyPass directives need 'nocanon'

ansible.cfg, examples/hosts
This is a rather small change that moves the pipelining option from `examples/hosts` to `ansible.cfg`.
In my understanding the example section tries to be as simple and as easy to understand as possible. Most users however will not be able to understand what pipelining actually means and thus not change the option. Moving it away will hide it and makes the example host file 25% easier to read ;)
Also, while that option can be triggered via an environment variable like in the example hosts file, moving it to the config file enables users (and developers of this playbooks) to define it as a default value, and change it via `-e` on the fly if needed without worrying about the precedence of the environment variables.
=> Move pipelining configuration to ansible.cfg

CHANGELOG.md, roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
#273 should happen at the same time
=> WIP: Upgrade Synapse (1.3.1 -> 1.4.0)

roles/matrix-synapse/templates/synapse/usr-local-bin/matrix-synapse-register-user.j2
Prompted by conversation between @elsatch:matrix.org and @aaronraimist about non-alphanumeric characters in password.
=> Quote docker args in case inputs contain spaces

examples/apache/matrix-synapse.conf
Listen 8448 directive makes apache listen on that port, without it federation does not work.
=> Listen 8448 required for apache

roles/matrix-synapse/templates/synapse/systemd/matrix-synapse.service.j2
`matrix_synapse_storage_path` is already defined in `matrix-synapse/defaults/main.yml` (with a default of `"{{ matrix_synapse_base_path }}/storage"`), but was not being used for its presumed purpose in `matrix-synapse.service.j2`. As a result, if `matrix_synapse_storage_path` was overridden (in a `vars.yml`), the synapse service failed to start.
=> Actually use matrix_synapse_storage_path

docs/howto-server-delegation.md
=> Fix --mount syntax in examples

roles/matrix-bridge-appservice-discord/tasks/init.yml, roles/matrix-bridge-appservice-irc/tasks/init.yml, roles/matrix-bridge-appservice-slack/tasks/init.yml, roles/matrix-bridge-mautrix-facebook/tasks/init.yml, roles/matrix-bridge-mautrix-hangouts/tasks/init.yml, roles/matrix-bridge-mautrix-telegram/tasks/init.yml, roles/matrix-bridge-mautrix-whatsapp/tasks/init.yml, roles/matrix-synapse/tasks/ext/rest-auth/setup_install.yml, roles/matrix-synapse/tasks/ext/shared-secret-auth/setup_install.yml, roles/matrix-synapse/tasks/ext/synapse-simple-antispam/setup_install.yml
Replace constructs appending elements with variables to matrix_synapse_container_extra_arguments. Fixes issue https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/304
The only bridge I have activated is mautrix-whatsapp. Can anyone test these changes with other/more bridges activated?
=> Replace constructs appending elements with variables to matrix_synapse_container_extra_arguments

roles/matrix-base/tasks/setup_server_base.yml
I switched to docker.io on my matrix server since docker-ce doesn't support Ubuntu 19.10 yet. This PR skips installing docker-ce if docker.io is already present.
=> Don't install docker-ce if docker.io is installed

roles/matrix-base/tasks/setup_server_base.yml
Since commit b9753635 the task 'Ensure docker-ce is installed (Debian)' fails with an error on CentOS although it should not even run on this OS.
=> Fix: Restrict a Debian-specific task to Debian OS.

roles/matrix-base/templates/static-files/well-known/matrix-client.j2
Riot used to be fine with it being blank but now it complains. This creates an ugly looking comma when there is an identity server configured but I guess that's fine.
=> Remove identity server section from .well-known/matrix/client if there is no identity server

roles/matrix-riot-web/defaults/main.yml, roles/matrix-riot-web/templates/systemd/matrix-riot-web.service.j2
Switching to the official image (vectorim/riot-web) should ensure:
- there's less breakage, as it's maintained by the same team as riot-web
- there's fewer actors we need to trust
- we can upgrade riot-web faster, as newer versions should be released
on Docker hub at the same time riot-web releases are made
-----
Looks like this works, but I'd rather we not regress in terms of Docker image sizes.
See: https://github.com/vector-im/riot-web/pull/9848
We can wait a while and switch later, if/when the above gets merged.
=> Switch riot-web image (bubuntux/riot-web -> vectorim/riot-web)

group_vars/matrix_servers, roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2, roles/matrix-synapse/templates/synapse/systemd/matrix-synapse.service.j2
Can you double check that the way I have this set only exposes it locally? It is important that the manhole is not available to the outside world since it is quite powerful and the password is hard coded.
=> Allow Synapse manhole to be enabled

roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2
Vhost directives were not being rendered in the https server block which made .well-known urls not work.
=> Render vhost directives in https server block

roles/matrix-bridge-appservice-discord/defaults/main.yml
This allows for users to bridge already existing matrix rooms to discord
=> Expose self service bridging in matrix_appservice_discord

docs/ansible.md
Fixed small typo, added an extra note on how to use the ansible docker image when not using a ssh key for authentication
=> Notes when not using a ssh key for authentication

roles/matrix-bridge-mautrix-facebook/defaults/main.yml, roles/matrix-bridge-mautrix-hangouts/defaults/main.yml, roles/matrix-bridge-mautrix-telegram/defaults/main.yml
These templates seemingly were copied originally from the mxisd one.. so remove the stray strings.
=> Remove spurious 'mxisd' string from mautrix bridge templates comment

roles/matrix-bridge-appservice-webhooks/defaults/main.yml
Currently user registration for the webhook bridge is broken. See:
```
Jan-15-2020 17:36:41.639 +00:00 info [WebService [Hook 6x3q7FjQkQk4UJI69c2oVu3cRJPUK4KvdKdgRRZKgYOIA1W0MYoQr3BsD4zRIRPe]] Publishing webhook request for processing
Jan-15-2020 17:36:41.641 +00:00 info [WebhookBridge] Updating appearance of @_webhook__fDIN992hzJPf7kYP6p_matrix_Incoming_Webhook:matrix
Jan-15-2020 17:36:41.647 +00:00 error [matrix-appservice-bridge] [-] POST http://matrix-synapse:8008/_matrix/client/r0/register (AS) HTTP 400 Error: "{\"errcode\":\"M_EXCLUSIVE\",\"error\":\"Invalid user localpart for this application service.\"}"
Jan-15-2020 17:36:41.648 +00:00 error [WebhookReceiver] Invalid user localpart for this application service.
```
This pull request fixes the user registration regex for the …
=> Fix regex in matrix_appservice_webhooks_registration_yaml

group_vars/matrix_servers
Under the previous salts, this resulted in the incredibly cryptic error of:
```
original message: An unhandled exception occurred while templating '{{ matrix_synapse_macaroon_secret_key | password_hash('sha512', 'webhooks-id-token') | to_uuid }}'.
Error was a <class 'ValueError'>, original message: invalid characters in sha512_crypt salt
```
Ansible password salts must be <= 16 characters and have a variety of restrictions on the contents, namely no `-` characters.
=> Fix invalid password salts for slack webhooks

roles/matrix-base/tasks/server_base/setup_debian.yml
I got this error when the if case evalutes to false, so I added an else statement to fix the error.
```
FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: the inline if-expression on line 1 evaluated to false and no else section was defined.
```
=> Fix for when if case evaluates to false

roles/matrix-bridge-appservice-irc/defaults/main.yml
77b919aec690a does most of the work to make this happen.
Still, it'd be nice to test this some more, especially by people who have been running the old bridge and have an existing database.
=> Switch to upgraded & official matrix-appservice-irc Docker image

roles/matrix-synapse/defaults/main.yml
Synapse v1.9.0 changed some things which made the REST Auth Password
Provider break.
The ma1uta/matrix-synapse-rest-password-provider implements some
workarounds for now and will likely deliver a proper fix in the future.
Not much has changed between the 2 projects, so this should be a
painless transition.
=> Switch from kamax-matrix/matrix-synapse-rest-password-provider to ma1uta/matrix-synapse-rest-password-provider

group_vars/matrix_servers
Change usage of `-` on slack bridge configuration files (password hash) to `.`, following the same principle as in #357 for slack webhooks, fixing #365.
=> fix invalid password salt on slack bridge

README.md, docs/configuring-playbook-bridge-appservice-irc.md, roles/matrix-bridge-appservice-irc/defaults/main.yml
This fixes an incorrect indentation in the database specification for appservice-irc which caused matrix-appservice-irc to refuse to start with the remarkably unhelpful error message:
```
ERROR:CLI Failed to run bridge.
```
This also updates doc links to the new upstream repo because the tedomum repo contains out-of-date documentation.
=> Fix matrix-appservice-irc database specification

group_vars/matrix_servers
Hi and thank you for these great ansible roles!
Following https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/357 and https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/368 it seems the slack bridge needs some more fixing:
```
TASK [matrix-bridge-appservice-slack : Ensure appservice-slack registration.yaml installed]
fatal: [matrix.pub.solar]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ matrix_appservice_slack_registration_yaml|from_yaml }}'
Error was a <class 'ValueError'>, original message: salt too large (sha512_crypt requires <= 16 chars)"
```
```
$: ansible -i inventory/hosts -m setup 'matrix_servers' | grep -i ansible_python_version
"ansible_python_version": "2.7.5",
```
This is on centOS 7.
This PR reduces the salt length to …
=> fix slack bridge: salt too large, sha512_crypt requires <= 16 chars

roles/matrix-nginx-proxy/defaults/main.yml, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-dimension.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-riot-web.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/nginx-http.conf.j2
Adding the ability to add additional configuration block not only the synapse vhost, but also to the nginx-http block, riot, dimension and domain vhost.
In my use case I needed to add additional arguments to import the real-ip (because my deployment is running behind a traefik reverse proxy).
Example usage:
```
matrix_nginx_proxy_proxy_http_additional_server_configuration_blocks:
- set_real_ip_from 172.16.0.0/12;
- real_ip_header X-Real-Ip;
- real_ip_recursive on;
```
=> matrix-nginx-proxy: adding additional configuration blocks

roles/matrix-bridge-appservice-webhooks/templates/systemd/matrix-appservice-webhooks.service.j2
appservice webhooks container was mapped to matrix port instead of webhooks port.
=> Fixed appservice webhooks container port mapping

CHANGELOG.md, roles/matrix-riot-web/defaults/main.yml, roles/matrix-riot-web/templates/config.json.j2
Support Riot config option to display a custom homeserver name on the Riot login page.
=> Riot config server name

roles/matrix-bridge-appservice-webhooks/templates/systemd/matrix-appservice-webhooks.service.j2
Hy,
When using Webhooks together with external nginx, the default ports are wrong in my opinion. This Merge Request modify Webhooks Appservice so it is working.
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-bridge-appservice-webhooks/templates/systemd/matrix-appservice-webhooks.service.j2
When you look at this file, you see node.js command, which is start with port "{{ matrix_appservice_webhooks_matrix_port }}" (Default: 6789)
But the Port, which is exposed by default is "{{matrix_appservice_webhooks_webhooks_port}}" (Default: 6788)
But on Port 6788 there nothing is listening in docker container.
So I switch the exposed variable to "matrix_appservice_webhooks_matrix_port", because I don't wanted to modify the ports for "non external nginx".
Normally …
=> Switch Webhooks Port, which is exposed for external nginx

roles/matrix-riot-web/defaults/main.yml, roles/matrix-riot-web/templates/config.json.j2, roles/matrix-riot-web/templates/welcome.html.j2
Because we are starting using Matrix/Riot productive, I checked Riot-Web README for new configurations and found some I'm searching for some time time, because both logos on welcome page are handled different and wallpaper cannot changed.
Now customization of logo during login and wallpaper is also able to configure.
Pay attention: 
The way I choose will change default behavior of UI, because in past the second "Login Logo" cannot configured. 
Now it is set to same logo as on welcome startpage. So this logo maybe changed from riot logo to branding.
When default of "matrix_riot_web_welcome_authlogo" is set to "false", the old behavior will used.
About "matrix_riot_web_welcome_headline", this isn't always my preferred method to insert "_t(..)", too, but I think the translation cannot …
=> Customization welcome

roles/matrix-postgres/defaults/main.yml
Update synapse-janitor to reflect changes in synapse database schema.
Old version failed with the following error:
```
psql:/synapse_janitor.sql:91: NOTICE:  synapse_clean_unused_rooms() Cleaning up 22 unused rooms
psql:/synapse_janitor.sql:91: ERROR:  relation "topics" does not exist
LINE 1: DELETE FROM topics AS x WHERE x.room_id IN (SELECT y.room_id...
^
QUERY:  DELETE FROM topics AS x WHERE x.room_id IN (SELECT y.room_id FROM synapse_clean_unused_rooms__tmp AS y)
CONTEXT:  PL/pgSQL function synapse_clean_unused_rooms() line 21 at SQL statement
```
=> Update synapse-janitor to support current synapse database schema

docs/configuring-playbook-jitsi.md
This matches the way the ports are written in prerequisites.md and is the format that UFW likes.
=> Flip around Jitsi port format to match other ports

roles/matrix-jitsi/templates/jicofo/sip-communicator.properties.j2, roles/matrix-jitsi/templates/web/config.js.j2
While double checking on the `internal` authentication in [docker-jitsi-meet](https://github.com/jitsi/docker-jitsi-meet) I noticed a missing conditional, that this PR adds.
For reference, see [sip-communicator.properties](https://github.com/jitsi/docker-jitsi-meet/blob/7c0c795fa7d29d04248ec6201ef7b879f4dc537f/jicofo/rootfs/defaults/sip-communicator.properties#L13-L15) in that repo.
=> add missing jitsi auth URL conditional

docs/configuring-playbook-jitsi.md
This PR adds documentation for how to setup Jitsi with authentication and guests mode.
@spantaleev I'd like to add reviewers, but it seems disabled for this repo.
=> add optional Jitsi internal auth+guests docs

roles/matrix-bridge-mautrix-facebook/tasks/setup_install.yml, roles/matrix-bridge-mautrix-hangouts/tasks/setup_install.yml
Slight modification to force self-build images when the git master branch has been modified, as currently the docker image xy:latest is always present.
=> Facebook self build

group_vars/matrix_servers
Gergely Horváth:
A single line is missing from group_vars/matrix_servers: matrix_mx_puppet_skype_container_image_self_build: "{{ matrix_container_images_self_build }}",
so if the global variable is set, everything is being self-built
=> Add global var to control skype image self build

docs/configuring-playbook-bridge-appservice-slack.md
better described how to get channel id, added a section how to unlink a channel and a troubleshooting section
=> matrix-appservice-slack: improved documentation

roles/matrix-bridge-mx-puppet-skype/defaults/main.yml
Default port was set to 6000 and upstream developer updated to 8438 to avoid port clash.
=> Upstream set mx-puppet-skype default port to 8438

roles/matrix-nginx-proxy/templates/usr-local-bin/matrix-ssl-lets-encrypt-certificates-renew.j2, roles/matrix-postgres/templates/usr-local-bin/matrix-change-user-admin-status.j2, roles/matrix-postgres/templates/usr-local-bin/matrix-postgres-cli.j2, roles/matrix-postgres/templates/usr-local-bin/matrix-postgres-update-user-password-hash.j2
There was a few hardcoded values in the postgres script template `matrix-change-user-admin-status`, which are fixed by this PR to correctly used the templated variables. Additionally, some inconsistent whitespace usage I noticed in these scripts is fixed by this PR.
=> Fix hardcoded postgres template values

roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
Trivial change to expose `allowed_local_3pids` (which allows you to restrict registration to users who provide a 3pid matching the specified pattern or patterns) as a configurable option.
=> Expose allowed local 3pids as a configurable option

docs/configuring-playbook-dimension.md, group_vars/matrix_servers, roles/matrix-dimension/defaults/main.yml, roles/matrix-dimension/tasks/validate_config.yml, roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
This PR adds support for running dimension in an unfederated environment, following the upstream [documentation](https://github.com/turt2live/matrix-dimension/blob/master/docs/unfederated.md).
I'm not sure about the DNS requirements in an unfederated environment, so left that section of the [docs](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-dimension.md#prerequisites) alone.
Happy to hear any advice on a better/cleaner way to make the switch in the config.
=> Add support for running dimension in an unfederated environment

roles/matrix-jitsi/defaults/main.yml
As far as I can see, there should be no further changes needed to our special ansible setup.
https://github.com/jitsi/docker-jitsi-meet/compare/stable-4384-1...stable-4416
=> Update Jitsi docker images to stable 4416

roles/matrix-riot-web/defaults/main.yml, roles/matrix-riot-web/templates/config.json.j2
Add two useful keys for configuring riot-web : `permalinkPrefix` and `default_theme`
Those two keys were missing and are useful to further configure Riot-Web, both being specifications of the [riot config file](https://github.com/vector-im/riot-web/blob/develop/docs/config.md)
- `permalinkPrefix` allows to redirect users to non-federated instance of Riot at `riot.DOMAIN` or `matrix.to.DOMAIN` instead of the default `matrix.to`
- `default_theme` allows to edit default_theme for Riot users
=> add missing keys 'permalinkPrefix' and 'default_theme' for configuring riot web

docs/configuring-playbook-jitsi.md, roles/matrix-jitsi/defaults/main.yml, roles/matrix-jitsi/templates/prosody/env.j2
This PR adds support for the [saslauthd method](https://github.com/jitsi/jitsi-meet/wiki/LDAP-Authentication#ldap-authentication-for-jitsi-meet-via-cyrussaslauthd) of authenticating Jitsi users via LDAP (by following the [docker-jitsi-meet](https://github.com/jitsi/docker-jitsi-meet#authentication-using-ldap) docs).
I was considering trying to harmonise the Jitsi LDAP configuration added in this PR with the other LDAP auth methods we already support ([synapse ldap3](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-ldap-auth.md#setting-up-the-ldap-authentication-password-provider-module-optional-advanced) and [ma1sd ldap](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-ma1sd.md#authentication)) …
=> Add support for Jitsi LDAP authentication

docs/configuring-playbook-dimension.md
This can be removed once turt2live/matrix-dimension#345 is resolved.
=> Document how to point dimension jitsi widgets at your own jitsi instance

docs/configuring-playbook-dimension.md
A minor improvement in the Dimension docs, as discussed in ﻿#matrix-docker-ansible-deploy:devture.com.
=> Clarify domain of Dimension admin users in docs by using matrix_domain variable

docs/installing.md
This flag is necessary for Ansible to ask for the sudo password when using the non-root option as documented in the `hosts` file. Otherwise, Ansible errors out with `missing sudo password`.
=> Add note about ask-become-pass

roles/matrix-riot-web/templates/systemd/matrix-riot-web.service.j2
Riot unconditionally asks for a config.${document.domain}.json, c.f.
https://github.com/vector-im/riot-web/blame/develop/src/vector/getconfig.ts#L24
So with some ease, we provide that.
=> Prevent 404s when Riot tries to retrieve domain-specific config.json

roles/matrix-jitsi/defaults/main.yml, roles/matrix-jitsi/tasks/setup_jitsi_prosody.yml, roles/matrix-jitsi/templates/prosody/matrix-jitsi-prosody.service.j2
This PR updates the Jitsi containers to the latest version which is 4548-1 atm.
Also a new volume for plugins is added to the prosody container.
Possible breaking upstream changes:
- Prosody auth method changed default from `internal_plain` to `internal_hashed`. I guess people using auth need to reconfigure all passwords. Will report back after more testing. See https://github.com/jitsi/docker-jitsi-meet/commit/d44230e2b121e72542a60b6dfbce9b07e84ed706#diff-af6bb4ab6f170892599e22f681468018
Open question:
- How closely do we want to follow the Jitsi docker upstream repo? E.g. [this commit](https://github.com/jitsi/docker-jitsi-meet/commit/0177765f2dfb7c54afa33158d5e25e8f3bcefe4d#diff-4e5e90c6228fd48698d074241c2ba760) adds compatibility for SElinux `enforcing` mode, do we want that, too? Or …
=> Jitsi 4548-1 update

roles/matrix-ma1sd/defaults/main.yml
I stumpled upon this while installing and configuring Matrix. The client (Riot) was not able to use the configured Identity Server. Riot returned
```
Access to XMLHttpRequest at 'https://matrix.example.com/_matrix/identity/v2/account/register' from origin 'vector://vector' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
First it looks like a CORS problem but with a deeper look in ma1sd I noticed that `v2` is not enabled by default at the moment. They will change that in a upcoming release. So I think it is a useful change to enable that by default or have it configurable anyways.
=> enable by default v2 api prefix for ma1sd

roles/matrix-postgres/tasks/import_sqlite_db.yml
the current version fails the import, because the volume for the media is missing. It still fails if you have the optional shared secret password provider is enabled, so that might need another mount. Commenting out the password provider in the hoimeserver.yaml during the run works as well.
=> fix for importing sqllite database

roles/matrix-bridge-mx-puppet-slack/defaults/main.yml, roles/matrix-bridge-mx-puppet-slack/templates/config.yaml.j2
Simple PR that copy the conf for double puppeting from mx-puppet-skype to mx-puppet-slack
=> Fix missing conf for double puppeting in mx-puppet-slack

docs/configuring-playbook-ma1sd.md
After some excellent help by @aaronraimist, and his suggestion that we document this particular use-case, I thought I'd give it a go. It's trivially easy to make SMS happen but finding the resultant options to twiddle wasn't intuitive.
Since I suspect many people would very much want to enable this option, I here suggest a small addition to the documentation to point the way.
=> Added config hint for SMS verification

roles/matrix-jitsi/defaults/main.yml, roles/matrix-jitsi/templates/web/config.js.j2
I was doing several tests with jitsi. I was able to improve CPU and bandwidth consumption by adjusting parameters as per the recommendations at https://jitsi-club.gitlab.io/jitsi-self-hosting/en/01-deployment-howto/03-tuning/
I found it useful to add some variables to better manipulate these values.
=> Add variables to fine tune jitsi

docs/configuring-playbook-own-webserver.md
Use playbook variables instead of textual place-holders for the domain names.
=> Improve the example Traefik config.

CHANGELOG.md, group_vars/matrix_servers, roles/matrix-ma1sd/defaults/main.yml
- Update to [newest release 2.4.0 of ma1sd](https://github.com/ma1uta/ma1sd/releases/tag/2.4.0)
- Re-enable user directory search, fixed in https://github.com/ma1uta/ma1sd/pull/45
=> Ma1sd v2.4.0

roles/matrix-jitsi/defaults/main.yml
- Update jitsi containers to latest release [stable 4627-1](https://github.com/jitsi/docker-jitsi-meet/releases)
- Notable changes: https://github.com/jitsi/docker-jitsi-meet/compare/stable-4548-1...stable-4627-1
The update should not contain any breaking changes.
=> Update Jitsi to stable-4627-1

docs/configuring-captcha.md, docs/configuring-playbook-ma1sd.md, roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
Running a public site pretty much demands Human-ness validation, and Synapse supports reCAPTCHA integration directly. It was simple enough to expose the necessary variables, so I've done it here. I've also added a quick bit of documentation to help new users figure it out.
=> Expose reCAPTCHA variables and document

roles/matrix-corporal/tasks/self_check_corporal.yml, roles/matrix-ma1sd/tasks/self_check_ma1sd.yml, roles/matrix-nginx-proxy/tasks/self_check_well_known_file.yml, roles/matrix-riot-web/tasks/self_check_riot_web.yml, roles/matrix-synapse/tasks/self_check_client_api.yml, roles/matrix-synapse/tasks/self_check_federation_api.yml
This PR allows running the matrix playbooks also in check_mode without failure due to undefined variables. 
It will enforce the execution of the uri module in check_mode, so all necessary variables are gathered.
=> Run all API self checks in check_mode

roles/matrix-bridge-mx-puppet-steam/tasks/setup_install.yml
- https://github.com/icewind1991/mx-puppet-steam is the link that's referenced by the documentation.
- The previous link, https://github.com/matrix-steam/mx-puppet-steam, is invalid/inaccessible to the public.
=> Fixed repository link for mx-puppet-steam

docs/howto-server-delegation.md
One could also remove the two variables from the docs completely,
because they are set by the playbook automatically.
Error: javax.net.ssl.SSLPeerUnverifiedException: Certificate for
<matrix.<your-domain>> doesn't match any of the subject alternative
names: [<your-domain>]
Fixes #577 (Github Issue).
=> Fix default SSL path for federation api in docs

docs/importing-postgres.md
**Note**: This PR addresses documenting the workaround only, it may be worth fixing the underlying issue.
If a Postgres dump contains ALTER TABLE ... OWNER_TO <username>
statements which set the owner to a username different from
'synapse' the post Postgres import task will fail complaining
about lack of role.
Changing the matrix_postgres_connection_username group var has no
effect. However, the ALTER TABLE statements (and accompanying comments)
can be rewritten to change the username to 'synapse', which permits the
import task to succeed.
From a sample of 1, having the owner set in this was causes no
discernable side effects on the homeserver.
=> importing-postgres.md: Add 'Troubleshooting' w/workaround for ownership

roles/matrix-ma1sd/defaults/main.yml, roles/matrix-ma1sd/tasks/setup_ma1sd.yml
The tag format used in the `ma1sd` repo have change. Versions no longer
start with 'v', and when building for non-amd64, we also need to strip
off the '-$arch' bit from the Docker image name.
Further, when building the .jar file, `ma1sd` currently names the .jar
based on the project's directory, which we call 'docker-src'. This means
other parts of the `ma1sd` build can't find the .jar file. Remedy this
by ensuring that the dir is called `docker-src/ma1sd`.
(I've proposed a patch to `ma1sd` on PR https://github.com/ma1uta/ma1sd/pull/55 to fix this: https://github.com/ma1uta/ma1sd/pull/55/commits/7b992c1060c58e2a46c814ce76a8fcc9435d89c2)
=> Fix issues building ma1sd Docker image

roles/matrix-base/tasks/server_base/setup_debian.yml
AWS Debian marketplace image does not have gpg preinstalled
https://aws.amazon.com/marketplace/pp/B0859NK4HC?ref=cns_srchrow
TASK [matrix-base : Ensure Docker's APT key is trusted] *******************************************************************************************************************************************************
fatal: [matrix.domain.com]: FAILED! => {"changed": false, "msg": "Failed to find required executable gpg in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}
Closes #590
=> Added gpg as base dependency for Debian 10

roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-element.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-dimension.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-jitsi.conf.j2
These headers add some security and I believe they are used by app.element.io and chat.mozilla.com.
I have tested them roughly and they do not seem to break our internal matrix/element/jitsi/dimension services.
=> Nginx proxy headers

docs/configuring-playbook-synapse-admin.md
I used the config sample at https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md and extended it for the new synapse admin container, so that it would be available at https://matrix.DOMAIN/synapse-admin.
Please review and edit this PR.
=> Added config sample for synapse admin with traefik 2

roles/matrix-common-after/tasks/start.yml
Make ansible check mode runs silent, for non idempotent tasks:
do not enforce service starts and stops in check_mode
=> Make ansible check mode runs silent, for non idempotent tasks

docs/configuring-playbook-client-element.md, docs/configuring-playbook-ma1sd.md, docs/configuring-playbook-ssl-certificates.md, docs/prerequisites.md, roles/matrix-base/defaults/main.yml
Hello all.
Having never used Ansible, the guide was a great help in getting a Matrix server up and running. I installed it locally to experiment and only ran into a few issues. I want to share my experience for anyone else who might run into these issues.
- The playbook requires the docker package.
- ma1sd is the 2nd most memory hungry container, so if you don't need the features you can disable it.
- Being installed locally, i used a self-signed SSL certificate. You have to add a security exception to Matrix by visiting `matrix.<your-domain>` (as well as Element of course).
I have a few questions, which I hope someone can answer:
- I am new to Ansible, so is it safe to disable ma1sd? Are there other configuration options that are depending on it?
- I had to run the ansible commands with …
=> Python requires docker package and other small improvements

roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2
Even with the v2 updates listed in #503 and partially addressed in #614, this is still needed to enable identity services to function with Element Desktop/Web. Testing on multiple clients with a clean config has confirmed this, at least for my installation.
This could be a case of a stubborn client, however making the change seems to fix the user experience. Here's the error in latest release of Element Desktop on macOS:
=> Update CORS for ma1sd

roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2
In #628 I proposed a CORS change that turns out not to be the root of the issue. Caffeine-addled diagnosis leads to sloppy thinking, and this change should be reverted. In fact, if left it will cause problems for new installations.
=> Undo ill-advised change

docs/configuring-playbook-telemetry.md
Change anonymized to more proper term as server vice this is not anonymized. Server name is the first parameter that is collected. And if server happens to be for individual use these statistics would be at personal level without any anonymising.
=> Change anonymized to general

roles/matrix-bridge-mx-puppet-instagram/templates/systemd/matrix-mx-puppet-instagram.service.j2
=> Use the same naming convention as the other mx-puppet suite.

roles/matrix-bridge-appservice-slack/defaults/main.yml
The used Docker image is no longer maintained and is outdated so it does not work anymore. 
Before upgrading existing installations, the data in the appservice-slack folder on the host server must be deleted, as the files are not compatible with the new version.
=> New docker image appservice-slack

roles/matrix-client-element/defaults/main.yml, roles/matrix-client-element/templates/config.json.j2
showLabsSettings is the new enableLabs I guess. enableLabs doesn't seem to do anything anymore. It had been deprecated for a while. I've left it enabled by default since it was previously but maybe it shouldn't be.
This PR also removes @riot-bot:matrix.org as the default welcome_user_id since it doesn't exist anymore.
=> Allow configuration of Element's bug_report_endpoint_url and showLabsSettings

group_vars/matrix_servers, roles/matrix-base/defaults/main.yml, roles/matrix-base/templates/static-files/well-known/matrix-client.j2
Support both the `im.vector.riot` and `io.element` variants in `.well-known/matrix/client`.
According to the docs, `e2ee` [is already under](https://github.com/vector-im/element-web/blob/develop/docs/e2ee.md#disabling-encryption-by-default) `io.element` however `jitsi` [is still under](https://github.com/vector-im/element-web/blob/develop/docs/jitsi.md#configuring-element-to-use-your-self-hosted-jitsi-server) `im.vector.riot`.
For now let's just maintain backward and forward compatibility for both settings since the client version is out of the control of this playbook. If somebody has a better proposal I am happy to hear it.
Also, I fixed a few remaining `*_riot_*` variables. Note that this is again a breaking change (similar to 2020-07-17), due to the variable name change.
=> Client well known compatibility

docs/maintenance-postgres.md
This follows up on the recent upgrade of the PostgreSQL container to v13.0.
=> Use up-to-date PostgreSQL container version for backups.

roles/matrix-base/defaults/main.yml, roles/matrix-base/templates/static-files/well-known/matrix-client.j2
Hi.
I had to put all the options into "io.element.e2ee" dictionary to make them work.
Actually I could not find out, how "secure_backup_required" true or false did make any difference, but it was requested in the chatroom.
The "secure_backup_setup_methods" definitely work, although it needs a tough deleting of every caching possible in the browser to see the change...
Same goes for the "default" option.
=> add variables for secure_backup_required and secure_backup_setup_methods

docs/howto-server-delegation.md
The SSL certificates should be accessible to the nginx proxy container, not the synapse container.
=> Fix docker mount instruction in documentation

roles/matrix-jitsi/defaults/main.yml
Latest stable jitsi version is `stable-5142`.
[Changelog](https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md) doesn't seem to indicate any breaking change.
**Also worth seeing:**
Changelog for this specific version: https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_5142
Full commit changelog comparing to current version (if needed): https://github.com/jitsi/jitsi-meet/compare/stable/jitsi-meet_4857...stable/jitsi-meet_5142
=> Update jitsi web to stable-5142

roles/matrix-jitsi/templates/web/interface_config.js.j2
Recording in Jitsi was disabled by default in commit e0d7d5f0, but the button is still visible in the UI. This PR removes the button from the Jitsi Web toolbar if recording is disabled.
=> Remove the recording button from the Jitsi UI if recording is disabled.

roles/matrix-bridge-appservice-discord/defaults/main.yml
After recently updating my matrix-docker-ansible-deploy installation, matrix-appservice-discord would refuse to start, logging ECONNREFUSED to https://matrix.[mydomain]:443, which was resolving to 172.18.0.2 due to the `--hostname` in mailer grabbing that hostname.
Curious why the IRC bridge didn't have this issue, I looked into it, and it was connecting to `http://matrix-synapse:8008`.  Correcting this one to that URL resolved the issue.
=> Correct inabillity for appservice-discord to connect

docs/configuring-playbook-nginx.md, roles/matrix-nginx-proxy/defaults/main.yml, roles/matrix-nginx-proxy/templates/nginx/nginx.conf.j2
Would be nice to have an option to disable the nginx access log for the proxy. This should be optional but possible.
=> add option to disable nginx access log

group_vars/matrix_servers
Otherwise the postgres upgrade fails with the following error:
```
Unexpected templating type error occurred on ({{
[matrix_postgres_connection_username]
+
matrix_postgres_additional_databases|map(attribute='username')
}}
): can only concatenate list (not "generator") to list
```
=> Fix concatenation of additional databases

docs/ansible.md, roles/matrix-base/tasks/sanity_check.yml
I have no idea if this works, I haven't tested it but it should theoretically check for the buggy version of Ansible that Ubuntu 20.04 comes with and provide a nicer warning message.
=> Check for buggy version of Ansible that Ubuntu 20.04 provides

roles/matrix-base/tasks/setup_matrix_base.yml, roles/matrix-coturn/tasks/setup_coturn.yml
This PR cleans up an old workaround.
No issues running like this for at least six months.
```
$ ansible --version
ansible 2.9.13
...
```
=> Drop the old workaround for an Ansible bug that has been fixed three years ago

group_vars/matrix_servers
- fix for error when updating in a homeserver environment with external Postgres DB:
```
TASK [matrix-bridge-appservice-slack : Ensure Matrix Appservice Slack config installed] ***************************************************************
fatal: [matrix.pub.solar]: FAILED! => {"msg": "The task includes an option with an undefined variable. 
The error was: {{ matrix_appservice_slack_configuration_yaml|from_yaml|combine(matrix_appservice_slack_configuration_extension, recursive=True) }}: {{ lookup('template', 'templates/config.yaml.j2') }}: {{ { 'nedb': 'nedb:///data', 'postgres': matrix_appservice_slack_database_connection_string, }[matrix_appservice_slack_database_engine] }}: 'dict object' has no attribute 'sqlite'
The error appears to be in …
```
=> Fix appservice-slack default db: nedb

roles/matrix-nginx-proxy/templates/usr-local-bin/matrix-ssl-lets-encrypt-certificates-renew.j2
While administering we will occasionally invoke this script interactively with the "non-interactive" switch still there, yet still sit at the desk waiting for 300 seconds for this timer to run out.
The systemd-timer already uses a 3h randomized delay for automatic renewals, which serves this purpose well.
=> When validating LE certs, do not wait for a random time

roles/matrix-base/tasks/server_base/setup_debian.yml
There is no Docker for Bullseye (Debian 11) yet, so I installed Docker for Buster (Debian 10) instead.
I have been running it for a few days now with most services enabled and haven't encountered any issues.
Future maintainer: check on https://docs.docker.com/engine/install/debian/ if Docker for Debian 11 is released, then undo this PR
=> Use Debian Buster Docker repo on Debian Bullseye

roles/matrix-postgres/templates/sql/init-additional-db-user-and-role.sql.j2
If `additional_db.username` or `additional_db.name` contains some special characters like `'-'` the _SQL commands_ will not be accepted AND ansible will not notice it. The playbook will continue, but the _db user_ will not be created.
```sh
homeserver# docker run --rm --user=996:1005 --cap-drop=ALL --env-file=/srv/matrix/_postgres/env-postgres-server --network postgres --mount type=bind,src=/tmp/matrix-postgres-init-additional-db-user-and-role.sql,dst=/matrix-postgres-init-additional-db-user-and-role.sql,ro -ti --entrypoint=/bin/sh docker.io/postgres:13.1-alpine
```
```sh
\ $ psql -h matrix-postgres --file=/matrix-postgres-init-additional-db-user-and-role.sql
psql:/matrix-postgres-init-additional-db-user-and-role.sql:9: ERROR:  syntax error at or near "-"
LINE 3:   CREATE USER …
```
=> Add double quotes 'matrix-postgres-init-additional-db-user-and-role.sql.j2' template

CHANGELOG.md, README.md, docs/configuring-playbook-etherpad.md, docs/container-images.md, group_vars/matrix_servers, roles/matrix-etherpad/defaults/main.yml, roles/matrix-etherpad/tasks/init.yml, roles/matrix-etherpad/tasks/main.yml, roles/matrix-etherpad/tasks/setup_install.yml, roles/matrix-etherpad/tasks/setup_uninstall.yml, roles/matrix-etherpad/tasks/validate_config.yml, roles/matrix-etherpad/templates/settings.json.j2, roles/matrix-etherpad/templates/systemd/matrix-etherpad.service.j2, roles/matrix-jitsi/defaults/main.yml, roles/matrix-jitsi/templates/web/custom-config.js.j2, roles/matrix-jitsi/templates/web/env.j2, roles/matrix-nginx-proxy/templates/nginx/nginx.conf.j2, setup.yml
The role takes the official Etherpad docker image, exposes it at `https://dimension.<your-domain>/etherpad`
To save time, many lines were copied from the Dimension role.
TODO:
=> Self-hosted Etherpad

docs/configuring-playbook-nginx.md
They finally deployed the 1 year old PR that fixed TLS 1.3 compatibility
=> Remove note about federation tester not working with TLS 1.3

README.md
The Link to the Slack Docker image was wrong in the README.
=> fix typo from skype to slack

roles/matrix-bridge-appservice-slack/tasks/setup_install.yml
It was missing the right variable name.
=> Fixes: a66a604e ("Selfbuild appservice-slack bridge")

roles/matrix-bridge-mautrix-signal/tasks/setup_install.yml
Changed `matrix_mautrix_signal_docker_image_force_pull` to `matrix_mautrix_signal_daemon_docker_image_force_pull` when force pulling the daemon
=> Fix wrong docker image being pulled

docs/configuring-playbook-nginx.md, docs/configuring-playbook-ssl-certificates.md, group_vars/matrix_servers, roles/matrix-nginx-proxy/defaults/main.yml
This pull request adds a new variable (`matrix_ssl_additional_domains_to_obtain_certificates_for`) which is an array of extra domain names, specified in the user's `vars.yml`. These domains get included in the `matrix_ssl_domains_to_obtain_certificates_for` variable, which is what the playbook loops over to obtain/renew certificates.
It also adds documentation to `configuring-playbook-nginx.md` for using this new variable and the already existing `matrix_nginx_proxy_proxy_http_additional_server_configuration_blocks`. This should hopefully make it clear how the nginx proxy added in this playbook can be configured to act as a reverse proxy for other services as well, reducing the need to set up your own webserver.
---
I think future work could be done to make additional reverse proxy blocks …
=> Add additional domains for Let's Encrypt certificates to be obtained

group_vars/matrix_servers, roles/matrix-etherpad/defaults/main.yml
The Etherpad container's port is exposed on all interfaces in the default configuration. That means that it's possible to access Etherpad in plaintext via http://matrix.[domain]:9001. While a user would have to stretch to actually find and deliberately use this insecure form of access, it's still a minor security flaw and should be adjusted.
This PR changes the default behaviour so that Etherpad
- does not bind to the host at all if the builtin reverse proxy is used
- only binds to a loopback port if the builtin reverse proxy is _not_ used
It's still possible for advanced users to override `matrix_etherpad_container_http_host_bind_port` and customize the behaviour to their liking.
Furthermore the PR instructs the Etherpad container to trust the reverse proxy by default, so that the logs …
=> Fix etherpad binding

docs/configuring-playbook-bridge-appservice-slack.md
Until [this issue](https://github.com/matrix-org/matrix-appservice-slack/issues/348) is fixed
=> Change the new app link to use classsic apps

ansible.cfg
The default default Ansible screen output encodes and prints error outputs as a hard to read dense line of JSON.
This patch changes the ansible-playbook command behavior for this project to output yaml instead.
Before:
```
TASK [matrix-synapse : Check Matrix Client API] **********************************************************************************************************************************
fatal: [matrix.domain.tld -> 127.0.0.1]: FAILED! => {"changed": false, "connection": "close", "content": "\n<html>\n  <head><title>404 - No Such Resource</title></head>\n  <body>\n    <h1>No Such Resource</h1>\n    <p>Sorry. No luck finding that resource.</p>\n  </body>\n</html>\n", "content_length": "167", "content_type": "text/html; charset=utf-8", "date": "Thu, 18 Feb 2021 14:52:15 GMT", …
```
=> Use the yaml callback plugin when running ansible-playbook

group_vars/matrix_servers, roles/matrix-etherpad/defaults/main.yml, roles/matrix-etherpad/tasks/validate_config.yml, roles/matrix-etherpad/templates/settings.json.j2, roles/matrix-etherpad/templates/systemd/matrix-etherpad.service.j2
PR #804 incorrectly assumed that `sqlite3` databases were supported by the official Etherpad Docker image, #874 reported this error.
To avoid any further confusion, I am removing all mention of sqlite3 in the matrix-etherpad role.
Even though it is possible to add sqlite3 support to the container, it is way more difficult to do than just connecting to the postgres database. I think the latter solution should be recommended.
=> Remove 'sqlite3' from the Etherpad role

docs/configuring-playbook-bridge-appservice-webhooks.md
fixes HTTP 400 Error: "{\"errcode\":\"M_MISSING_PARAM\",\"error\":\"Missing key 'avatar_url'\"}"
=> fix wrong json parameter in webhook documentation

README.md, docs/configuring-playbook-bridge-mx-puppet-groupme.md, docs/configuring-playbook.md, docs/container-images.md, group_vars/matrix_servers, roles/matrix-bridge-mx-puppet-groupme/defaults/main.yml, roles/matrix-bridge-mx-puppet-groupme/tasks/init.yml, roles/matrix-bridge-mx-puppet-groupme/tasks/main.yml, roles/matrix-bridge-mx-puppet-groupme/tasks/setup_install.yml, roles/matrix-bridge-mx-puppet-groupme/tasks/setup_uninstall.yml, roles/matrix-bridge-mx-puppet-groupme/tasks/validate_config.yml, roles/matrix-bridge-mx-puppet-groupme/templates/config.yaml.j2, roles/matrix-bridge-mx-puppet-groupme/templates/systemd/matrix-mx-puppet-groupme.service.j2, setup.yml
Adds support for: https://gitlab.com/robintown/mx-puppet-groupme
Modeled after the other mx-puppet bridges.
WIP as additional testing needs to be done--however, there are no currently known issues.
=> Add mx-puppet-groupme support

docs/faq.md
All examples in that section show the config to lower the memory usage on the server. However the `matrix_coturn_enabled` config is set to `true` when my understanding of it is that to lower the memory usage you have to set it to `false`
=> Update lower power config example

docs/maintenance-postgres.md
The recommended way of backing up postgres has a couple of drawbacks:
- It uses a hardcoded Postgres version that's not guaranteed to be the same as the running one
- It spawns an extra container just to perform the dump
This PR proposes a slightly more elegant solution:
- Calls pg_dumpall inside the matrix-postgres container, ensuring that the version is always compatible. This also removes the need to download potentially another image
- Stores the backup file under /matrix so a backup of the whole folder (as recommended) will also contain a consistent DB dump
- Uses absolute paths for good measure, just in case something in the ENV is messed up
=> Recommend a better way of backing up postgres

docs/configuring-playbook-prometheus-grafana.md
This document didn't describe that it is necessary to have a DNS-entry for stats sub-domain.
=> Added paragraph about updating DNS to get stats

roles/matrix-coturn/templates/systemd/matrix-coturn-reload.timer.j2, roles/matrix-nginx-proxy/templates/systemd/matrix-ssl-lets-encrypt-certificates-renew.timer.j2, roles/matrix-nginx-proxy/templates/systemd/matrix-ssl-nginx-proxy-reload.timer.j2
Currently we check for new certificates once a week. While this works well, this pull request ensures more timely updates of certifcates.
To be honest, I'm not sure this update is really needed, but following our recent discussion I promised to submit a pull request. I won't be offended if it doesn't get merged as one could easily argue that it's not a good idea to change something that already works well.
Also, we're needlessly restarting nginx every day around 6:30 a.m. with this update (and Coturn as well if enabled), although I doubt there is much going on at this time of day in most deployments ... :smile:
=> Run Let's Encrypt renewal checks daily instead of weekly.

roles/matrix-nginx-proxy/defaults/main.yml, roles/matrix-nginx-proxy/templates/nginx/nginx.conf.j2
On my deployment's nginx server I get a lot of errors stating that the default amount (1024) of worker connections is not enough. This PR allows users to configure the amount of worker connections and worker processes. 
A PR (#544) was made implementing this before, but was not completed. I have implemented the comments made on that PR in this PR.
=> Added nginx proxy worker configuration to template and defaults

roles/matrix-common-after/tasks/start.yml
During first setup postgres takes its time to get up and running, resulting in "postgres in startup" exceptions from synapse if you run without additional services that come in between. Hence suggesting increasing the time a bit to avoid having an error which heals itself and thus is hard to spot for newcomers.
=> Adjust wait timeout

roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
Added Ansible vars to be able to configure the following synapse settings:
- include_profile_data_on_invite
- require_auth_for_profile_requests
- limit_profile_requests_to_users_who_share_rooms
=> Adding vars to synapse for private servers

roles/matrix-nginx-proxy/tasks/self_check_well_known_file.yml
Self-checks against the .well-known URIs look for the HTTP header
"Access-Control-Allow-Origin" indicating that the remode endpoint
supports CORS. But the remote server is not required to include
said header in the response if the HTTP request does not include
the "Origin" header. This is in accordance with the specification
[1] stating: 'A CORS request is an HTTP request that includes an
"Origin" header.'
This is in fact true for Gitlab pages hosting and that's why the
issue was identified.
Let's specify "Origin" header in the respective uri tasks performing
the HTTP request and ensure a CORS request.
[1] https://fetch.spec.whatwg.org/#http-requests
=> matrix-nginx-proxy: specify Origin header, comply with CORS

roles/matrix-dimension/tasks/setup_install.yml
Looks like this field was forgotten in https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/80c72615c7bfdcf47644d55f033e88f4e610cf25
SequelizeDatabaseError: invalid input syntax for type smallint: "false" error in the logs when adding a custom go-neb bot in dimension.
=> Another field with 'invalid input syntax for type smallint'

roles/matrix-awx/surveys/configure_synapse_admin.json.j2, roles/matrix-bridge-appservice-slack/defaults/main.yml, roles/matrix-bridge-appservice-webhooks/defaults/main.yml
In case anyone wanted to use a domain name other than matrix.DOMAIN
=> matrix.{{ matrix_domain }} -> {{ matrix_server_fqn_matrix }}

roles/matrix-bridge-mautrix-facebook/defaults/main.yml, roles/matrix-bridge-mautrix-hangouts/defaults/main.yml, roles/matrix-bridge-mautrix-instagram/defaults/main.yml, roles/matrix-bridge-mautrix-signal/templates/registration.yaml.j2, roles/matrix-bridge-mautrix-telegram/defaults/main.yml, roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml, roles/matrix-bridge-mx-puppet-discord/defaults/main.yml, roles/matrix-bridge-mx-puppet-groupme/defaults/main.yml, roles/matrix-bridge-mx-puppet-instagram/defaults/main.yml, roles/matrix-bridge-mx-puppet-skype/defaults/main.yml, roles/matrix-bridge-mx-puppet-slack/defaults/main.yml, roles/matrix-bridge-mx-puppet-steam/defaults/main.yml, roles/matrix-bridge-mx-puppet-twitter/defaults/main.yml
This adds https://github.com/matrix-org/matrix-doc/pull/2409 to the
appservice registrations, enabling synapse to push EDUs to appservices.
=> feat: push ephemeral events to appservices

roles/matrix-client-element/defaults/main.yml
Not totally sure what this fixes but apparently it is a Docker only release
> Element Web 1.7.24.1 has been tagged to fix a compressed resources issue which only affects the official Docker build. If you don't use the official Docker build, feel free to ignore this version.
=> Upgrade Element (1.7.24 -> 1.7.24.1)

roles/matrix-base/tasks/sanity_check.yml
May fix #943
This has only been tested on an amd64 server and an arm64 server. It has not been tested on an arm32 server.
If this works properly then we might be able to automatically set `matrix_architecture` instead of making the user set it.
=> Add sanity check for server architecture

roles/matrix-coturn/templates/turnserver.conf.j2
These old versions of TLS rely on MD5 and SHA-1, both now broken, and contain other flaws. TLS 1.0 is no longer PCI-DSS compliant and the TLS working group has adopted a document to deprecate TLS 1.0 and TLS 1.1.
=> Disable TLS 1.0 and TLS 1.1 for coturn

roles/matrix-prometheus/tasks/setup_install.yml
Reverts the revert badd81e0ec95811ba98688ac185f4fb406c9c8e0 with the addition of parens. Tested on ansible 2.7.7 and 2.10.8.
=> Fix prometheus network for ansible < 2.8

roles/matrix-grafana/defaults/main.yml, roles/matrix-grafana/templates/grafana.ini.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-element.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-grafana.conf.j2
- removed duplicate X-Content-Type-Options
- removed duplicate X-Frame-Options header
- Referrer-Policy [Might consider adding variable]
- Secure flag with cookies
- matrix_grafana_content_security_policy variable for [Content Security Policy](https://grafana.com/docs/grafana/latest/administration/configuration/#content_security_policy)
=> Improve security for grafana

roles/matrix-grafana/defaults/main.yml
Latest stable grafana version is [7.5.4 (2021-04-14)](https://github.com/grafana/grafana/releases/tag/v7.5.4)
=> updated matrix_grafana_docker_image to v7.5.4

roles/matrix-prometheus-node-exporter/defaults/main.yml, roles/matrix-prometheus-node-exporter/templates/systemd/matrix-prometheus-node-exporter.service.j2
By default node-exporter docker container expose port 9100
```
**netstat -ntlp**
tcp6       0      0 :::9100                 :::*                    LISTEN      7577/node_exporter
```
=> security** node-exporter data & port publicly exposed

docs/container-images.md, roles/matrix-coturn/defaults/main.yml, roles/matrix-coturn/templates/systemd/matrix-coturn.service.j2
Coturn got an official image recently (https://github.com/coturn/coturn/pull/746) from the maintainer of `instrumentisto/coturn`. As far as I can tell the original image isn't deprecated yet but probably will be soon, e.g. https://github.com/instrumentisto/coturn-docker-image/issues/37#issuecomment-767876958.
=> Switch to official coturn image

roles/matrix-awx/surveys/access_export.json.j2, roles/matrix-awx/surveys/backup_server.json.j2, roles/matrix-awx/surveys/configure_corporal.json.j2, roles/matrix-awx/surveys/configure_dimension.json.j2, roles/matrix-awx/surveys/configure_element.json.j2, roles/matrix-awx/surveys/configure_jitsi.json.j2, roles/matrix-awx/surveys/configure_ma1sd.json.j2, roles/matrix-awx/surveys/configure_synapse.json.j2, roles/matrix-awx/tasks/customise_website_access_export.yml, roles/matrix-awx/tasks/import_awx.yml, roles/matrix-awx/tasks/set_variables_dimension.yml, roles/matrix-common-after/tasks/awx_post.yml
Create new 'Access Export' playbook for subscriptions that aren't hosting the base domain through AWX.
Allow metrics ports in firewall.
Update postgresql tuning and change default cache factor.
Added swappiness settings.
User manual updates.
Added a changelog with upgrade notes for AWX.
- Delete '{{ matrix_domain }} - 1 - Configure Website + Access Export from on-premises servers, re-provision.
- Delete 'customise_base_domain_website' variable in every on-premises subscribers matrix_vars.yml in AWX
- Set 'matrix_synapse_caches_global_factor' to '4.0' in every subscribers matrix_vars.yml in AWX
=> GoMatrixHosting v0.4.4 update

roles/matrix-grafana/defaults/main.yml, roles/matrix-grafana/templates/grafana.ini.j2
`matrix_grafana_content_security_policy_customized` to customized content security policy template.
- added 'unsafe-inline' (ignored by browsers supporting nonces/hashes) to be backward compatible with older browsers.
- added https: and http: url schemes (ignored by browsers supporting 'strict-dynamic') to be backward compatible with older browsers.
=> Grafana csp template backward compatible with older browsers

roles/matrix-synapse/defaults/main.yml
This release fixes a denial of service attack (CVE-2021-29471) against Synapse's push rules implementation. Server admins are encouraged to upgrade.
Ref: https://github.com/matrix-org/synapse/releases/tag/v1.33.2
=> Upgrade Synapse (1.33.1 -> 1.33.2)

roles/matrix-nginx-proxy/defaults/main.yml, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-base-domain.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-bot-go-neb.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-element.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-dimension.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-grafana.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-jitsi.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-riot-web.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-sygnal.conf.j2
`matrix_nginx_proxy_ocsp_stapling_enabled` Added. Default value:
```
matrix_nginx_proxy_ocsp_stapling_enabled: true
```
- OCSP Stapling eliminating the need for clients to contact the CA, with the aim of improving both security and performance.
- OCSP stapling can provide a performance boost of up to 30%
- nginx web server supports OCSP stapling since version 1.3.7.
> **warning** Nginx is lazy loading OCSP responses, which means that for the first few web requests might unable to add the OCSP response.
Learn more about what it is here:
- https://en.wikipedia.org/wiki/OCSP_stapling
- https://blog.cloudflare.com/high-reliability-ocsp-stapling/
- https://blog.mozilla.org/security/2013/07/29/ocsp-stapling-in-firefox/
=> Enable OCSP Stapling

roles/matrix-nginx-proxy/defaults/main.yml, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-base-domain.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-bot-go-neb.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-element.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-dimension.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-grafana.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-jitsi.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-riot-web.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-sygnal.conf.j2
**ssl_session_cache:**
- Creating a cache of TLS connection parameters reduces the number of handshakes 
and thus can improve the performance of application.
- Default session cache is not optimal as it can be used by only one worker process
and can cause memory fragmentation. It is much better to use shared cache.
- Learn More: https://nginx.org/en/docs/http/ngx_http_ssl_module.html
**ssl_session_timeout:**
- Nginx by default it is set to 5 minutes which is very low.
should be like 4h or 1d but will require you to increase the size of cache.
- Learn More: 
https://github.com/certbot/certbot/issues/6903
https://github.com/mozilla/server-side-tls/issues/198
**ssl_session_tickets:**
- In case of session tickets, information about session is given to the client.
Enabling this improve …
=> Optimize SSL session

docs/configuring-playbook-prometheus-grafana.md, roles/matrix-grafana/templates/grafana.ini.j2
Because grafana is running behind a reverse proxy, it will in some cases (e.g. in notifications) show links to localhost:3000 instead the web interface address.
This PR fixes that.
=> Configure root_url in granafa.ini

group_vars/matrix_servers, roles/matrix-jitsi/defaults/main.yml, roles/matrix-jitsi/templates/prosody/matrix-jitsi-prosody.service.j2
Since the update to Jitsi from 5142 to 5765 (#1037) and the corresponding changes to the nginx template to allow for the XMPP websocket client support (#1037), people using their webservers might not have been able to create calls using the web client. This manifested in the "You have been disconnected" error when starting a call.
The above commit added and {{else}} for people that disabled the internal nginx-proxy that redirected ```/xmpp-websocket``` to ```http://127.0.0.1:5280;```.
The prosody containers that ```/xmpp-websocket``` needed to redirect to lacked the necessary port binding to allow this for people running their own webserver.
To fix this I have added:
- Conditional localhost Port bindings for Jitsi Prosody systemd template
- Added variable to main.yml to allow overriding …
=> Allow Jitsi XMPP websocket support for users using own webserver.

docs/configuring-playbook-ssl-certificates.md
chain.pem file is required for `ssl_trusted_certificate`
=> OCSP Stapling SSL manually-managed

roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
Add two fields in synapse/homeserver.yaml.j2 to support AD,  
see https://github.com/matrix-org/matrix-synapse-ldap3#active-directory-forest-support
=> Synapse LDAP auth: add support for Active Directory

roles/matrix-bridge-appservice-irc/tasks/migrate_nedb_to_postgres.yml
In the edge case where the appservice IRC bridge was set up and subsequently disabled again before the migration to Postgres, trying to enable it again will trigger that migration. That tries unconditionally to stop the matrix-appservice-irc systemd service, which will fail because the service file isn't present (because the bridge had been disabled).
This PR adds a check for the presence of that service file, copied from here:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/36e583cc215f1419eb6b32821ab9ac74cd6aa4b2/roles/matrix-bridge-appservice-irc/tasks/setup_uninstall.yml#L3-L13
I've tested this on my own homeserver and it seems to solve the problem.
=> Check IRC appservice service is present before stopping it

docs/configuring-playbook-prometheus-postgres.md, group_vars/matrix_servers, roles/matrix-grafana/tasks/setup.yml, roles/matrix-prometheus-postgres-exporter/defaults/main.yml, roles/matrix-prometheus-postgres-exporter/tasks/init.yml, roles/matrix-prometheus-postgres-exporter/tasks/main.yml, roles/matrix-prometheus-postgres-exporter/tasks/setup.yml, roles/matrix-prometheus-postgres-exporter/templates/systemd/matrix-prometheus-postgres-exporter.service.j2, roles/matrix-prometheus/templates/prometheus.yml.j2, setup.yml
This commit introduces a new role that downloads and installs the
prometheus community postgres exporter  https://github.com/prometheus-community/postgres_exporter.
A new credential is added to matrix_postgres_additional_databases that
allows the exporter access to the database to gather statistics.
A new dashboard was added to the grafana role, with some refactoring
to enable the dashboard only if the new role is enabled.
I've included some basic instructions for how to enable the role in
the Docs section.
In terms of testing, I've tested enabling the role, and disabling
it to make sure it cleans up the container and systemd role.
Any feedback/rework is welcome.
=> Add support for a prometheus postgres exporter

roles/matrix-nginx-proxy/tasks/ssl/setup_ssl_lets_encrypt.yml, roles/matrix-postgres/tasks/setup_postgres.yml, roles/matrix-synapse/tasks/synapse/setup_install.yml
It's mildly annoying when trying to execute these scripts while logged in as a regular user, as the missing execute permissions will hinder autocompletion even when trying to use with sudo.
These shell scripts don't contain secrets, but may fail when ran by a regular user. The failure is due to the lack of access to the /matrix directory, and does not result in any damage.
=> Fix local/bin scripts autocompletion by adding rx perms to everyone

roles/matrix-bridge-heisenbridge/templates/systemd/matrix-heisenbridge.service.j2
Fixes running the container as an unprivileged user.
=> Heisenbridge identd on unprivileged port

roles/matrix-prometheus/defaults/main.yml
[CVE-2021-29622](https://github.com/prometheus/prometheus/security/advisories/GHSA-vx57-7f4q-fpc7)
=> prometheus security update 2.27.1

roles/matrix-client-hydrogen/tasks/init.yml
Without this the hydrogen task would fail for Ansible 2.7 even when hydrogen is not enabled.
=> fix error when running with Ansible 2.7 in the hydrogen setup

roles/matrix-base/defaults/main.yml, roles/matrix-base/tasks/server_base/setup.yml, roles/matrix-base/tasks/server_base/setup_centos8.yml
With these changes I've successfully installed and have been using the server (with a few bridges) on the CentOS Stream 8. AFAIK, everything seems to be working as it should.
This PR is basically more of a request for comments. I don't know enough Ansible to replace `ntp`/`ntpd` with `chrony`/`chronyd` only for CentOS 8+.
Also, `docker-py` is installed through `pip` since I couldn't find it in any repos (checked CentOS and EPEL). Is that a good enough solution?
=> Add support for CentOS (Stream) 8

docs/configuring-dns.md
These previously denoted optional DNS records but now optional records are a separate table so they are unnecessary.
=> Remove asterisks from configuring-dns.md

docs/maintenance-synapse.md
Recently, documentation on Synapse has been changed from .rst to .md. Therefore, the current links for the purge history API were resulting in a 404 error.
=> Correct broken documentation link

roles/matrix-synapse/tasks/main.yml
When running the playbook for a host with `matrix_synapse_enabled: false`, it would fail on task `Fail if required Synapse settings not defined`.
The easiest fix I see is checking for this condition when importing the task itself.
=> Skip importing validate_config task when Synapse is disabled

group_vars/matrix_servers, roles/matrix-prometheus/defaults/main.yml, roles/matrix-prometheus/templates/prometheus.yml.j2
I tried a few ways of doing this in various levels of insanity. This was the only way I could come up with that actually worked, but I appreciate it's using a synapse variable in the prometheus role.
=> Add worker metrics to prometheus exporter

docs/configuring-playbook-synapse.md
Example uses `{%raw}` while proper syntax is `{% raw %}`. This example doesn't work.
https://docs.ansible.com/ansible/latest/user_guide/playbooks_advanced_syntax.html#unsafe-or-raw-strings
=> Fix docs template syntax error in OIDC SSO example

roles/matrix-prometheus/defaults/main.yml
- [2.28.1 / 2021-07-01](https://github.com/prometheus/prometheus/releases/tag/v2.28.1)
=> prometheus version 2.28.0 -> 2.28.1

roles/matrix-grafana/defaults/main.yml, roles/matrix-nginx-proxy/defaults/main.yml
Upgrade certbot (v1.16.0 -> v1.17.0) nginx (1.21.0 -> 1.21.1)
=> Upgrade certbot, nginx & grafana

roles/matrix-synapse/defaults/main.yml
There are no breaking changes, but there is a database index rebuild needed, that can consume approximately 4 times more space.
Release notes: https://github.com/matrix-org/synapse/releases/tag/v1.38.0
=> Update synapse to v1.38.0

examples/apache/matrix-synapse.conf
Added missing X-Forwarded-Proto header according to the example here: https://github.com/matrix-org/synapse/blob/3fffb71254d052c54d7a6eabae8534480f021adc/docs/reverse_proxy.md
=> Added missing X-Forwarded-Proto header

roles/matrix-bot-matrix-reminder-bot/defaults/main.yml
Resolves an issue with the bot version being incompatible with Synapse  v1.38+
Issue: https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1191 
Upgrades the reminder bot to v.0.2.1 which resolves this known issue:  https://github.com/anoadragon453/matrix-reminder-bot/issues/86
=> Update main.yml for matrix-reminder-bot

group_vars/matrix_servers, roles/matrix-bridge-mautrix-telegram/defaults/main.yml, roles/matrix-bridge-mautrix-telegram/tasks/setup_install.yml
I added this changes because the docker [build file](https://mau.dev/tulir/mautrix-telegram/-/blob/c02f67e0d1dcabde598d65d346c63097e309d410/Dockerfile) contains an architecture constraint to only work for amd64 because the FROM image is amd64 only. Therefore, I mask the constraint and compile the [underlying image](https://mau.dev/tulir/lottieconverter.git) by myself and then compile the constraint mautrix-telegram image.
=> Fixed mautrix-telegram selfbuild not working on non amd64 platforms

roles/matrix-base/defaults/main.yml, roles/matrix-base/templates/static-files/well-known/matrix-server.j2, roles/matrix-nginx-proxy/defaults/main.yml, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2
**tl;dr:** Setup option to allow matrix federation fqn to be different to matrix client fqn
In some cases it might be useful to have a different domain for your matrix federation API than for your client communications.
e.g.:
- you are running the matrix-docker-ansible-deploy ecosystem behind a webproxy, which only allows `:80` and `:443` to be configured. By making the federation fqn different to client communications, you can handle the federation requests within _matrix-nginx-proxy_ separately with the nginx `server_name` key.
**Attention:** I did not checked every role and most roles does not uses federation API anyway. Therefore I am happy about advises, where these code changes to the federation domain could cause problems.
=> Make federation domain customizable

group_vars/matrix_servers, roles/matrix-bridge-mautrix-signal/defaults/main.yml, roles/matrix-bridge-mautrix-signal/tasks/setup_install.yml
I now autodetect compatible platforms of the mautrix-signal docker images via the manifest and added overlooked self-build functionality for the signal daemon.
Follow-up to  #1175
=> Fixed self-build functionality for mautrix-signal

roles/matrix-prometheus-node-exporter/defaults/main.yml
- https://github.com/prometheus/node_exporter/releases/tag/v1.2.0
=> Update prometheus node exporter (1.1.2 -> 1.2.0)

group_vars/matrix_servers, roles/matrix-bot-matrix-reminder-bot/defaults/main.yml, roles/matrix-bot-matrix-reminder-bot/tasks/setup_install.yml
I added self-build functionality to the reminder-bot similar to #1175 and #1180.  The reminder bot is now working on a Raspberry Pi 4.
=> Added selfbuild functionality to matrix-reminder-bot

roles/matrix-awx/tasks/set_variables_ma1sd.yml, roles/matrix-awx/tasks/set_variables_synapse.yml
- Set prometheus retention period as variable in create-awx-system.
- Fixed minor bugs relating to ma1sd/LDAP.
- Update the borg backup config to include the rest of /matrix and custom website folder, also fixed issue where re-provisioning blanks the recaptcha section of the 'Configure Synapse' survey, solves 'Create AWX System' issue [#16](https://gitlab.com/GoMatrixHosting/create-awx-system/-/issues/16).
- Set locale of all client servers to en_US to avoid 'Ansible Provision Server' issue [#11](https://gitlab.com/GoMatrixHosting/ansible-provision-server/-/issues/11).
Follow us on [GitLab](https://gitlab.com/GoMatrixHosting), or come say hello at [GoMatrixHosting](https://matrix.to/#/#general:gomatrixhosting.com)!
=> GoMatrixHosting v0.5.5

group_vars/matrix_servers, roles/matrix-ma1sd/defaults/main.yml, roles/matrix-ma1sd/tasks/validate_config.yml
Version 2.5.0 did not have an architecture tag.
https://hub.docker.com/r/ma1uta/ma1sd/tags?page=1&ordering=last_updated
=> Updating to ma1sd v2.5.0

roles/matrix-bridge-mautrix-signal/defaults/main.yml
The new version of the Mautrix Signal bridge is provided through a slightly changed GitLab location:
* old: 'dock.mau.dev/tulir/mautrix-signal'
* new: 'dock.mau.dev/mautrix/signal'
#1220
=> New version of Mautrix Signal bridge (version 0.2.0)

roles/matrix-bridge-appservice-irc/defaults/main.yml
See https://hub.docker.com/layers/matrixdotorg/matrix-appservice-irc/release-v0.29.0/images/sha256-4caa51e900a1d073b9349d1aaec3bd47498e06bc4e81b52e0faedda9924d5efe?context=explore
=> irc appservice image tag has a 'v' now

roles/matrix-bridge-mautrix-signal/templates/config.yaml.j2
I updated the config-template to the latest version of the project's [example-config.yaml](https://github.com/mautrix/signal/blob/master/mautrix_signal/example-config.yaml)
I changed the example-config's default in two places:
```
'{{ matrix_mautrix_signal_homeserver_domain }}': relay
```
to only relay messages of users of your own homeserver (is this a desired default?) and
```
relay:
enabled: true
```
to be able to enable relay mode for rooms via `!signal set-relay`
=> Update matrix-mautrix-signal config to 0.2.0 to enable relay mode

roles/matrix-bridge-heisenbridge/defaults/main.yml
Heisenbridge is now stable. Pinning image to 1.0.0.
=> Pin Heisenbridge to 1.0.0

roles/matrix-bridge-mautrix-facebook/defaults/main.yml
The Github link is just a redirect to Tulir's own GitLab, so I replaced the self-build link
The docker container repository was rearranged hierarchically (dock.mau.dev/tulir/mautrix-facebook -> dock.mau.dev/tulir/mautrix/facebook)
Tagged versions have been made available, thus :latest -> :v0.3.1
=> Mautrix-Facebook repo location update, pin v0.3.1

roles/matrix-bridge-mautrix-telegram/defaults/main.yml
See #1239  . Just tested, and the installation works without issues.
=> Update the docker image version for mautrix-telegram

roles/matrix-bridge-appservice-irc/defaults/main.yml
Fix incorrect docker version tag for matrix-appservice-irc
This is the fix I mentioned in the matrix channel.
Looks like there is a bug in the irc bridge docker image tag, just tried to update and it complained the tag didn't exist: Error pulling image docker.io/matrixdotorg/matrix-appservice-irc:release-v0.30.0
On docker hub, the image tag looks to me release-0.30.0 (no v)
https://hub.docker.com/r/matrixdotorg/matrix-appservice-irc/tags?page=1&ordering=last_updated
=> Fix appservice-irc version

roles/matrix-synapse/vars/workers.yml
Changes after executing the `workers-doc-to-yaml.sh` bash script to retrieve new endpoints
=> Endpoint changes for Client and media API due to migration to 1.41.0

docs/configuring-playbook-dimension.md
This avoids having to create a new room and to click the "Add widgets, bridges & bots" link (Formerly the four-squares-icon)
=> Add link to Dimension admin page

roles/matrix-synapse/defaults/main.yml
Synapse 1.41.1 Patches 2 exploits that can reveal information about rooms an user is not supposed to have access to information about.
=> Upgrade to Synaspe v 1.41.1 (Security Update)

roles/matrix-client-hydrogen/tasks/setup.yml
With https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/e913347fe15d4d1c6db0d5de8cc1026f335a02c2 the config file will never be read so Hydrogen will use matrix.org as the default server. I've added a comment explaining why it was put in this order.
=> Revert "Move some related tasks closer together in matrix-client-hydrogen"

roles/matrix-nginx-proxy/defaults/main.yml
- [nginx:1.21.3-alpine](https://hub.docker.com/layers/nginx/library/nginx/1.21.3-alpine/images/sha256-826624c15f5e49e591d80f3e0c696f92a2d5967b989017572fe241edac294a2a?context=explore)
- [certbot/certbot:v1.19.0](https://hub.docker.com/layers/certbot/certbot/v1.19.0/images/sha256-ab3c3200b23c281c96b4acce1f95cc32fcacbe55dfd2d08d422bccb8ac4b1778?context=explore)
=> Updates Certbot -> v1.19.0, nginx ->1.21.3-alpine

docs/prerequisites.md
Ubuntu ended support for 16.04 in April and it looks like Docker no longer supports 16.04 either according to https://docs.docker.com/engine/install/ubuntu/#os-requirements
Fixes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1277
=> Bump minimum supported Ubuntu version

roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.2.0
=> Upgrade Heisenbridge (1.1.1 -> 1.2.0)

roles/matrix-base/defaults/main.yml, roles/matrix-base/tasks/server_base/setup_archlinux.yml
Facing time sync issue in ubuntu 20.04 https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1029
- chrony availability and compatibility with mostly all OS.
- systemd-timesyncd is light weight and chrony more accurate, full featured.
=> migrate from ntp to systemd-timesyncd for ubuntu & Archlinux

docs/configuring-playbook-own-webserver.md, roles/matrix-etherpad/tasks/init.yml, roles/matrix-nginx-proxy/defaults/main.yml, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-jitsi.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-sygnal.conf.j2, roles/matrix-registration/tasks/init.yml, roles/matrix-synapse-admin/tasks/init.yml
This replaces `$scheme` with the contents of the `X-Forwarded-Proto` when enabled.
Not 100% certain on the variables. Creating `matrix_nginx_proxy_trust_forwarded_proto` means that you can have a completely HTTP matrix server, which I don't know if that's supported or not. Or I can move `matrix_nginx_proxy_x_forwarded_proto_value` to `roles/matrix-nginx-proxy/tasks/init.yml` and have it key off `matrix_nginx_proxy_https_enabled` instead?
I think this resolves #1132 but I'm not 100% certain people's problems there are the same as mine.
=> Support trusting the upstream server when it says the protocol is HTTPS

roles/matrix-base/tasks/server_base/setup_archlinux.yml
#1192 lead to the following error for me on Archlinux:
`TASK [matrix-base : Install host dependencies] *******************************************************************************************************************************
fatal: [matrix.***.de]: FAILED! => changed=false 
msg: |-
failed to install systemd-timesyncd: error: target not found: systemd-timesyncd`
There is no package called `systemd-timesyncd` on Archlinux. The service is installed with the [`systemd`](https://archlinux.org/packages/core/x86_64/systemd/) package itself.
I suggest removing the `systemd-timesyncd` from https://github.com/sakkiii/matrix-docker-ansible-deploy/blob/2453876eb9a463eb6e327a9f771ea2a29b9cdc49/roles/matrix-base/tasks/server_base/setup_archlinux.yml#L7
I'm not sure whether we have to put the `- …
=> Archlinux: remove package systemd-timesyncd

roles/matrix-nginx-proxy/defaults/main.yml
for `matrix_nginx_proxy_proxy_synapse_metrics_basic_auth_key`
resolves #1308
=> add how to generate htpasswd

roles/matrix-postgres/templates/systemd/matrix-postgres.service.j2
docker-ce does not like quotes around the shm-size value
=> fixes #1365

roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2
nginx matrix-synapse.conf generated by the playbook, should have `server_name` only if `matrix_nginx_proxy_enabled`
=> add server_name to matrix-synapse.conf only if matrix_nginx_proxy_enabled

roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-base-domain.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-bot-go-neb.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-element.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-hydrogen.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-dimension.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-grafana.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-jitsi.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-riot-web.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-sygnal.conf.j2
If you use a external certbot because of an external reverse proxy, the server has to be reached via ipv6 on port80.
=> Port 80 for IPv6

roles/matrix-postgres/defaults/main.yml
https://www.postgresql.org/about/news/postgresql-141-135-129-1114-1019-and-9624-released-2349/
=> Postgres Minor Updates (14.1, 13.5, 12.9, 11.14, 10.19)

roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
Hello,
currently to configure synapse email sending you need to add smtp username and password through synapse additional configuration var/block, but all other smtp connection-related vars already exposed via role vars.
This PR adds missing `smtp_user` and `smtp_pass` to synapse role defaults
=> expose smtp_user and smtp_pass to ansible configs (role: matrix-synapse)

roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2, roles/matrix-synapse/files/workers-doc-to-yaml.awk, roles/matrix-synapse/vars/workers.yml
Support for these APIs will probably be in Synapse 1.48.0 but this can get merged at any time.
=> Allow workers to serve new v3 APIs

roles/matrix-bridge-heisenbridge/defaults/main.yml
This fixes a critical compatibility issue with Synapse 1.47.
=> Upgrade Heisenbridge (1.7.0 -> 1.7.1)

group_vars/matrix_servers
This change forces ansible to decrypt the variable before using it, if encrypted with ansible-vault, to avoid the error `{"msg": "Unexpected templating type error occurred on ({{ matrix_synapse_macaroon_secret_key | password_hash('sha512') }}): secret must be unicode or bytes, not ansible.parsing.yaml.objects.AnsibleVaultEncryptedUnicode"}`
Every other variable in the playbook was found to have no problems with encryption.
The change has no negative impact on non-encrypted matrix_synapse_macaroon_secret_key variable.
=> Support encrypted matrix_synapse_macaroon_secret_key

collections/requirements.yml
I know there is an extended AWX implementation within this repository, but we use the repository since beginning in AWX without any extra functions.
Unfortunately we was forced to upgrade to latest, k8s only, AWX 19.4 and run into some problems, because I suppose a latest ansible version is used in images. In other issues this also was mentioned, related to ansible-base: (example #1363)
**Our problem:**
> ERROR! couldn't resolve module/action 'docker_network'. This often indicates a misspelling, missing collection, or incorrect module path.
Is it possible to merge this collections/requirements.yaml file into the repository, so latest Ansible and also AWX come back to compatibility without adjustments? 
I'm not fully sure if this create problems with existing AWX integration, but I think …
=> Ansible 2.10 & AWX 19.4 compatibility

roles/matrix-grafana/defaults/main.yml
https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/
=> Update Grafana from 8.3.0 to 8.3.1 due to Security Flaw

docs/self-building.md, group_vars/matrix_servers, roles/matrix-dimension/defaults/main.yml, roles/matrix-dimension/tasks/setup_install.yml
Add a self-build option for the Dimension Dockerfile.
- This helps further support running on arm64 hosts (i.e. [A1.Flex w/Oracle](https://matrix.org/docs/guides/free-small-matrix-server))
**NOTE:** A pre-built arm64 image does not currently exist for [matrix-dimension on Dockerhub](https://hub.docker.com/r/turt2live/matrix-dimension/tags)
=> Add self-build for Dimension (arm64 support)

roles/matrix-bridge-appservice-discord/defaults/main.yml, roles/matrix-bridge-mautrix-facebook/defaults/main.yml, roles/matrix-bridge-mautrix-googlechat/defaults/main.yml, roles/matrix-bridge-mautrix-hangouts/defaults/main.yml, roles/matrix-bridge-mautrix-instagram/defaults/main.yml, roles/matrix-bridge-mautrix-telegram/defaults/main.yml, roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml, roles/matrix-dimension/defaults/main.yml, roles/matrix-ma1sd/defaults/main.yml, roles/matrix-registration/defaults/main.yml
Was renamed in 087dbe4ddc80ba6308e7ee98391ea475354e8860
It is unclear to me if there is anything you actually need to adjust with these variables. It looks like that is done automatically in `matrix_servers`.
=> Fix comments about `_database_*` variables

roles/matrix-synapse/vars/workers.yml
1472958e25c729f3fb9f6c018c2df947bcae97aa reverted some of the v3 changes. I'm not sure why. Running the `workers-doc-to-yaml.sh` script right now puts them back 🤷‍♂️.
=> Run `workers-doc-to-yaml.sh`

docs/configuring-playbook-jitsi.md, roles/matrix-jitsi/defaults/main.yml, roles/matrix-jitsi/tasks/setup_jitsi_prosody.yml, roles/matrix-jitsi/tasks/util/setup_jitsi_auth.yml, roles/matrix-jitsi/tasks/validate_config.yml
This allows the playbook to create Jitsi internal authentication users without manual intervention. I'm not extremely familiar with Ansible, but it seems to work as intended and includes support for multiple user accounts.
=> Add support for creation of Jitsi internal authentication users in vars.yml

roles/matrix-bot-mjolnir/defaults/main.yml
https://hub.docker.com/r/matrixdotorg/mjolnir/tags
using the "latest" tag seems inefficient as it doesn't actually redirect to the latest release
In any case, the latest release is now 1.2.1
docker pull matrixdotorg/mjolnir:v1.2.1
=> Upgrade Mjolnir from 1.1.20 to version 1.2.1

roles/matrix-bridge-mautrix-signal/defaults/main.yml
Recently, a vulnerability in log4j was discovered. Signald uses log4j. This PR updates the path of the signald docker image from the previously recommended, but now outdated docker image at mau.dev to the [now by @tulir recommended](https://docs.mau.fi/bridges/python/signal/setup-docker.html) docker image at docker.io.
Please merge this ASAP since there is a vulnerability on all servers running signald until the fixed image gets pulled.
=> Updated signald docker image path

roles/matrix-jitsi/defaults/main.yml
Simple PR to update Jitsi to its latest version.
I've tested that it works, but am unable to test LDAP. There haven't been any changes that would affect it, however.
**Note:** Some changes have been made to Jibri configuration. As far as I understand it, its become simpler, but those working on integration should be made aware.
* e9275d5 jvb: remove deprecated option
* f40a8d5 jicofo: Handle special characters in password
* 6f56e5b web,prosody: add breakout rooms support
* 3208296 base: update base images to Debian Bullseye
* b02a689 env:  fix unexpected character bug with recent docker desktop
* b5dbfa0 misc: working on latest
* 487bcca jvb: try to use the correct IP as the default server ID
* 9e982fe examples: move to jitsi-contrib
* 192a623 jvb: add ability to configure the shutdown …
=> Update Jitsi Version (stable-6173 => stable-6727)

roles/matrix-client-element/defaults/main.yml
Ref: https://matrix.org/blog/2021/12/13/disclosure-buffer-overflow-in-libolm-and-matrix-js-sdk
=> (Security fix) Update Element 1.9.6 -> 1.9.7

roles/matrix-jitsi/templates/jvb/env.j2
The domain is invalid with space, so it shouldn't be here
=> Remove a space from XMPP_INTERNAL_MUC_DOMAIN

roles/matrix-bridge-mautrix-instagram/templates/config.yaml.j2
=> missing uppercase in instagram's bot name

roles/matrix-synapse/defaults/main.yml
This update fixes a sync issue that would cause some users to experience sync issues that could cause initial sync to completely fail.
https://github.com/matrix-org/synapse/releases/tag/v1.49.1
=> Update Synapse from 1.49.0 to 1.49.1

roles/matrix-synapse/defaults/main.yml
This upgrade is technically not needed due to 1.49.1 and 1.49.2 being identical with a lone fix to Debian packaging being the only change. 
Still some might want us to be on the absolutely latest version even tho these 2 are practically identical.
ARM64 has yet to be built so this has to wait for that before merge.
=> Update Synapse Version from 1.49.1 to 1.49.2

roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.8.2
=> Upgrade Heisenbridge (1.8.0 -> 1.8.2)

roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
This commit simply add encryption_enabled_by_default_for_room_type
variable.
Signed-off-by: Alejo Diaz <xlejo@protonmail.com>
=> Add encryption_enabled_by_default_for_room_type

roles/matrix-bridge-appservice-webhooks/defaults/main.yml
turt2live/matrix-appservice-webhooks -> redoonetworks/matrix-appservice-webhooks
the original turt2live project is almost abandoned and archived at this point. redoonetworks have applied a few essential fixes and provide a docker image.
I have been testing this for 20 days now, works as expected.
in the long run, webhooks should probably migrate to hookshot: #1486
=> switch appservice-webhooks fork

roles/matrix-bridge-mautrix-telegram/defaults/main.yml, roles/matrix-bridge-mautrix-telegram/templates/config.yaml.j2
Added defaults and edited config template for mautrix-telegram, allowing editing of MXID/displayname templates for bridged users.
This is primarily useful for removing the `(Telegram)` suffix from displaynames.
I have added the following config variables (defaults also shown):
```
matrix_mautrix_telegram_username_template: 'telegram_{userid}'
matrix_mautrix_telegram_alias_template: 'telegram_{groupname}'
matrix_mautrix_telegram_displayname_template: '{displayname} (Telegram)'
```
The defaults are the same as the current (hardcoded) config.
I have tested this on my deployment and can confirm that it works as intended.
=> Allow editing of MXID/dispname templates for mautrix-telegram users

docs/configuring-playbook-etherpad.md, roles/matrix-etherpad/defaults/main.yml, roles/matrix-etherpad/templates/settings.json.j2
Enables optional access to Etherpad's web-UI. This is useful for
managing Etherpad plugins.
Among other things, plugins makes it easy to manage/delete pads if you
install the adminpads2 plugin.
---
This seems to work for me on my server. User settings are based on the information in [`settings.json.template`](https://github.com/ether/etherpad-lite/blob/0af728ffeeba35cc7b264f3d9b8890469db1e861/settings.json.template?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L435-L473) in Etherpad's repo.
=> feat(etherpad): add optional admin web-UI access

group_vars/matrix_servers, roles/matrix-bot-honoroit/defaults/main.yml
Hi there,
To mitigate #1518 and prevent such issues in future, multiarch support was added both to the base image and to the honoroit image.
Both images support arm32, arm64 and amd64 architectures now, so no need for automatic self-building (of course, that's still possible, but default value changed to `false`).
These changes already available for the `latest` image tag, but as it works as expected, pinned release added as well.
=> matrix-bot-honoroit: disable self-build by default, update to v0.9.1

roles/matrix-bridge-mautrix-signal/templates/systemd/matrix-mautrix-signal.service.j2
Voice Messages work only if the bridge has an writable /tmp dir. The bridge needs the /tmp dir for transcoding with ffmpeg
=> Added writable /tmp dir for Mautrix Signal Bridge 

roles/matrix-bridge-beeper-linkedin/defaults/main.yml
Updates the beeper-linkedin image tag to v0.5.2.
Closes #1534
=> Updated: beeper-linkedin to v0.5.2

roles/matrix-bridge-appservice-webhooks/defaults/main.yml
Updates the appservice-webhooks image tag to v1.0.3-01 which adds arm64 builds.
Closes #1533
=> Updated: webhooks image tag to v1.0.3-01

roles/matrix-sygnal/defaults/main.yml
Updates the sygnal image tag to v0.11.0. No config changes have been made upstream
Closes #1542
=> Updated: sygnal to v0.11.0

roles/matrix-bridge-mautrix-instagram/defaults/main.yml
Hello,
I have added the version tag for this bridge as there has been a new release yesterday. This ensures that we don't break things in the future by using the latest tag, but can check if anything on our site needs to be changed.
https://github.com/mautrix/instagram/releases/tag/v0.1.2
=> Added Instagram version tag instead of latest

roles/matrix-bot-honoroit/defaults/main.yml
Honoroit updated to v0.9.2
By default Element doesn't support threads yet. To mitigate that, fallback reply-to mode was added, so now you can interract with honoroit just replying to previous messages, to avoid [such frustrations](https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1518#issuecomment-1008263296). That method considered as temporary workaround, so performance will be pretty poor on large reply-to chains, but that's better than nothing.
=> Updated Honoroit with fallback reply-to mode

roles/matrix-bridge-mautrix-telegram/defaults/main.yml, roles/matrix-bridge-mautrix-telegram/templates/config.yaml.j2, roles/matrix-bridge-mautrix-telegram/templates/systemd/matrix-mautrix-telegram.service.j2
Hi,
I've updated mautrix-telegram to v0.11.1 which seems to fix the problem regarding the database corruption when upgrading to v0.11.0 (`Fixed migrating pre-v0.11 legacy databases if the database schema had been corrupted (e.g. by using 3rd party tools for SQLite -> Postgres migration`).
I've also removed the deduplication settings from the config as they have been removed in the example config upstream as well. Lottieconverter has been updated to 3.15 so it matches the requirement of telegram.
=> Updated: telegram to v0.11.1

roles/matrix-bridge-mautrix-signal/defaults/main.yml
Hi,
mautrix-signal had an update two days ago. There has been only a small commit since then which doesn't break things for latest tag users.
https://github.com/mautrix/signal/releases/tag/v0.2.2
https://gitlab.com/signald/signald/-/releases/0.16.1
=> Added: mautrix-signal 0.2.2 & signald 0.16.1

roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml
Hi,
mautrix-whatsapp had an update a few hours ago. There has been only two smaller commits since then which doesn't break things for latest tag users (at least it seems like)
https://github.com/mautrix/whatsapp/releases/tag/v0.2.3
=> Added: mautrix-whatsapp v0.2.3 tag

roles/matrix-bridge-mautrix-twitter/defaults/main.yml
Hi,
Mautrix-twitter has been bumped to https://github.com/mautrix/twitter/releases/tag/v0.1.3 two days ago. Since then nothing much has happened over at the repo.
=> Updated: mautrix-twitter to v0.1.3

roles/matrix-prometheus-postgres-exporter/defaults/main.yml
Hi,
I've updated the postgres exporter to v0.10.1. As this update is only a minor update which only changes the logging behavior, I do not expect any breakage.
`[BUGFIX] Fix broken log-level for values other than debug. `
Closes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1540
=> Updated: prom-postgres-exporter to v0.10.1

group_vars/matrix_servers
it's required if enabled by the dimension config here:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/6eb8fb83925af055483ca797e31b5d803135e61f/roles/matrix-etherpad/tasks/init.yml#L42-L49
see also #1517
=> add etherpad to nginx wanted services

roles/matrix-bridge-mx-puppet-discord/defaults/main.yml
The scheme portion of the URL for `matrix_mx_puppet_discord_bridge_mediaUrl` in `main.yml` for matrix-bridge-mx-puppet-discord is missing a slash and causes messages to fail when sending to discord if the matrix user has a profile picture configured.
=> Add missing slash in url scheme for mediaUrl

roles/matrix-synapse/defaults/main.yml
Fixes a issue with room version 1.
Merging has to wait until ARM images are built ofc.
=> Update Synapse from 1.50.1 to 1.50.2

docs/configuring-playbook-bridge-mx-puppet-slack.md, roles/matrix-bridge-mx-puppet-slack/defaults/main.yml, roles/matrix-bridge-mx-puppet-slack/templates/config.yaml.j2
The OAuth credentials method seems to be the only viable way to
configure the mx-puppet-bridge now. Legacy tokens can no longer be
created, and the other methods (xoxs and xoxc tokens) come with warnings
about them being against Slack's terms of service.
=> feat(mx-puppet-slack): add support for OAuth client ID/secret

docs/configuring-playbook-bridge-hookshot.md
Fixes a few small 404 errors in the docs due to a missing leading slash.
=> Fixing 404 error in links to main.yml

docs/configuring-playbook-ssl-certificates.md
While working on support for Let's Encrypt DNS challenges, I just noticed that some of the endpoints the playbook retrieves certificates for are not listed in the doc.
I was not able to figure out any expected contribution format so feel free to tell me which one to use if I missed it.
Thanks in advance.
=> Add missing endpoints for SSL certificates

roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/tasks/ext/shared-secret-auth/setup_install.yml, roles/matrix-synapse/tasks/init.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
It seems to work well (and is backward compatible by default),
but suffers from this issue with Element: https://github.com/vector-im/element-web/issues/19605
=> Upgrade matrix-synapse-shared-secret-auth (1.0.2 -> 2.0)

roles/matrix-client-hydrogen/defaults/main.yml
This PR should be able to merge essentially instantly due to that all platforms self build hydrogen therefore we do not need to worry about docker image delay plus the release is 7 hours old at time of writing.
=> Update Hydrogen from v0.2.25 to v0.2.26

docs/configuring-playbook-federation.md
This is a proposed to add to the documentation information about how to change the Synapse federation port using the ansible playbook in order to allow  use with third party services such as CDNs not accepting port 8448.
=> Update for changing the federation port into the documentation

roles/matrix-bridge-mautrix-signal/tasks/init.yml
bridge requires the daemon, so start it first
=> Optimize signal bridge startup order

README.md, docs/configuring-awx-system.md, roles/matrix-awx/surveys/configure_mjolnir.json.j2, roles/matrix-awx/tasks/main.yml, roles/matrix-awx/tasks/set_variables_dimension.yml, roles/matrix-awx/tasks/set_variables_ma1sd.yml, roles/matrix-awx/tasks/set_variables_mjolnir.yml, roles/matrix-bridge-mautrix-signal/tasks/init.yml, roles/matrix-postgres/tasks/setup_postgres.yml, roles/matrix-postgres/templates/usr-local-bin/matrix-postgres-cli-non-interactive.j2
GoMatrixHosting v0.7.0 🚀
- CENTOS 8 EOL fix, curse you RedHat!! See [#33](https://gitlab.com/GoMatrixHosting/create-awx-system/-/issues/33)
- Add Mjolnir Bot section. See [#20](https://gitlab.com/GoMatrixHosting/ansible-provision-server/-/issues/20)
- Unclog discord-appservice-bot so it now works behind the wireguard proxy. See [#8](https://gitlab.com/GoMatrixHosting/matrix-docker-ansible-deploy/-/issues/8)
- Update deploy script readme and docs to reflect recent changes to GoMatrixHosting. See [#1654](https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1654)
Upgrade Notes v0.7.0 🚀
- Add the following section to every matrix_vars.yml file on AWX:
```
matrix_bot_mjolnir_enabled: false
matrix_bot_mjolnir_configuration_extension_yaml: |
"homeserverUrl": …
```
=> GoMatrixHosting v0.7.0

docs/configuring-playbook-bridge-hookshot.md, roles/matrix-bridge-appservice-webhooks/defaults/main.yml
I have this deployed and my appservice-webhooks webhooks keep working as before, it does not even create new ones, so it appears this upgrade path is clear.
=> avoid namespace collisions between webhook bridges

roles/matrix-bridge-hookshot/tasks/init.yml
add `$is_args$args` to proxy pass URL params in GET requests 
following the NGINX docs https://nginx.org/en/docs/http/ngx_http_core_module.html#var_args 
based on discussions in https://github.com/matrix-org/matrix-hookshot/issues/208
=> Fix empty body for GET requests in hookshot-bridge 

roles/matrix-bridge-hookshot/tasks/init.yml
Hello, this PR should fix Hookshot container not receiving API calls with the right path because nginx proxy was stripping the /v1 from it.
Thanks
=> fix hookshot provisioning url in nginx

docs/configuring-playbook-bridge-appservice-discord.md, roles/matrix-bridge-appservice-discord/defaults/main.yml, roles/matrix-bridge-appservice-discord/templates/config.yaml.j2
I've also expanded appservice-discord documentation to detail the different types of bridging available, and how to use them.
=> feat(appservice-discord): add disablePortalBridging bridge option

docs/configuring-playbook-bridge-mautrix-facebook.md, roles/matrix-bridge-mautrix-facebook/templates/config.yaml.j2, roles/matrix-bridge-mautrix-instagram/templates/config.yaml.j2, roles/matrix-bridge-mautrix-signal/templates/config.yaml.j2, roles/matrix-bridge-mautrix-twitter/templates/config.yaml.j2
"Community" support
- has been removed from mautrix/facebook in v0.3.3:
https://github.com/mautrix/facebook/commit/31cac6fb5e75667d272bf0daae094578add09a1f
- has been removed from mautrix/signal in v0.2.2:
https://github.com/mautrix/signal/commit/1f27a608a661118e17e2ef89412fd7ee2735b15c
- will be removed in the next mautrix/instagram release:
https://github.com/mautrix/instagram/commit/e2ae1ca503e7ab05e1f9dd703c26e4a5a2d4e517
- will be removed in the next mautrix/twitter release:
https://github.com/mautrix/twitter/commit/3893075265fc78021be773acc58203619ffaa067
"Spaces" support is currently not implemented. See also in mautrix/telegram#365, mautrix/facebook#216
=> Remove deprecated community options

roles/matrix-bridge-mautrix-facebook/defaults/main.yml, roles/matrix-bridge-mautrix-facebook/templates/config.yaml.j2, roles/matrix-bridge-mautrix-googlechat/defaults/main.yml, roles/matrix-bridge-mautrix-googlechat/templates/config.yaml.j2, roles/matrix-bridge-mautrix-instagram/defaults/main.yml, roles/matrix-bridge-mautrix-instagram/templates/config.yaml.j2, roles/matrix-bridge-mautrix-signal/defaults/main.yml, roles/matrix-bridge-mautrix-signal/templates/config.yaml.j2, roles/matrix-bridge-mautrix-telegram/defaults/main.yml, roles/matrix-bridge-mautrix-telegram/templates/config.yaml.j2, roles/matrix-bridge-mautrix-twitter/defaults/main.yml, roles/matrix-bridge-mautrix-twitter/templates/config.yaml.j2, roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml, roles/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2
This PR makes it configurable whether portal rooms created by mautrix bridges will be federatable or not.
Note: Rooms cannot transition from unfederated to federated after creation.
=> "Federate rooms" switch for mautrix bridges

roles/matrix-bridge-mautrix-facebook/templates/config.yaml.j2, roles/matrix-synapse/templates/synapse/systemd/matrix-synapse.service.j2
- bridge-mautrix-facebook: disable temporary disconnect notices
mautrix/facebook#215
- synapse: do not expose plain federation port when it's disabled
matrix_synapse_federation_port_enabled can be disabled by users, for example, when one wants to use the same port for client and federation requests (docs/configuring-playbook-federation.md).
=> mautrix-facebook, synapse: minor improvements

group_vars/matrix_servers, roles/matrix-bridge-appservice-slack/tasks/init.yml, roles/matrix-bridge-appservice-webhooks/tasks/init.yml, roles/matrix-bridge-hookshot/tasks/init.yml, roles/matrix-bridge-mautrix-facebook/defaults/main.yml, roles/matrix-bridge-mautrix-facebook/tasks/init.yml, roles/matrix-bridge-mautrix-facebook/tasks/validate_config.yml, roles/matrix-bridge-mautrix-facebook/templates/config.yaml.j2, roles/matrix-bridge-mautrix-facebook/templates/systemd/matrix-mautrix-facebook.service.j2, roles/matrix-bridge-mautrix-googlechat/tasks/init.yml, roles/matrix-bridge-mautrix-hangouts/tasks/init.yml, roles/matrix-bridge-mautrix-telegram/defaults/main.yml, roles/matrix-bridge-mautrix-telegram/tasks/init.yml, roles/matrix-bridge-mautrix-telegram/templates/config.yaml.j2, roles/matrix-bridge-mautrix-telegram/templates/systemd/matrix-mautrix-telegram.service.j2, roles/matrix-bridge-mx-puppet-slack/tasks/init.yml, roles/matrix-bridge-mx-puppet-twitter/tasks/init.yml, roles/matrix-etherpad/tasks/init.yml, roles/matrix-registration/tasks/init.yml, roles/matrix-synapse-admin/tasks/init.yml
This PR adds web login support for the Facebook bridge.
By default, it is on, as it does not seem to be a breaking change (the web login authentication method is optional, you can choose between this and the previously available "in-Matrix" login method when communicating with the bridge bot).
=> bridge-mautrix-facebook: add support for web-based login

roles/matrix-nginx-proxy/templates/prometheus/external_prometheus.yml.example.j2
For an unknown reason prometheus ignored the given "numeric" index and replaced it by 1. This made it not work properly, plus multiple workers of same types were not differentiable. With a "string" index, it works as intended.
before:
after:
=> Fix index in external_prometheus.yml.example.j2

roles/matrix-bridge-mautrix-googlechat/defaults/main.yml
Since the release is only a little over a week old, we should still merge this, especially since there have been no commits made after this release was published (https://github.com/mautrix/googlechat/releases/tag/v0.3.1)
=> Updated: matrix-googlechat to v0.3.1

roles/matrix-bridge-mautrix-facebook/templates/config.yaml.j2
The presence config key has been changed in mautrix-facebook from `presence` to `presence_from_facebook`: https://github.com/mautrix/facebook/blame/master/mautrix_facebook/example-config.yaml#L157
Relevant upstream commit: https://github.com/mautrix/facebook/commit/a8e6f57bc94a17068086b4020477db508ea1639b
This PR updates the config key in the template.
=> Fix Facebook presence config key

docs/self-building.md, group_vars/matrix_servers, roles/matrix-bridge-mx-puppet-steam/defaults/main.yml
Current icewind1991 source is broken (the main problem is a package name which changed since the latest commit in Alpine's repo). A [PR is waiting from tilosp](https://github.com/icewind1991/mx-puppet-steam/pull/27) and fix that error.
A great side effect is that this new Dockerfile built and works on arm64 (tested for months now on my RP4) :)
This PR is bringing this 2 features (change build source + self-buildable for arm64)
=> [STEAM] Move Docker source repository to a fixed version

docs/self-building.md, group_vars/matrix_servers, roles/matrix-bridge-hookshot/defaults/main.yml, roles/matrix-bridge-hookshot/tasks/setup_install.yml
As commented  in [#1505](https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1505#issuecomment-1027725206), Hookshot is buildable for arm64 and works (at least on my RP4 since I commented it). Also, this PR should close #1592 
PS : First time I do some Ansible, feel free to point out all my possible mistakes 👍
=> Add hookshot self build for arm64 and amd64

README.md, docs/configuring-playbook-backup-borg.md, group_vars/matrix_servers, roles/matrix-backup-borg/defaults/main.yml, roles/matrix-backup-borg/tasks/init.yml, roles/matrix-backup-borg/tasks/main.yml, roles/matrix-backup-borg/tasks/setup_install.yml, roles/matrix-backup-borg/tasks/setup_uninstall.yml, roles/matrix-backup-borg/tasks/validate_config.yml, roles/matrix-backup-borg/templates/config.yaml.j2, roles/matrix-backup-borg/templates/passwd.j2, roles/matrix-backup-borg/templates/sshkey.j2, roles/matrix-backup-borg/templates/systemd/matrix-backup-borg.service.j2, roles/matrix-backup-borg/templates/systemd/matrix-backup-borg.timer.j2, roles/matrix-bot-honoroit/tasks/setup_install.yml, setup.yml
Note: the used docker image [supports multiple architectures](https://gitlab.com/etke.cc/borgmatic/-/blob/main/.gitlab-ci.yml#L15) and builds weekly
Another note: we use [rsync.net borg](https://www.rsync.net/products/borg.html) and that PR was developed and tested on it, but other vendors (eg: [hetzner storage box](https://www.hetzner.com/storage/storage-box)) work in the same way, so there is no vendor-lock
=> add borg backup

roles/matrix-bridge-hookshot/defaults/main.yml
When [roles/matrix-bridge-hookshot/defaults/main.yml](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/b3176957c3cf1e0797a8d1f1796d14b91ed3d1ca#diff-928f098aacc3d3a87d932d4c7d275d20444f42d8649fc1dd4ce7f1a380813f8fR15) was edited https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/b3176957c3cf1e0797a8d1f1796d14b91ed3d1ca.  The docker image was changed to `mautrix/whatsapp`.  I assume it was copy/pasted and then was not changed.  
This pull sets the image back to `halfshot/matrix-hookshot`
=> Fix matrix-bridge-hookshot container image

roles/matrix-dendrite/defaults/main.yml, roles/matrix-dendrite/templates/dendrite/dendrite.yaml.j2
Minor changes to support Dendrite 0.8.1
Cleaned up config yaml based on [dendrite-config.yaml](https://github.com/matrix-org/dendrite/blob/main/dendrite-config.yaml) instead of [build/docker/config/dendrite.yaml](https://github.com/matrix-org/dendrite/blob/main/build/docker/config/dendrite.yaml)
=> Dendrite 0.8.1

docs/configuring-playbook-bridge-hookshot.md, group_vars/matrix_servers, roles/matrix-bridge-hookshot/defaults/main.yml, roles/matrix-bridge-hookshot/tasks/init.yml, roles/matrix-bridge-hookshot/templates/config.yml.j2
first addresses #1724
and on top upgrades hookshot to 1.4.0 https://github.com/matrix-org/matrix-hookshot/releases/tag/1.4.0, adding most importantly the new widgets feature.
=> Upgrade Hookshot (1.3.0 -> 1.4.0) 

roles/matrix-bridge-hookshot/defaults/main.yml
No API or config changes = no playbook changes, just a simple version bump
https://github.com/matrix-org/matrix-hookshot/releases/tag/1.5.0
=> Upgrade Hookshot (1.4.0 -> 1.5.0)

roles/matrix-synapse/tasks/rust-synapse-compress-state/main.yml
Increase the async timeout value defaults, as larger Matrix servers need more time to complete.
Not doing so can result in timeout errors such as;
```
ASYNC POLL on matrix.unredacted.org: jid=30536919578.3797072 started=1 finished=0
ASYNC FAILED on matrix.unredacted.org: jid=30536919578.3797072
fatal: [matrix.unredacted.org]: FAILED! => changed=false 
ansible_job_id: '30536919578.3797072'
child_pid: 3797076
finished: 1
msg: Timeout exceeded
results_file: /root/.ansible_async/30536919578.3797072
started: 1
stderr: ''
stderr_lines: <omitted>
stdout: ''
stdout_lines: <omitted>
```
=> Increase default async time for rust-synapse-compress-state

roles/matrix-synapse/defaults/main.yml
=> update synapse 1.56.0 -> 1.57.0

roles/matrix-base/defaults/main.yml, roles/matrix-grafana/tasks/setup.yml, roles/matrix-prometheus/tasks/setup_install.yml, roles/matrix-synapse/tasks/ext/encryption-disabler/setup_install.yml, roles/matrix-synapse/tasks/ext/rest-auth/setup_install.yml, roles/matrix-synapse/tasks/ext/shared-secret-auth/setup_install.yml
This PR adds automatic retries to all `get_url` actions to avoid errors like this one:
```
Request failed: <urlopen error [Errno -3] Temporary failure in name resolution>
```
The same was done to docker pulls before
=> add retires to all get_url actions

roles/matrix-bridge-appservice-slack/templates/config.yaml.j2
It is very confusing to debug why messages only go from Matrix to Slack
but not from Slack to Matrix. RTM should be enabled by default, as
that's the recommended way to make this work.
=> Slack appservice: Enable RTM by default

docs/configuring-playbook-bot-matrix-registration-bot.md, roles/matrix-bot-matrix-registration-bot/templates/systemd/matrix-bot-matrix-registration-bot.service.j2
Sorry to request to pull into master, but a hotfix is needed. I have removed a line in [matrix-bot-matrix-registration-bot.service.j2](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-bot-matrix-registration-bot/templates/systemd/matrix-bot-matrix-registration-bot.service.j2). 
If this line is left open, docker will crash when it tries to open a file that doesn't exist. Looks like this may have been left over from something. I have tested this and I was able to install it on my own server. Once this line was removed, I had no issues.
I also noticed a documentation error that referenced the wrong bot. I corrected this too.
=> HOTFIX: matrix-registration-bot, fixed systemd template that caused setup error

roles/matrix-bridge-mautrix-signal/defaults/main.yml
According to https://signald.org/articles/install/docker/#migrating-from-versions-before-0180,
This release only chowns files if the container is running as root. See also this upstream commit:
https://gitlab.com/signald/signald/-/commit/3bb7e8d2c128681473e324f811cff25e0883b88d
=> Bump signald to 0.18.1

roles/matrix-nginx-proxy/defaults/main.yml, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2
When setting `matrix_nginx_proxy_enabled: false` and enabling authentication on the metrics endpoint, the htpasswd file is hardcoded to the nginx-proxy container dir.
This changes the hardcoded value to a variable so the path can be updated.
Added a new variable in the nginx-proxy defaults `matrix_nginx_proxy_proxy_synapse_metrics_basic_auth_path` pointing to the currently hardcoded value
=> Make synapse htpasswd file path configurable

group_vars/matrix_servers
Running the setup playbook on a fresh Ubuntu 21 VM, I was getting the same error described in #1420 because I was using `ansible-vault` to encrypt the `matrix_homeserver_generic_secret_key` variable.
I implemented the same solution I saw in #1420 everywhere I found this variable and was able to get the playbook to go through successfully :smile:
=> Support ansible vault strings for homeserver secret key

roles/matrix-bridge-hookshot/defaults/main.yml
https://github.com/matrix-org/matrix-hookshot/releases/tag/1.6.1
https://github.com/matrix-org/matrix-hookshot/releases/tag/1.6.0
tl;dr:
- gitlab can be configured with commands and a widget
- rss/atom feed support
- docker image is now only 300MB instead of 1.3GB! :tada:
no api changes = easy upgrade
=> Upgrade Hookshot (1.5.0 -> 1.6.1)

roles/matrix-bridge-mx-puppet-discord/defaults/main.yml
This MR will revert the change to use beepers fork back to the upstream project.
Closes: #1801
=> Change back to original mx-puppet-discord

docs/configuring-well-known.md, examples/caddy2/Caddyfile
The suggestions for how to serve/reverse proxy .well-known files from base domain using Caddy 2 seems to be outdated. https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md#option-3-setting-up-reverse-proxying-of-the-well-known-files-from-the-base-domains-server-to-the-matrix-server
Instead what is suggested in this issue (https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1442) should be used.
=> Clarify reverse-proxying of well-known files with Caddy2

roles/matrix-bridge-appservice-slack/defaults/main.yml
Has some Threading-related improvements: https://github.com/matrix-org/matrix-appservice-slack/compare/1.10.0...1.11.0
=> Bump Slack Appservice to 1.11.0

roles/matrix-client-element/defaults/main.yml
It forwards to the correct place but might as well just update it to the current URL.
=> Update Element self build repo URL

roles/matrix-bridge-mx-puppet-discord/defaults/main.yml, roles/matrix-bridge-mx-puppet-slack/defaults/main.yml
Now that v0.1.1 is out, which depends on the functional matrix-slack-parser it works again.
=> Change back to working original mx-puppet-slack

group_vars/matrix_servers
This was a bug preventing the bot from interacting with the admin API (404). It now configures nginx so that the admin API is accessible from the outside, as synapse admin does too
=> Automatically enable admin api access via nginx

roles/matrix-postgres/defaults/main.yml
CVE: https://security-tracker.debian.org/tracker/CVE-2022-1552
Source: https://www.postgresql.org/about/news/postgresql-143-137-1211-1116-and-1021-released-2449/
Postgres 9.6 upgrade (**not a CVE fix, 9.x still vulnerable**): https://www.postgresql.org/docs/release/9.6.24/
=> Update Postgres (CVE-2022-1552 + last 9.x update)

roles/matrix-bridge-mautrix-signal/defaults/main.yml, roles/matrix-bridge-mautrix-signal/templates/config.yaml.j2, roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml, roles/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2
Hello,
This PR adds two new variables, one in each Signal & WhatsApp bridges, to be able to enable end-to-bridge encryption.
Closes #877
=> Bridge mautrix signal and mautrix whatsapp encryption

roles/matrix-bot-matrix-registration-bot/defaults/main.yml
Line 10, which sets the tag to which docker version to pull was reverted from `v1.1.15` to latest. This gets the playbook working again when a user wants to use the matrix-registration-bot.
Closes #1847
=> HOTFIX: Update Matrix-Registration-Bot main.yml

roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
When using LDAP simple bind, the `bind_dn` and `bind_password`
configuration values must not be present.
Fixes #1496
=> Fix synapse LDAP simple bind config

docs/configuring-playbook-bridge-hookshot.md
Just two links to the hookshot github pages that changed.
=> Fix dead-links in configuring-playbook-bridge-hookshot.md

roles/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2
Hello,
after taling to "tulir" in the matrix-mautrix-whatsapp room, we found out that the "null" string in status_endpoint is causing this WARN:
```
Failed to update bridge state: failed to send request: Post "null": unsupported protocol scheme "", retrying in 64 seconds
```
He told us that to fix that, any of these changes must be done to the config:
```
status_endpoint:
status_endpoint: ""
status_endpoint: null
```
Hope this helps.
=> Fix string "null" in status_endpoint

roles/matrix-synapse/templates/synapse/worker.yaml.j2
Currently, Synapse workers ignore the X-Forwarded headers, which leads to internal Docker IP addresses randomly appearing in the device list of users.
This adds the `x_forwarded: true` option to the worker config, fixing the issue.
=> Synapse workers should respect X-Forwarded headers

group_vars/matrix_servers
* synapse-admin arm64 builds available since 2021-12-17 v.0.8.4 [awesometechnologies/synapse-admin:0.8.5](https://hub.docker.com/layers/synapse-admin/awesometechnologies/synapse-admin/0.8.5/images/sha256-eb54b8660c4641641b8acd08fd2dfc94ecc3fc604860f9e8b286a38008e3f3b6?context=explore)
* coturn arm32/arm64 builds available since 2021-04-15 v.4.5.2-r0-alpine [coturn/coturn:4.5.2-r12](https://hub.docker.com/layers/coturn/coturn/coturn/4.5.2-r12/images/sha256-94887581bb1093085033be0494c3a651bd40034afba1867ddc78b8ba32dc2faf?context=explore)
=> Use prebuilt ARM images for coturn / synapse-admin

roles/matrix-jitsi/defaults/main.yml, roles/matrix-jitsi/tasks/init.yml
Support for arm64 images tracked in jitsi/docker-jitsi-meet#1214 and added in jitsi/docker-jitsi-meet#1269
fixes spantaleev/matrix-docker-ansible-deploy#1889
=> feat(jitsi+arm64): Enable Jitsi on arm64

roles/matrix-bridge-mautrix-signal/defaults/main.yml
https://gitlab.com/signald/signald/-/blob/main/releases/0.19.0.md
https://gitlab.com/signald/signald/-/blob/main/releases/0.19.1.md
https://gitlab.com/signald/signald/-/blob/main/releases/0.20.0.md
Notable changes in version `0.19.0`
- All critical data now stored in database
- Avatars, group images, attachments, etc are still stored on the disk for now
- None of these need to be kept around for signald to continue working
- New command line flag `--migrate-data` tells signald to preform all required data migrations and exit
I'm not sure if we'd like to automate this or add a hint to CHANGELOG.md about it?
=> signald: 0.18.5 -> 0.20.0

docs/configuring-well-known.md, roles/matrix-base/defaults/main.yml, roles/matrix-base/tasks/setup_well_known.yml, roles/matrix-base/templates/static-files/well-known/matrix-support.j2, roles/matrix-nginx-proxy/tasks/setup_well_known.yml
Fixes #1612
For details to the proposed (not accepted yet) MSC, see:
https://github.com/matrix-org/matrix-spec-proposals/blob/hs/proposal-admin-contact-1/proposals/1929-admin-contact.md
=> Implement MSC 1929 Homeserver Admin Contact

roles/matrix-bridge-hookshot/defaults/main.yml
No docker tag published yet, [keep an eye on it](https://hub.docker.com/r/halfshot/matrix-hookshot/tags?page=1&ordering=last_updated&name=1.8.1)
=> Update Hookshot 1.8.0 -> 1.8.1

docs/configuring-playbook-telemetry.md, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
Synapse no longer describes the stats as anonymized since the `server_name` is included.
https://github.com/matrix-org/synapse/pull/13321
=> Update telemetry documentation to more closely match upstream

roles/matrix-coturn/defaults/main.yml
**no docker tag yet**, [keep an eye on it](https://hub.docker.com/r/coturn/coturn/tags?page=1&name=4.5.2-r13)
=> Update Coturn 4.5.2-r12 -> 4.5.2-r13

roles/matrix-bridge-appservice-irc/tasks/init.yml, roles/matrix-bridge-appservice-slack/tasks/init.yml, roles/matrix-bridge-mautrix-facebook/tasks/init.yml, roles/matrix-bridge-mautrix-googlechat/tasks/init.yml, roles/matrix-bridge-mautrix-hangouts/tasks/init.yml, roles/matrix-bridge-mautrix-instagram/tasks/init.yml, roles/matrix-bridge-mautrix-telegram/tasks/init.yml, roles/matrix-bridge-mx-puppet-discord/tasks/init.yml, roles/matrix-bridge-mx-puppet-groupme/tasks/init.yml, roles/matrix-bridge-mx-puppet-instagram/tasks/init.yml, roles/matrix-bridge-mx-puppet-slack/tasks/init.yml, roles/matrix-bridge-mx-puppet-steam/tasks/init.yml, roles/matrix-bridge-mx-puppet-twitter/tasks/init.yml, roles/matrix-corporal/tasks/init.yml, roles/matrix-coturn/tasks/init.yml, roles/matrix-dynamic-dns/tasks/init.yml, roles/matrix-ma1sd/tasks/init.yml, roles/matrix-mailer/tasks/init.yml, roles/matrix-registration/tasks/init.yml, roles/matrix-synapse-admin/tasks/init.yml
Fixes self-build errors from an unsupported Ansible version that references only the Element image.
=> Fix self-build error image names

docs/configuring-playbook-backup-borg.md
After copy pasting from current documentation it had a tab. I had to attempt a couple of times to get the correct formatting on yml. Private key is base64'd lorem ipsum.
Conversation https://matrix.to/#/!cNSQwPqhHKkIZdBnvt:devture.com/$otTtC0eojvNEKI5PV3p3rqCfy9BHXfHdj8cWKY_qbwk?via=devture.com&via=matrix.org&via=virtualenigma.net
=> Borg backup provide ssh key example format

README.md
This PR fixes a 404'd link in the README.
=> Fix link to maubot docs in README

README.md, docs/configuring-playbook-bridge-mx-puppet-groupme.md, docs/container-images.md, roles/matrix-bridge-mx-puppet-groupme/defaults/main.yml
mx-puppet-groupme is no longer maintained at [https://gitlab.com/robintown/mx-puppet-groupme](https://gitlab.com/robintown/mx-puppet-groupme), so I put up a new repo at [https://gitlab.com/xangelix-pub/matrix/mx-puppet-groupme](https://gitlab.com/xangelix-pub/matrix/mx-puppet-groupme).
So far, I have bumped the dependencies and made a few quick changes to fix the docker builds and mitigate security issues. I may later consider moving it to the new fork of mx-puppet-bridge and/or rewriting it in mautrix.
=> Migrate mx-puppet-groupme to new repo

docs/configuring-playbook.md, examples/host.yml, inventory/scripts/ansible-all-hosts.sh
This is a bash script to run the playbook on multiple hosts with different credentials.
It first iterates over any `inventory/<my host>.yml` to get all the sudo passwords, and then runs the playbook on each host afterwards. The PR includes an example host file and documentation. The host file comes with yaml syntax, so that the for loop in the bash script can use the asterisk wildcard syntax: `inventory/*.yml`.
I am aware that running playbooks on multiple hosts can be done using [default ansible methods](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#using-multiple-inventory-sources). Though, this playbook ought to be usable as a standalone configuration imho.
Feel free to rephrase, extend, alter or reject anything of this contribution. Just wanted to share the …
=> run the playbook on multiple hosts with different credentials

docs/configuring-playbook-synapse-admin.md
Add a basic example how to get synapse-admin running behind Caddy v2 proxy.
=> Add example configuration for Caddy v2

roles/matrix-bridge-mautrix-telegram/defaults/main.yml
Because for telegram bridge there is a special `full` level to allow double-puppeting for users
=> Fix mautrix-telegram permissions

roles/matrix-bridge-go-skype-bridge/defaults/main.yml
According to [this commit](https://github.com/kelaresg/go-skype-bridge/commit/59e27903cd6888399706ec5b7b1757411834990c), the docker hub account did change. This PR follow this update.
Also, this new image is automatically build (latest & release) for AMD64 and ARM64 :) Don't know how to apply those informations, but it can be handy :smile:
=> [Go-Skype] Change Docker Hub repository

roles/matrix-synapse/defaults/main.yml
reintroduces support for `account_threepid_delegates.email`, which was removed in 1.64.0rc1. It remains deprecated and will be removed altogether in Synapse v1.66.0. ([#13406](https://github.com/matrix-org/synapse/issues/13406))
Deprecation Warning
-------------------
Synapse v1.66.0 will remove the ability to delegate the tasks of verifying email address ownership, and password reset confirmation, to an identity server.
If you require your homeserver to verify e-mail addresses or to support password resets via e-mail, please configure your homeserver with SMTP access so that it can send e-mails on its own behalf.
[Consult the configuration documentation for more information.](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#email)
=> Update Synapse 1.63.1 -> 1.64.0

docs/configuring-playbook-bridge-appservice-discord.md, docs/configuring-playbook-bridge-mautrix-discord.md, docs/configuring-playbook-bridge-mx-puppet-discord.md
The mautrix/discord bridge [isn't able to plumb](https://matrix.to/#/#discord:maunium.net/$94Ea7sM5eb86k_BQV6mq2XFDWiDoYuh2sHJvtcBs6qw?via=maunium.net&via=matrix.org&via=tchncs.de), 
[the developer of the bridge recommend appservice discord himself](https://matrix.to/#/#discord:maunium.net/$2buGUiAlg35kJvenaWqp6bBz0_1Yv3qv3Kfp5OM02po?via=maunium.net&via=matrix.org&via=tchncs.de).
Fixed the links which linked to https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/docs/configuring-playbook-bridge-mautrix-discord.md
=> specify which discord bridge to use; fix links

group_vars/matrix_servers
* element-web arm64 builds available since 2022-08-03 v.1.11.2 [vectorim/element-web:v1.11.2](https://hub.docker.com/layers/element-web/vectorim/element-web/v1.11.2/images/sha256-776f82281936226d91cc1b3b587f4aa28fd46934b8045427ced7c72668eda223?context=explore)
=> Use prebuilt ARM images for Element

roles/matrix-dendrite/templates/dendrite/systemd/matrix-dendrite.service.j2
This PR moves the `matrix_dendrite_process_extra_arguments` line up so that it doesn't get lost, and adds a trailing backslash.
Without this PR, anything below the `..._bind_address` lines gets lost.  I ran into this bug because I needed to enable the "Really enable open registration" option on a server in a test environment.  But even after I added it to the `_extra_arguments` variable, Dendrite still wasn't seeing it.
One possible approach would be to do figure out whether we have any extra args for the process or not.  And if we do, then add the trailing \ after the `_bind_address` lines.
Instead, here I just move the `_extra_arguments` line up so that it's no longer the last one.  Then everything is easy -- we always have the \ after the `_extra_arguments` line, and we never need one …
=> Fix Dendrite extra arguments getting lost

roles/matrix-bot-maubot/templates/config/config.yaml.j2, roles/matrix-bot-maubot/templates/systemd/matrix-bot-maubot.service.j2
I found that all my plugins (other than rss which supports postgres) broke because this config option was missing.
@moan0s
=> Add back sqlite plugin database config option to maubot

docs/configuring-playbook-bot-maubot.md, group_vars/matrix_servers, roles/matrix-bot-maubot/templates/systemd/matrix-bot-maubot.service.j2
The backslash was missing and prevented users from starting the bot
=> Fix bug that prevented user with external nginx from launch

group_vars/matrix_servers
Cinny now builds arm64 docker images since [v2.0.4](https://hub.docker.com/layers/cinny/ajbura/cinny/v2.0.4/images/sha256-a7202136f8568eb0397a3d644725a8fb7dca230e08bcfc42040238bda0382057?context=explore).
=> Use arm64 images for Cinny

roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml, roles/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2
* `matrix_mautrix_whatsapp_bridge_personal_filtering_spaces` **true** - enable spaces support
* `matrix_mautrix_whatsapp_bridge_mute_bridging` **true** - sync `muted` tag/status from whatsapp to matrix
* `matrix_mautrix_whatsapp_bridge_enable_status_broadcast` **false** - disable whatsapp status broadcast. Never saw anybody use it, but there are complaints about disk utilization when broadcasts enabled
* `matrix_mautrix_whatsapp_bridge_allow_user_invite` **true** - give invite permissions to user
=> mautrix-whatsapp config adjustements

roles/matrix-bridge-mautrix-signal/defaults/main.yml
There is no docker tag in UI, but it exists:
```
docker pull registry.gitlab.com/signald/signald:0.21.0
0.21.0: Pulling from signald/signald
2f42a0d7a7b7: Pull complete 
81c2fb1b6074: Pull complete 
7e8b9a51d6b6: Pull complete 
f6ed8fd77301: Pull complete 
64e6fa036bdc: Pull complete 
5e98b5369603: Pull complete 
f2a9b80dd9fc: Pull complete 
Digest: sha256:201cf93efba689aa0319d2a480deea8ffb7dcdfbda31ea45932fccf4c7626ab9
Status: Downloaded newer image for registry.gitlab.com/signald/signald:0.21.0
registry.gitlab.com/signald/signald:0.21.0
```
=> Update Signal daeon 0.20.0 -> 0.21.0

roles/matrix-synapse/defaults/main.yml, roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
Hello, I had to be able to change the rate limit for the invitation event on my server.
I needed to be able to add ~50+ members quickly.
Thus, I added the config for `matrix_synapse_rc_invites` the same way it was added for `matrix_synapse_rc_joins ` ( not sure why it wasn't added before ?) 
for the default values, I took them from here `https://github.com/matrix-org/synapse/blob/f4ab6a4a96ceb02e260a3d025ff6c1e6cfefe4ed/docs/usage/configuration/config_documentation.md`
=> added rc_invites configuration for synapse

README.md, docs/configuring-playbook-bridge-beeper-linkedin.md, roles/matrix-bridge-beeper-linkedin/defaults/main.yml, roles/matrix-bridge-beeper-linkedin/tasks/setup_install.yml
beeper-linkedin has moved to GitHub at https://github.com/beeper/linkedin and a new version has been published, v0.5.3.
=> Update beeper-linkedin v0.5.2 -> v0.5.3 (repo change)

roles/matrix-bridge-beeper-linkedin/defaults/main.yml
Fixes issue with beeper-linkedin tag introduced in https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2035 (sorry!). 
The new tag naming structure does not include the architecture.
=> Remove arch from beeper-linkedin tag

docs/configuring-playbook-bot-go-neb.md, docs/configuring-playbook-bot-matrix-registration-bot.md, docs/configuring-playbook-bot-maubot.md, docs/configuring-playbook-bot-mjolnir.md, docs/configuring-playbook-bridge-appservice-kakaotalk.md, docs/configuring-playbook-bridge-mautrix-discord.md, docs/configuring-playbook-bridge-mautrix-facebook.md, docs/configuring-playbook-bridge-mautrix-googlechat.md, docs/configuring-playbook-bridge-mautrix-hangouts.md, docs/configuring-playbook-bridge-mautrix-signal.md, docs/configuring-playbook-bridge-mautrix-telegram.md, docs/configuring-playbook-bridge-mautrix-whatsapp.md, docs/configuring-playbook-dimension.md, docs/configuring-playbook-email2matrix.md, docs/maintenance-synapse.md, docs/obtaining-access-tokens.md, docs/updating-users-passwords.md
Right now, the documentation pages on how to set up bots and bridges each describe how to obtain the required access token. This means a lot of redundancy. Also the documentation is not always complete, often lacking one of the two options to generate a token. 
I propose in this PR to create a dedicated page in the documentation on how to obtain an access token, and then just link to that page on other documentation pages requiring the setup of a token, similar to how there is already a dedicated page on how to register a new user. 
Please let me know what you think.
=> Create dedicated doc page on obtaining access tokens

roles/matrix-dendrite/defaults/main.yml, roles/matrix-dendrite/templates/dendrite/usr-local-bin/matrix-dendrite-create-account.j2
It currently fails with:
```
FATA[0003] Failed to create the account: unable to get nonce: Get "https://localhost:8448/_synapse/admin/v1/register": dial tcp 127.0.0.1:8448: connect: connection refused
```
Also go ahead and disable open registration by default to match the synapse defaults.
=> dendrite: fix user-registration command

roles/matrix-bridge-mautrix-telegram/defaults/main.yml, roles/matrix-bridge-mautrix-telegram/templates/config.yaml.j2
Hi,
this PR adds a variable to enable End-To-Bridge encryption for mautrix-telegram just like #1818.
It also updates the encryption configuration stanza to the latest stable upstream example config (which can be found here): https://github.com/mautrix/telegram/blob/v0.11.3/mautrix_telegram/example-config.yaml#L240-L259
=> feat(telegram-bridge): add variable to enable encryption support

docs/configuring-playbook-bot-mjolnir.md
The doc currently says that [synapse has no rate limiting config option](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bot-mjolnir.md#3-make-sure-the-account-is-free-from-rate-limiting) but links to a close issue with merged pull requests regarding this.
=> out dated doc: Synapse has a rate limiting config option

roles/matrix-dendrite/templates/dendrite/usr-local-bin/matrix-dendrite-create-account.j2
This is probably a continuation of changes made in d7ed672f7.
=> Correctly check number of arguments when creating a dendrite account

roles/matrix-conduit/defaults/main.yml, roles/matrix-conduit/templates/conduit/conduit.toml.j2
This PR exposes the Conduit configuration variable `rocksdb_max_open_files` to the playbook and sets it to a slightly higher default value.
The parameter exists to prevent RocksDB from opening too many files and exceeding the system's maximum number of open files.
By default, Conduit sets the parameter to 20 if no value is given in the config file.  Here I'm setting it to 64 instead, so that we avoid creating a bottleneck on larger systems.  Some RocksDB documentation suggests allowing for at least one open file per CPU.
=> Make Conduit's rocksdb_max_open_files parameter configurable

roles/matrix-synapse/defaults/main.yml
`one-of-each` setting for workers,  recently broke with error messages from `matrix-synapse-worker-stream-writer-0-events.service` with  `port 19111 already in use` . 
Changing `matrix_synapse_workers_stream_writer_workers_metrics_range_start` from  `19111` to `19211` seem to fixed for me the issue
=> change stream writer worker metrics range start

docs/configuring-playbook-bot-maubot.md
Add two important informations:
- The `mbc` commands must be ran in the docker container
- Not using this method prevent from using encrypted rooms with the bot
=> Improve maubot doc

roles/matrix-bot-postmoogle/tasks/setup_install.yml
Reason: during a fresh install, when there is no synapse yet, systemd unit fails to start, thus whole play fails
=> Do not restart postmoogle during installation

roles/matrix-synapse/defaults/main.yml
Updates rate limit variables to match default values as "documented" in [ratelimiting.py](https://github.com/matrix-org/synapse/blob/ac1a31740b6d0dfda4d57a25762aaddfde981caf/synapse/config/ratelimiting.py).
=> synapse: match upstream rate limit defaults

roles/matrix-dendrite/defaults/main.yml
- update to v0.10.1 (https://github.com/matrix-org/dendrite/releases/tag/v0.10.1)
=> dendrite: update image tag version

roles/matrix-bot-mjolnir/templates/production.yaml.j2
#2141 introduced a change to the config that makes mjolnir poll for reports. This change is reverted in this PR as Mjolnir is not happy to try to poll for Reports but get denied due to lack of being a homeserver admin that is required. 
If your mjolnir is homeserver admin the changes where safe but i am not going to expect all mjolnirs to be homeserver admins. There are other config flags that require it being HS admin that are not default enabled in #2141 for that very reason.
=> Fix error introduced in #2141

roles/matrix-bot-maubot/tasks/init.yml
I've got a situation where I'm using maubot with gitlab bot. 
My matrix server is setup behind a nginx configured as a proxy.
The bot is giving me error 400 : room not found on webhooks.
The proposed change is working fixes the problem in my situation. However I have not tested it on other configurations nor ran any test.
=> Update proxied nginx for maubot

roles/matrix-bot-postmoogle/defaults/main.yml, roles/matrix-bot-postmoogle/templates/env.j2
* fix `!pm send` parsing with one-word subject and body
* fix `CTE_8BIT_MISMATCH`
* add account data encryption (keys and values) support
* add catch-all mailbox support
**WARNING**: [CI job is in progress](https://gitlab.com/etke.cc/postmoogle/-/jobs/3138819456)
=> Update Postmoogle 0.9.4 -> 0.9.5

group_vars/matrix_servers
On Debian 10 (buster) at least, while the Synapse systemd service unit was referring to Goofys as `matrix-goofys` without a `.service` suffix, systemd was ignoring the goofys dependency, starting Synapse before Goofys. All other dependant units which work are using the ".service" suffix.
This generally leads to the mount path goofys using having been populated by Synapse before Goofys starts, causing it to fail due to the mount target not being empty.
The fix seems to be to ensure that the Synapse service unit refers to Goofys as `matrix-goofys.service`.
This change causes the following two lines in `/etc/systemd/system/matrix-synapse.service`:
Requires=matrix-goofys
After=matrix-goofys
To be modified to:
Requires=matrix-goofys.service
After=matrix-goofys.service
---
I believe this may …
=> fix(goofys): fix synapse systemd unit file to correctly require goofys

roles/matrix-bridge-hookshot/templates/config.yml.j2
all other bridges use that level
=> Change hookshot logging level to warn

roles/matrix-bridge-hookshot/defaults/main.yml
as per documentation: "Services that need no further configuration are enabled by default" and feeds service doesn't require it
=> Enable hookshot feeds by default

docs/configuring-playbook-jitsi.md, docs/configuring-playbook-own-webserver.md, examples/caddy2/Caddyfile
I encountered a few issues when setting up my instance, some of them caused by lacking or outdated documentation.
1. Updated the `DOCKER_HOST_ADDRESS` for Jitsi to its new name (`JVB_ADVERTISE_IPS`)
2. Moved a part of the external webserver documentation that seemed to be specific to nginx because it was in the nginx section to the generic section since the configuration needed for all external webservers on another docker network or host. Also includes an example for a default setup (Synapse + Element)
3. Updated Caddyfile to :
- Support CORS
- Update some click-jacking protection directives to use a different approach that allows different subdomains to use the website as a frame, not just the exact same origin (ex : `element.example.com` trying to use `jitsi.example.com` in an iframe) …
=> Update Caddy examples and outdated Jitsi docker env variable/documentation link

docs/configuring-playbook-bridge-mautrix-telegram.md, roles/matrix-bridge-mautrix-telegram/defaults/main.yml, roles/matrix-bridge-mautrix-telegram/templates/config.yaml.j2
Hi all,
as a bloody beginner I tried to add the ability to sync only direct-chats with the bridge, because for me TG-Groups and Channels are way to noisy ... 
I would love to have this reviewed regarding:
1. Is that the right way to extend the project?
2. Can somebody confirm the filter-mode works like this?
Regards & thanks for that really nice project!
=> Add ability to sync only direct Chats in TG-Bridge

docs/configuring-playbook.md
Had to search a few minutes for the Etherpad configuration documentation. This PR should make it easier to find.
=> docs/configuring-playbook: Add link to etherpad configuration

group_vars/matrix_servers, roles/matrix-bot-postmoogle/defaults/main.yml
* !pm send to multiple recipients at once
* !pm spamlist with wildcards and automatic migration from old spamlists
* fix mappings check with enabled catch-all
* fix false-positive error message on attachments upload
* drop arm32 support (docker images)
**Warning**: [CI job is in progress](https://gitlab.com/etke.cc/postmoogle/-/jobs/3225112942)
=> update postmoogle 0.9.7 -> 0.9.8

docs/configuring-playbook-bridge-mautrix-discord.md
You can now login/bridge using a discord token.
The `login` command still works but its [aliased to `login-qr`](https://github.com/mautrix/discord/blob/6be531685f308f081675034904d89c9e920be996/commands.go#L94).
=> update way to login to discord

roles/matrix-bridge-mautrix-signal/defaults/main.yml
ref: https://github.com/mautrix/signal/releases/tag/v0.4.1
Note that part:
> The docker image now has an option to bypass the startup script by setting the MAUTRIX_DIRECT_STARTUP environment variable. Additionally, it will refuse to run as a non-root user if that variable is not set (and print an error message suggesting to either set the variable or use a custom command).
=> Update mautrix-signal 0.4.0 -> 0.4.1

roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-base-domain.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-bot-buscarron.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-bot-go-neb.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-cinny.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-element.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-hydrogen.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-conduit.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-dendrite.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-dimension.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-grafana.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-jitsi.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-ntfy.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-riot-web.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-sygnal.conf.j2, roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2
For some tests with this playbook I currently do, I need to add the _**matrix_nginx_proxy_http_level_resolver**_ variable within all nginx configurations.
The variable already exists, is defined [here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/matrix-nginx-proxy/defaults/main.yml#L506), but is not used in any files..
During a first test, it runs without any difference for result, because default value is same then current value and the empty "else" definition is not used, because all usages are also surrounded by **matrix_nginx_proxy_enabled** check.
=> Always use resolver variable in nginx conf.d files

roles/matrix-dendrite/defaults/main.yml
- update tag to latest dendrite release (https://github.com/matrix-org/dendrite/releases/tag/v0.10.6)
=> dendrite: update tag to v0.10.6

roles/matrix-synapse/tasks/synapse/workers/init.yml
The [combine filter](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#combining-hashes-dictionaries) used for adding the Synapse `stream_writers` field in `homeserver.yaml` does not add multiple event stream writers if `matrix_synapse_workers_stream_writer_events_stream_workers_count > 1`. This results in only one event stream writer process being utilized by Synapse even if multiple event stream writers are defined.
According to the [Synapse documentation](https://matrix-org.github.io/synapse/latest/workers.html#the-events-stream), multiple event stream writers can be defined, so changing the `combine` default filter parameter from `replace` to `append` now populates `events` field with multiple writers if defined.
Synapse performance metrics on my homeserver now …
=> Fixed filter for Synapse stream_writer HS config

roles/custom/matrix-etherpad/defaults/main.yml, roles/custom/matrix-etherpad/templates/settings.json.j2
They're used to integrate AbiWord or LibreOffice to import/export Microsoft Office docs.
=> etherpad: add abiword and soffice config options, update log level

roles/custom/matrix-ma1sd/tasks/setup_install.yml, roles/custom/matrix-ma1sd/tasks/util/ensure_gradle_installed_archlinux.yml
On Ubuntu 18.04.6, when I run: `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all,ensure-matrix-users-created,start --ask-pass`
I get this error:
````
SSH password:
ERROR! couldn't resolve module/action 'community.general.pacman'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/home/redacted/spant_matrix-docker-ansible-deploy/roles/custom/matrix-ma1sd/tasks/setup_install.yml': line 77, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: Ensure gradle is installed for self-building (Archlinux)
^ here
````
This commit hopefully fixes that.
I'm not sure about the `update_cache: true` part.
=> stop gradle pacman error on ubuntu

group_vars/matrix_servers, roles/custom/matrix-bot-postmoogle/defaults/main.yml, roles/custom/matrix-bot-postmoogle/templates/env.j2
* automatic ban list (can be enabled by postmoogle admin)
* automatic greylisting (can be configured by postmoogle admin)
* internal email queue to re-send failed emails (with 45x errors) automatically
* bridging email threads ⇿ matrix threads/reply-tos (for new emails)
* reply to an email in a matrix room (in a matrix thread or with reply-to) to automatically send an email reply into the email thread
* multi-domain mode with the ability to select a domain for sending emails per room/per mailbox (all other domains will act as aliases)
* `!pm send` and thread replies send multipart emails by default (both HTML from formatted markdown and plaintext in the same email)
* speed up incoming emails by omitting MX and SMTP checks when they are not explicitly enabled
* updated deps
docker tag is …
=> update postmoogle 0.9.8 -> 0.9.9

docs/configuring-playbook-dendrite.md, docs/configuring-playbook.md, roles/custom/matrix-dendrite/defaults/main.yml, roles/custom/matrix-dendrite/templates/dendrite/dendrite.yaml.j2
Dendrite 0.10.5 added the variable `auto_join_rooms` to its configuration.
I added `matrix_dendrite_auto_join_rooms` option but I'm certain this needs to be added in a couple different places.
I'm new to jinji btw :)
=> add auto join option to dendrite config

README.md
Hi,
as the list of services that this playbook manages is getting bigger and bigger, I find the unstructured list of installable services in the Readme to be increasingly harder to read. Additionally, some information in the list is superfluous (like marking every service as optional), while some are missing information like the link to their respective documentation.
In this PR I attempt to improve the situation by splitting the services into multiple categories and using a set of tables instead of an unordered list.
More precisely I changed these things: 
- Tried to split the list of services into distinct categories
- Use tables instead of a list
- Dropped "optional" flag, as every service is now optional anyways
- Added links to the documentation where docs exist and were missing …
=> Restructure the list of services in the README.md

roles/custom/matrix-ntfy/defaults/main.yml, roles/custom/matrix-ntfy/templates/ntfy/server.yml.j2, roles/custom/matrix-ntfy/templates/systemd/matrix-ntfy.service.j2
Add the Matrix server to ntfy's exemption list. Also allow all ntfy rate limits to be configured through Ansible variables.
Reasoning: we (UnifiedPush) have seen some support requests for people not receiving notifications due to rate limits. At some point, someone using this playbook for a large-ish ntfy deployment will also run into that. Adding this as a precaution should mitigate that.
I will test this on my server soon, and then make this ready for review.
=> Exempt Matrix server from ntfy rate limit

docs/configuring-playbook-synapse.md
I'm not sure, but this should be changed to devture_postgres_... !? 
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/CHANGELOG.md#2022-11-28
```yaml
matrix_postgres_process_extra_arguments: [
"-c 'max_connections=200'"
]
```
=> matrix_ to devture_

roles/custom/matrix-bot-postmoogle/defaults/main.yml, roles/custom/matrix-bot-postmoogle/templates/env.j2
* notification when somebody creates a mailbox (enabled by env var)
* reserved mailboxes (enabled by env var)
* CC/BCC support, including multi-domain setups and thread replies
* SPF and DKIM validation (enabled by mailbox owners)
* removal of CSS in HTML part of incoming emails (the famous `@font-face`)
* section titles in `!pm help`
* do not react to edits and redactions
* reject impersonations while using postmoogle as SMTP server from your own scripts
* parallelize MX, SPF, SMTP, spamlist validations
* healthchecks.io integration
* trusted proxies
* big refactoring
**Warning**: [CI job is in progress](https://gitlab.com/etke.cc/postmoogle/-/jobs/3433938411)
=> update postmoogle 0.9.9 -> 0.9.10

docs/configuring-playbook-jitsi.md, roles/custom/matrix-jitsi/defaults/main.yml, roles/custom/matrix-jitsi/templates/prosody/env.j2
Hi Spantaleev,
I have added an option to set the max participants on a jitsi conference. The changes simply add another variable to the prosody env file based upon a user setting a specific INT variable in the playbook host-vars configuration file
=> Changes to allow a user to set the max participants on a jitsi conference

roles/custom/matrix_playbook_migration/tasks/cleanup_usr_local_bin.yml
I had a script to run ansible in a docker container (similar to [this](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/ansible.md#running-ansible-in-a-container-on-the-matrix-server-itself)) that I put at the path `/usr/local/bin/matrix-install` to match the pattern of the other matrix maintenance scripts. It got deleted during my last update by [this new task](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/3d1ea3e79ea9a89c05d022ef6a75f2a9dc897a9b).
I probably should have thought through the name/location for my script a bit more, but this change will ensure the playbook only deletes scripts from the shared directory `/usr/local/bin` that it originally created.
=> Only delete playbook scripts from /usr/local/bin

README.md
Old link was pointing at 
`https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/configuring-playbook-ma1sd.md` which 404s
New link at `https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-ma1sd.md`
=> Fix Broken ma1sd Playbook Documentation Link

roles/custom/matrix-synapse/tasks/ext/s3-storage-provider/validate_config.yml
add 'not' to fail check for  matrix_synapse_ext_synapse_s3_storage_provider_config_endpoint_url
=> add 'not' to fail check for s3_storage_provider

group_vars/matrix_servers, roles/custom/matrix-client-hydrogen/defaults/main.yml, roles/custom/matrix-client-hydrogen/tasks/setup_install.yml, roles/custom/matrix-client-hydrogen/templates/config.json.j2, roles/custom/matrix-client-hydrogen/templates/systemd/matrix-client-hydrogen.service.j2
I've just tested this, and confirmed that using the upstream Docker image for Hydrogen and bind-mounting in the config file works correctly. That is to say, it configures the Hydrogen client to use my own Matrix server etc.
I was a bit confused as to why I needed to change the case of the theme in the config file, but after doing so to make it match that of the file within the Docker image, it all seemed to behave itself.
Fixes #2294
=> Use upstream Docker image for amd64 rather than self-build

roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml
When trying to use the !pm <phone number> command, I always got some weird error. This was caused by signald and is discussed in the following issue: https://gitlab.com/signald/signald/-/issues/345
The issue was fixed in version 0.23.1, so I would like to upgrade to it. I know that the latest mautrix-signal release recommends version 0.23.0, but its developer told me in his matrix channel that the bridge does not really care about the version. I have not tested if anything breaks through this upgrade, but I can confirm that the issue is indeed solved.
=> Upgrade Signald

group_vars/matrix_servers
selectattr() returns a generator object, an iterator. This leads to an exception later, lists can't concated to iterators, only to other lists. So '| list' converts the iterator to a list and the script runs happily.
Maybe it's only my system (CentOS 7, Python 2.7) wich struggels here, but the documentation of jinja list-filters say's also, the return of selectattr() is a iterator. Anyway, this simple fix converts this to a list and everything is fine.
=> convert to list from generator

docs/configuring-playbook-bridge-mautrix-whatsapp.md, roles/custom/matrix-bridge-mautrix-whatsapp/defaults/main.yml, roles/custom/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2
This allows a user to enable the relaybot by setting a variable in `vars.yml` in the same way that the mautrix signal relaybot is configured.
=> Allow the mautrix whatsapp relaybot to be enabled with a variable

roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
note about default value - "search" is desired default, because the only purpose to integrate synapse with LDAP is to use it as identity provider for SSO
=> add mode var for synapse ext ldap auth

roles/custom/matrix-backup-borg/defaults/main.yml, roles/custom/matrix-backup-borg/tasks/setup_install.yml
New tags include postgres, borg and borgmatic versions
[ref](https://gitlab.com/etke.cc/borgmatic#docker-image-tags)
=> update borg image tag

roles/custom/matrix-bot-chatgpt/templates/systemd/matrix-bot-chatgpt.service.j2
This container needs a writable $HOME, and will fail at startup if there isn't one.
Provide one by pointing HOME to a path under the mounted /data directory.
=> Fix ChatGPT container

roles/custom/matrix-cactus-comments/defaults/main.yml, roles/custom/matrix-cactus-comments/tasks/setup_install.yml
This is a long overdue fix that enables users to use the "real" client css and cs file. It is not as beautiful as for each updated the files must be updated individually, but that is something we can't change as cactus comments decides to distribute the client this way.
PS: Might take me a while to answer feedback on this PR
=> Fix client js and css download (load compiled version)

roles/custom/matrix-dendrite/defaults/main.yml
We missed [Dendrite 0.10.9](https://github.com/matrix-org/dendrite/releases/tag/v0.10.9) but [Dendrite 0.11.0](https://github.com/matrix-org/dendrite/releases/tag/v0.11.0) is out.
=> updated dendrite to version 0.11.0

roles/custom/matrix-bridge-mautrix-slack/templates/config.yaml.j2
Supported since PR mautrix/slack/pull/13
=> mautrix-slack: add team name in channel name template

roles/custom/matrix-bridge-mautrix-facebook/defaults/main.yml, roles/custom/matrix-bridge-mautrix-facebook/tasks/inject_into_nginx_proxy.yml, roles/custom/matrix-bridge-mautrix-facebook/templates/config.yaml.j2, roles/custom/matrix-bridge-mautrix-instagram/defaults/main.yml, roles/custom/matrix-bridge-mautrix-instagram/tasks/inject_into_nginx_proxy.yml, roles/custom/matrix-bridge-mautrix-instagram/tasks/main.yml, roles/custom/matrix-bridge-mautrix-instagram/templates/config.yaml.j2, roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml, roles/custom/matrix-bridge-mautrix-signal/tasks/inject_into_nginx_proxy.yml, roles/custom/matrix-bridge-mautrix-signal/tasks/main.yml, roles/custom/matrix-bridge-mautrix-signal/templates/config.yaml.j2, roles/custom/matrix-bridge-mautrix-twitter/defaults/main.yml, roles/custom/matrix-bridge-mautrix-twitter/tasks/inject_into_nginx_proxy.yml, roles/custom/matrix-bridge-mautrix-twitter/tasks/main.yml, roles/custom/matrix-bridge-mautrix-twitter/templates/config.yaml.j2, roles/custom/matrix-bridge-mautrix-whatsapp/defaults/main.yml, roles/custom/matrix-bridge-mautrix-whatsapp/tasks/inject_into_nginx_proxy.yml, roles/custom/matrix-bridge-mautrix-whatsapp/tasks/main.yml, roles/custom/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2
Adding ability to expose metrics endpoints of mautrix bridges which supports it.
=> Mautrix metrics

roles/custom/matrix-prometheus/defaults/main.yml
Docker images are released now so this change can now be pushed.
=> Update Prometheus to v2.42.0 from v2.41.0

docs/configuring-playbook-bot-draupnir.md
A small formating error managed to sneak its way past our review in the Draupnir docs. So this PR fixes it.
=> Fix formating error in Draupnir docs

group_vars/matrix_servers
Dimension,Mjolnir and Drapunir all crash if they lack HS connectivity upon startup. For mjolnir this was "fixed" with the introduction of a potentially very BAD flaw and therefore its recomended in some circles to stick to 1.6.1 or move to Drapunir that does not have the flaw. Dimension also has this behavior but unknown if its intentional like Mjolnir pre 1.6.2 or like Drapunir where its intentionally kept. All these services will recover smoothly after HS connectivity is established. By moving the priority to a higher value this should make it so we start these services later in the chain allowing the full proxy chain to start if using the intregrated proxy. If using an external proxy and only using the Helper if running Synapse this issue is mittigated but i think we should not only …
=> Fix Dimension,Mjolnir and Drapunir crashing upon startup just to recover. 

roles/custom/matrix-bot-draupnir/defaults/main.yml
https://github.com/Gnuxie/Draupnir/releases/tag/v1.80.0
Docker Image built and ready to go. Since Mjolnir did not build for ARM Draupnir does not either so we dont have to wait for ARM images.
=> Upgrade Drapunir from 1.8.0 Beta to 1.8.0 release.

roles/custom/matrix-base/defaults/main.yml, roles/custom/matrix-base/tasks/validate_config.yml, roles/custom/matrix-base/templates/static-files/well-known/matrix-client.j2
As the title says, only add element related entries to client well-known if element is enabled.
=> fix: only add element related entries to client well-known if element is enabled

roles/custom/matrix-bot-postmoogle/defaults/main.yml
* live SSL certificates reload on file changes (e.g., on automatic certs renewal)
* print all errors when trying connection to an SMTP server
=> Update postmoogle 0.9.12 -> 0.9.13

roles/custom/matrix-bot-postmoogle/defaults/main.yml
* make banlist consistent
* proper multi-error message
* ignore "." MX hosts
* try recipient domain directly, even when MX records found, but failed
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/postmoogle/-/pipelines/777596940)
=> update postmoogle 0.9.13 -> 0.9.14

docs/configuring-playbook-own-webserver.md
Otherwise the public hookshot url will use http and not https
=> Add `matrix_playbook_ssl_enabled: true` to configuring-playbook-own-webserver.md

docs/configuring-playbook-own-webserver.md
Without `matrix_nginx_proxy_https_enabled: true` the playbook won't generate the https related parts of `/matrix/nginx-proxy/conf.d/matrix-domain.conf`. So the Matrix Server would not be accessible over https://matirx.{base-domain}.
=> Added matrix_nginx_proxy_https_enabled to the own-nginx documentation

roles/custom/matrix-bot-draupnir/defaults/main.yml, roles/custom/matrix-bot-draupnir/templates/production.yaml.j2
Updates the config to include options from upstream for easier changes. Also by upgrading we finally get the new ban constructor working. It was broken last release and fixed due to me submitting logs from the error. This release does share the same flaw as its predecessor tho of having incorrect version string. This release calls it self `v1.80.0-5-g64e721d` and last release called it self `v1.80.0-beta.0-23-g5e2a175`
=> Update Draupnir from v1.80.0 to v1.80.1

roles/custom/matrix-client-element/defaults/main.yml, roles/custom/matrix-client-element/templates/config.json.j2
Element web client has ability to set default phone country code to use when login via phone number. By default it is 'GB' but can be changed by setting ['default_country_code'](https://github.com/vector-im/element-web/blob/a26be2665fc1ba55842a613a154cddab5bdb32e6/docs/config.md#default-settings) in 'config.json'. So I've added a new variable to configure it when needed.
=> Allow configure default country code in element welcome page.

CHANGELOG.md, docs/configuring-playbook-own-webserver.md
The old docs would lead to a port collision because both the traefik container as well as the fronting reverse proxy would try to bind to port 8448.
The old documentation for the nginx proxy used port 8449 as the local bind port so I added that one to the traefik documentation as well.
=> Fix documentation when fronting traefik with another reverse proxy

roles/custom/matrix-base/templates/bin/remove-all.j2
Currently the `remove-all.j2` script (or `/matrix/bin/remove-all`) removes all matrix systemd services but leaves `devture-traefik.service`. If more devture services are added in the future they will also be left running.
=> remove devture services in remove-all script

roles/custom/matrix-bot-chatgpt/defaults/main.yml, roles/custom/matrix-bot-chatgpt/templates/env.j2
OpenAI changed the model a month ago and broke the bot. This bump fixes it and adds the default model.
=> Bump ChatGPT version and add new config settings

group_vars/matrix_servers, roles/custom/matrix-dendrite/defaults/main.yml, roles/custom/matrix-dendrite/tasks/validate_config.yml, roles/custom/matrix-dendrite/templates/dendrite/dendrite.yaml.j2
Dendrite added a new API, `relay_api`, which requires a new database.
fixes: #2571
related: #2567
=> add database for Dendrite's relay API - fixes #2571

roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
When you've configured SSO, it may be useful to disable password authentication to only allow users to connect through it.
Note: I did commit through Github UI, it may be preferable to squash when merging
=> Add ability to disable password auth

group_vars/matrix_servers
Docker binds ports `devture_traefik_config_entrypoint_web_port` (80), `devture_traefik_config_entrypoint_web_secure_port` (443), and `matrix_federation_public_port` (8448) for Traefik,
If `matrix_federation_public_port` is set to 443, docker attempts to bind to 443 twice and consequently fails.
`matrix_federation_public_port` is bound only if it is not set to `devture_traefik_config_entrypoint_web_port` and `devture_traefik_config_entrypoint_web_secure_port`.
This way, Traefik uses the existing entrypoint.
=> fix(traefik): Ignore federation endpoint if entrypoint with port already exists

docs/configuring-playbook-synapse.md
Please review, I believe this note in the docs is no longer necessary. This was added in https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/05819056bc16b7e5ba2e75060bf1e9dcb003f999 but this PR is not a complete revert of that commit. There used to be another note, but I don't know if it should be re-added ? I let you check.
----
Similar to:
https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/362954aeab35398e3cd6cd5e735f3fade338b022
This warning was added because of:
https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/2090
The problem has since been fixed by:
https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/e9e84341a91fb0013469d74ee8c88c2edb5ad3a5
This current patch was provoked by: …
=> Removing warning that no longer applies

roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
Without conversion to string vault encrypted variables doesn't decrypt
Same conversion is used for database password https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2#L864
=> Fix recaptcha vars ansible-vault compatibility

docs/configuring-playbook-ldap-auth.md, roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
This commit enables [matrix-synapse-ldap3](https://github.com/matrix-org/matrix-synapse-ldap3) to support N-number of backup servers, according to their documentation "[the]  first available server is used"
=> Add support for backup LDAP servers

roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml
0.23.1 no longer syncs groups properly, the solution is to use 0.23.2, which works as expected. Thanks to `@boris:tilt303.org` for helping me uncover this.
=> Update signald version

roles/custom/matrix-bot-chatgpt/defaults/main.yml
update matrix_bot_chatgpt_version to 3.1.0 adding support for gpt-4, reverse proxy and custom api url
=> Update matrix chatgpt bot  (v3.0.0 -> v3.1.0)

roles/custom/matrix-dendrite/defaults/main.yml, roles/custom/matrix-dendrite/tasks/setup_install.yml
Recently I needed to add an option to self-build dendrite in order to [apply a bug patch](https://github.com/matrix-org/dendrite/issues/2902#issuecomment-1489937931) that's not yet in any official release.
The actual build itself is done with a `ansible.builtin.command` rather than a `community.docker.docker_image`, because [the dendrite Docker image uses the BUILDPLATFORM variable](https://github.com/matrix-org/dendrite/blob/aa1bda4c58d20e7d14267f9c87fab8efd7ae36ad/Dockerfile#L6), which is a [BuildKit/buildx feature](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/), and according to the [`community.docker.docker_image` documentation](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html):
> Building …
=> Adds a self build option for dendrite

docs/configuring-playbook-own-webserver.md, examples/caddy2/Caddyfile, examples/caddy2/Caddyfile.deprecated, examples/caddy2/README.md, examples/nginx/README.md
Because I was so scared by touching my reverse proxy setup without having an example to follow, I postponed upgrading my matrix server until now. Today I finally decided to do the upgrade and discovered that guessing the correct cofiguration was actually not that hard.
To save others from this hurdle, I decided to add my Caddyfile as an example. Because the old example Caddyfile could still be of use, I did not remove it, but renamed it to `Caddyfile.deprecated`. To make clear what is what, I finally updated the `README.md` heavily inspired by the one of the nginx example.
=> add updated Caddyfile example

roles/custom/matrix-bridge-hookshot/tasks/setup_install.yml
For Issue #2718 
This is a fix for matrix-hookshot v4.1.0. PR #2714 
This will cause errors for people using <v4.1.0.
=> Fix for hookshot validation failure

roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
YAML hooks to have all users searchable and prefer local user search.
This is to mimic the behaviour of Teams and Slack.
=> Create hooks for user search ability

docs/configuring-playbook-synapse-s3-storage-provider.md, roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/tasks/ext/s3-storage-provider/validate_config.yml, roles/custom/matrix-synapse/templates/synapse/ext/s3-storage-provider/env.j2, roles/custom/matrix-synapse/templates/synapse/ext/s3-storage-provider/media_storage_provider.yaml.j2
I have an EC2 instance that I deployed my stack to. I wanted to use the S3 storage provider but I'm not too keen on creating IAM users (and especially access keys) when I don't have to [so I assigned an IAM role directly to my EC2 instance. ](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-metadata.html)
The playbook just needed a few tiny tweaks so that it can optionally stop expecting the `matrix_synapse_ext_synapse_s3_storage_provider_config_access_key_id` and `...secret_access_key` variables. 
By setting the variable `matrix_synapse_ext_synapse_s3_storage_provider_config_ec2_instance_profile` to `true` in your host vars, the access key id/secret will not be expected by the playbook and will not be provided to the server, allowing instance metadata to get picked up. The …
=> Support EC2 instance metadata for S3 storage provider

playbooks/matrix.yml, requirements.yml
As discussed in #2738 - this PR fixes installing the "ansible-role-aux" role on NTFS.
Tested using `just roles` and `just setup-all`.
=> Fix installing 'aux'-role on NTFS

roles/custom/matrix-bridge-mautrix-googlechat/defaults/main.yml
From the changelog:
> Switched to web app API to make authentication work again. This will require all users to relogin.
=> Update mautrix-googlechat 0.4.0 -> 0.5.0

requirements.yml
**Warning**: no 1.9.0 tag yet - https://hub.docker.com/r/etherpad/etherpad/tags?page=1&name=1.9.0
=> Update etherpad 1.8.18 -> 1.9.0

docs/configuring-playbook-turn.md
I was very surprised by the fact that a rather important configuration option for Coturn was "hidden" in the Hosts file, but not mentioned here. 
Therefore my suggestion is to explicitly mention it here, as I believe that is that natural for people to look.
=> Explain the option of manually defining your public IP in the documentation for Coturn

README.md, docs/configuring-playbook-matrix-media-repo.md, docs/configuring-playbook-prometheus-grafana.md, docs/configuring-playbook-s3.md, group_vars/matrix_servers, roles/custom/matrix-media-repo/defaults/main.yml, roles/custom/matrix-media-repo/tasks/main.yml, roles/custom/matrix-media-repo/tasks/setup_install.yml, roles/custom/matrix-media-repo/tasks/setup_uninstall.yml, roles/custom/matrix-media-repo/templates/grafana/media-repo.json, roles/custom/matrix-media-repo/templates/media-repo/env.j2, roles/custom/matrix-media-repo/templates/media-repo/media-repo.yaml.j2, roles/custom/matrix-media-repo/templates/media-repo/systemd/matrix-media-repo.service.j2, roles/custom/matrix-nginx-proxy/defaults/main.yml, roles/custom/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2, roles/custom/matrix-prometheus-services-connect/defaults/main.yml, roles/custom/matrix-synapse/defaults/main.yml, setup.yml
I have added a role for the matrix-media-repo project (https://github.com/turt2live/matrix-media-repo) to the playbook for our own server deployments, and wanted to share changes upstream since there was previous interest in adding this to the playbook #67
This role supports out-of-box setup of the matrix-media-repo with any of the homeservers from this playbook, along with integrating with the other services in this playbook  like Postgres, NGINX, Prometheus, and Grafana.
=> Added matrix-media-repo role

docs/configuring-playbook-mautrix-bridges.md, roles/custom/matrix-base/defaults/main.yml, roles/custom/matrix-bridge-appservice-kakaotalk/defaults/main.yml, roles/custom/matrix-bridge-appservice-kakaotalk/templates/config.yaml.j2, roles/custom/matrix-bridge-mautrix-facebook/defaults/main.yml, roles/custom/matrix-bridge-mautrix-facebook/templates/config.yaml.j2, roles/custom/matrix-bridge-mautrix-instagram/defaults/main.yml, roles/custom/matrix-bridge-mautrix-instagram/templates/config.yaml.j2, roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml, roles/custom/matrix-bridge-mautrix-whatsapp/defaults/main.yml
WhatsApp, Signal, Instagram, Facebook and KakaoTalk bridges support it, others may follow later.
Ref (mautrix): https://docs.mau.fi/bridges/general/relay-mode.html
=> add global bridges relay mode switch

roles/custom/matrix-bridge-mautrix-gmessages/templates/config.yaml.j2
The current config defaults to not using the variable it's created for logging, as well as logging to a file as well as to the journal.
This updates it to use the existing variable, and removes the logging to file.
This will change everyone who's already installed it from 'debug' to 'warn' as the configuration file that did not use the variable was for 'debug' while the default for the variable is 'warn'
=> Gmessage bridge: Remove file logging, and add existing log level variable to config

roles/custom/matrix-client-element/defaults/main.yml
Element's logo's location was moved a few versions ago and currently points to a non-existent path.
=> Update Element logo location

docs/configuring-playbook-bot-matrix-registration-bot.md
variable need to be named:
matrix_bot_matrix_registration_bot_bot_password
and not:
matrix_bot_matrix_registration_bot_password
Dont know if it need fixed in every rule or just change the docs
=> Fix Variable Registration bot

roles/custom/matrix-bot-chatgpt/defaults/main.yml, roles/custom/matrix-bot-chatgpt/templates/env.j2
This creates a variable and sets it to the default given in the example env from the bot's github page.
This will be handy so the bot can be more easily configured to reply to things in different ways.
=> Create and set default for chatgpt prompt

docs/configuring-playbook-sliding-sync-proxy.md, group_vars/matrix_servers, roles/custom/matrix-base/defaults/main.yml, roles/custom/matrix-base/templates/static-files/well-known/matrix-client.j2
Starting from version `0.6.0` conduit natively supports some sync v3 (sliding-sync) features.
https://gitlab.com/famedly/conduit/-/releases/v0.6.0
https://gitlab.com/famedly/conduit/-/merge_requests/501
=> Advertise sliding-sync support when using conduit

group_vars/matrix_servers, roles/custom/matrix-bot-draupnir/defaults/main.yml
In addition to bugfixes from a version bump this version is also the first version to support Arm as prebuilt containers. This was as far as i am aware contributed due to that arm based container deployment is used by Draupnir Contributors.
So huraa one less docker image that you have to self build if on Arm.
=> Update Draupnir from 1.83.0 to 1.84.0

docs/configuring-playbook-bridge-appservice-discord.md, docs/configuring-playbook-bridge-appservice-webhooks.md
Add an extra step in the documentation. As of Synapse 1.90.0 backwards compatibility for appservice authorization needs to be explicitly turned on for these bridges to work. Fixes the issue I had in #2840.
=> Update docs for older appservice bridges to enable legacy authorization

CHANGELOG.md, README.md, docs/configuring-playbook-bot-draupnir.md, roles/custom/matrix-bot-draupnir/defaults/main.yml, roles/custom/matrix-bot-draupnir/templates/production.yaml.j2
This PR updates Draupnir from 1.84.0 to 1.85.0. 
Adds new config flag to the config and adds a new easy to access option for the newly introduced ACL control. 
The ability to not make the bot scream because you denied it ACL powers is common enough as a desire it seems to make it sensible to add for easy access. Its like one of like 3 attributes in the config that users might want to change the others being Control room, Homeserver (that we do for the user) and ACL sending disabled. 
The setting starts disabled as upstream recomends but you can enable it if you want to. 
This PR also changes the upstream Git repository as Draupnir changed git Repository as its now under a newly created github organisation instead of under Gnuxie/Draupnir
=> Update Draupnir from 1.84.0 to 1.85.0

roles/custom/matrix-bridge-mautrix-gmessages/defaults/main.yml
The default branch of [mautrix-gmessages](https://github.com/mautrix/gmessages) is `main` not `master`.
=> Fix mautrix-gmessages branch

roles/custom/matrix-bridge-beeper-linkedin/defaults/main.yml
no pinned releases from 2022, security fix available with latest only
=> Update beeper-linkedin 0.5.4 -> latest (security fix)

docs/configuring-playbook-synapse-admin.md
the old one is deprecated (says the page at the link target), and refers to this new one.
=> Update Admin-API link

examples/apache/matrix-synapse.conf
This PR extends MSC1929 integration with an example for the Apache config to run your own webserver.
=> Update apache example for support discovery

.gitattributes
[The line 7 of .editorconfig](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/0393bd63562bf958205614d7f7d467aa9a48cf32/.editorconfig#l7) specifies that all files use lf line endings. However if the repository is cloned on Windows and the user has `core.autocrlf = true`, they will end up with crlf line endings on everything with text editors configured to use lf line endings (although they may autodetect that).
`.gitattributes` of `* text=auto eol=lf` enables end of line normalization for checked in files that are detected as text and checks them out with lf line-endings regardless of the platform overriding `core.autocrlf`.
- https://www.git-scm.com/docs/gitattributes#_end_of_line_conversion
As an alternative to this pull request, the offending line in `.editorconfig` …
=> Add .gitattributes with checking out with lf line endings

docs/configuring-playbook-sliding-sync-proxy.md
It's no longer necessary, as the Element X app now lets you configure the homeserver through the gui at first run
=> Remove mention of the need for manual compilation of Element X for custom homeserver

group_vars/matrix_servers, roles/custom/matrix-user-verification-service/defaults/main.yml, roles/custom/matrix-user-verification-service/tasks/setup_install.yml, roles/custom/matrix-user-verification-service/templates/systemd/matrix-user-verification-service.service.j2
Currently v3.0.0 tested with no issues.
So remove matrix_user_verification_service_docker_image from groups_vars.
/.npm must be writable or an error will be reported.
=> add self-build for matrix_user_verification

roles/custom/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2
exchanged `^~` with `~` as a pattern matching in the location part. I am very sure, that it only works using `~`. I am not quite sure though, if this is the right way to do it, because `~` is probably more expensive than `^~`
the rewrite has to be behind the definition of the $backend. Otherwise nginx will fail to work. This is probably because "break" goes directly to the proxy_pass which uses $backend.
=> Update matrix-domain.conf.j2 - trying to fix issue #2954

docs/configuring-playbook-sliding-sync-proxy.md
Quoting upstream:
> Element X Android and Element X iOS apps are in a similar state.
> 
> https://github.com/vector-im/element-x-android/issues/911
=> Remove mention of Android Element X being less feature complete than the iOS version

roles/custom/matrix-media-repo/defaults/main.yml, roles/custom/matrix-media-repo/tasks/main.yml, roles/custom/matrix-media-repo/tasks/validate_config.yml, roles/custom/matrix-media-repo/templates/media-repo/media-repo.yaml.j2, roles/custom/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2
Changes:
- Updated matrix media repo to v1.3.3
- Updated configuration values that were added/removed from versions v1.2.13 to v1.3.3
- Flattened defaults configuration structure for easier editing
- Fixed issue where media uploads throw errors when exceeding nginx `client_max_body_size`
=> Updated matrix media repo to v1.3.3

README.md
Notced the old playbooks were finally archived. Figured it would be a good time to remove them and replace with the successor in the README.md
=> Update README.md: add mash-playbook, remove archived playbooks

README.md, docs/configuring-dns.md, docs/configuring-playbook-client-element.md, docs/configuring-playbook-client-hydrogen.md, docs/configuring-playbook-jitsi.md, docs/configuring-playbook-riot-web.md, docs/configuring-playbook-sliding-sync-proxy.md, roles/custom/matrix-base/defaults/main.yml, roles/custom/matrix-client-element/defaults/main.yml, roles/custom/matrix-client-element/tasks/setup_install.yml, roles/custom/matrix-client-element/templates/welcome.html.j2, roles/custom/matrix-client-hydrogen/defaults/main.yml, roles/custom/matrix-client-schildichat/tasks/setup_install.yml, roles/custom/matrix-client-schildichat/templates/welcome.html.j2
As mentioned in issue https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3043 some components (e.g. hydrogen) were not accessible anymore due to the recent renaming of Vector-im.
Here are some updates of the links to prevent future breakdowns and fix hydrogen.
*Might not be complete as I can't test all components at once.*
=> [#3043] vector im now element hq

docs/configuring-playbook-matrix-media-repo.md, roles/custom/matrix-media-repo/defaults/main.yml
The MMR v1.3.3 update resulted in some config variable name changes, so updating docs to reflect that. Additional changes:
* ~~Added `matrix_media_repo_database_password` variable in the quickstart for users to change~~
* Removed placeholder password value from defaults
* Changed default value of `matrix_media_repo_datastore_s3_opts_temp_path` since temp directory is not created by the playbook
=> Updated MMR docs with updated fields in main.yaml

docs/configuring-well-known.md
In nginx reverse-proxy, when the upstream server relies on SNI, the reverser-proxy may return 502 by follow error:
```
*10 SSL_do_handshake() failed (SSL: error:0A000410:SSL routines::sslv3 alert handshake failure:SSL alert number 40) while SSL handshaking to upstream, client: 172.19.0.1, server: example.host, request: "GET /.well-known/matrix/client HTTP/2.0", upstream: "https://<ip>/.well-known/matrix/client", host: "<domain>"
```
This problem often arises when the upstream server is behind the CDN, setting `proxy_ssl_server_name` to `on` will solve it.
=> Fix "SSL_do_handshake() failed" in nginx reverse-proxy

group_vars/matrix_servers, roles/custom/matrix-media-repo/defaults/main.yml, roles/custom/matrix-media-repo/tasks/setup_install.yml, roles/custom/matrix-media-repo/templates/media-repo/labels.j2, roles/custom/matrix-media-repo/templates/media-repo/systemd/matrix-media-repo.service.j2, roles/custom/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2
Changes:
* Added Traefik support for the MMR role
* Fixed federation media download failures when using NGINX
* Changed internal MXC link format from `mxc://matrix.DOMAIN/hash` to `mxc://DOMAIN/hash`
=> MMR reverse proxy updates

group_vars/matrix_servers
However, bot still needs manual access token adjustments, ref: https://github.com/matrixgpt/matrix-chatgpt-bot/issues/258
=> add automatic registration of chatgpt bot's user (if password is provided)

roles/custom/matrix-synapse-reverse-proxy-companion/templates/nginx/conf.d/matrix-synapse-reverse-proxy-companion.conf.j2
This PR adds `keepalive` on each of the Synapse worker upstreams, and uses HTTP 1.1 with persistent connections.  This allows the reverse proxy companion to re-use its connections to the workers, reducing the need for TCP round-trips for 3-way handshake and teardown.
This is in keeping with Nginx best practices https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#no-keepalives
The expectation is that this change should improve performance when the server is under heavy load.  Load test results can be provided in a day or two to support or refute this hypothesis.
=> Add keepalive on worker upstreams and use persistent connections

roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml, roles/custom/matrix-bridge-mautrix-signal/templates/config.yaml.j2
As mentioned here https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3079#issuecomment-1877373963 here is an analog configuration with the whatsapp bridge.
The value can still be overridden in the inventory vars.
Default to `true`
=> [#3082] Analog Signal spaces configuration with rest of playbook

examples/reverse-proxies/apache/README.md, examples/reverse-proxies/caddy2/README.md, examples/reverse-proxies/haproxy/README.md, examples/reverse-proxies/nginx/README.md
Just a few broken links in docs I was looking at right when the repo changed :dizzy_face:
Did the clickity-click test on the PR version and they point at current locations.
=> Update broken links in reverse proxies docs

docs/configuring-playbook-traefik.md
Added docu on how to host another server behind traefik to the docu file about configuring traefik.
All configuration options were succsessfully tested in my own deployment.
=> Added docu on how to host another server behind traefik.

roles/custom/matrix-synapse-reverse-proxy-companion/defaults/main.yml, roles/custom/matrix-synapse-reverse-proxy-companion/templates/systemd/matrix-synapse-reverse-proxy-companion.service.j2, roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/tasks/synapse/workers/util/setup_files_for_worker.yml, roles/custom/matrix-synapse/templates/synapse/systemd/matrix-synapse-worker.service.j2, roles/custom/matrix-synapse/templates/synapse/systemd/matrix-synapse.service.j2
* Added extra systemd service arguments  to matrix-synapse-reverse-proxy-companion and synapse workers
* Added extra arguments to the master synapse service that only apply to that container
One use-case we are using this for is to limit docker container CPU utilization for specific synapse processes and other services in the playbook.
=> Added extra systemd service arguments to synapse workers and proxy companion

roles/custom/matrix-synapse/templates/synapse/ext/s3-storage-provider/bin/migrate.j2, roles/custom/matrix-synapse/templates/synapse/ext/s3-storage-provider/bin/shell.j2
Container needs attachment to postgres network also.
When trying to run the s3 storage migration (or shell) script this issue popped up:
```
s3_media_upload: error: Could not connect to postgres database: could not translate host name "matrix-postgres" to address: Temporary failure in name resolution
```
This PR fixes that
=> Fix s3-storage migrate and shell

docs/howto-srv-server-delegation.md
The path rule was not working because for federation fo work it needs several endpoints.
Two of them are not under /_matrix/federation : 
- /_matrix/key
- /_matrix/media
=> Update SRV delegation docs

examples/reverse-proxies/nginx-proxy-manager/README.md
As of v2.11.1 of nginx-proxy-manager (NPM) the custom locations definition causes the proxy to fail running. I believe this is because the custom locations config is duplicating options NPM includes by default in a proxy host.
=> Update nginx-proxy-manager readme 

docs/configuring-playbook-bridge-mautrix-signal.md
With the `|` the yaml is interpreted and saved to the configuration as a string and mautrix-signal doesn't start with the failure:
```
Feb 20 19:05:28 h3002795.stratoserver.net matrix-mautrix-signal[685899]: Ignoring incorrect config field type !!str at bridge->permissions
Feb 20 19:05:28 h3002795.stratoserver.net matrix-mautrix-signal[685899]: Feb 20, 2024 18:05:28 FTL Configuration error error="bridge.permissions not configured"
```
Without the `|` it is written to the config correctly.
=> Fix documentation bug in configuring-playbook-bridge-mautrix-signal.md

roles/custom/matrix-synapse-reverse-proxy-companion/defaults/main.yml
We noticed that the reporting function in Element is broken, at least when using the 'specialized-workers' preset. Requests seem to land on a worker, which is then confused and returns 404.
This changes the `main_override_locations_regex` of the reverse proxy companion to ensure that requests to `/_matrix/client/v3/rooms/<roomid>/report/<message>` always land on the main process.
=> Ensure reports always land on the synapse main process

roles/custom/matrix-bridge-mautrix-meta-instagram/defaults/main.yml, roles/custom/matrix-bridge-mautrix-meta-instagram/templates/config.yaml.j2, roles/custom/matrix-bridge-mautrix-meta-messenger/defaults/main.yml, roles/custom/matrix-bridge-mautrix-meta-messenger/templates/config.yaml.j2
unifying with other mautrix bridges
=> mautrix-meta: enable spaces; add a hint into the display name

roles/custom/matrix-media-repo/defaults/main.yml, roles/custom/matrix-media-repo/templates/media-repo/media-repo.yaml.j2
MMR was updated to v1.3.4 via https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/2d4b96e0c5a904857bc440d0a4d49fcade11fa8f, which added support for media redirects. This PR adds the corresponding config options for enabling the feature.
=> Added MMR media redirect config options

roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
That allows using different logical db id if needed
=> add matrix_synapse_redis_dbid var

.gitignore, flake.lock, flake.nix
- The `flake.lock` file should be committed to the repo
- `nix-direnv` creates the `.direnv` directory so we need to ignore it
=> chore: fix nix flake

roles/custom/matrix-synapse/tasks/synapse/setup_install.yml
I managed to make this project work on Synology DSM 7.2 by replacing the original Docker command with the `devture_systemd_docker_base_host_command_docker` variable.
After that, I specified the DSM Docker location in my vars file as follows:
`devture_systemd_docker_base_host_command_docker: "/usr/local/bin/docker`
It would be appreciated if this change can be approved.
=> Resolve Synology DSM 7.2 Docker Command Issue 

group_vars/matrix_servers, requirements.yml
Emails are supposed to be sent from matrix@matrix.DOMAIN, not matrix@DOMAIN by default, especially when you care about deliverability and have SPF, DMARC, DKIM, and rDNS set to matrix.DOMAIN to have fully-featured email service on the DOMAIN and don't have conflicts between them
=> exim-relay: fix dkim permissions, fix sender address

roles/custom/matrix-bridge-hookshot/defaults/main.yml
Hookshot tries to connect to Redis/KeyDB on the wrong port when enabling encryption. Ending up with this:
```
Apr 19 11:14:21 matrix matrix-hookshot[764426]: [ioredis] Unhandled error event: Error: connect ECONNREFUSED 172.20.0.2:6739
Apr 19 11:14:21 matrix matrix-hookshot[764426]:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
Apr 19 11:14:21 matrix matrix-hookshot[764426]: [ioredis] Unhandled error event: Error: connect ECONNREFUSED 172.20.0.2:6739
Apr 19 11:14:21 matrix matrix-hookshot[764426]:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
Apr 19 11:14:21 matrix matrix-hookshot[764426]: [ioredis] Unhandled error event: Error: connect ECONNREFUSED 172.20.0.2:6739
Apr 19 11:14:21 matrix matrix-hookshot[764426]:     at …
```
=> fix(hookshot): incorrect Redis port

roles/custom/matrix-conduit/templates/labels.j2
I have to preface this with an image macro that we refer to as `dogscience` at work, since I have no experience with Traefik and very little experience with Ansible.
I was trying out all three homeserver implementations. Synapse and Dendrite worked fine, but Conduit kept throwing this error in Element:
> Can't connect to homeserver - please check your connectivity,
All requests (e.g. to `https://matrix.example.com/_matrix/client/versions`) were throwing `404 page not found` errors.
Inspecting the Docker container using `sudo docker inspect`, I found that the working Dendrite container had these two labels:
```
"traefik.http.routers.matrix-dendrite-public-client-api.entrypoints": "web-secure",
"traefik.http.routers.matrix-dendrite-public-client-api.rule": "Host(`matrix.example.com`) && …
```
=> [Conduit] Fix internal client API Traefik config

roles/custom/matrix-client-element/defaults/main.yml, roles/custom/matrix-client-element/templates/welcome.html.j2
- Provoked by: [Migrate translations to keys and switch to Localazy](https://github.com/element-hq/element-web/commit/c525b633bdb4801086999048295d0d4e5e296d6f#diff-3bbccf505f97c801dfb746d577c2ded291ce3f2ba9fdec55ac856565608a93e4)
- Schildi-Chat: Not affected yet (still using Weblate)
=> [Element] Fix translation on welcome screen

roles/custom/matrix-bridge-hookshot/defaults/main.yml
The conditional check 'matrix_hookshot_experimental_encryption_enabled and matrix_hookshot_cache_redisUri == ''' failed. The error was: An unhandled exception occurred while templating '{{ ('redis://' + matrix_hookshot_cache_redis_host + ':' + matrix_hookshot_cache_redis_port) if matrix_hookshot_cache_redis_host else '' }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ ('redis://' + matrix_hookshot_cache_redis_host + ':' + matrix_hookshot_cache_redis_port) if matrix_hookshot_cache_redis_host else '' }}): can only concatenate str (not \"int\") to str. can only concatenate str (not \"int\") to str
=> fix redis port type

roles/custom/matrix-bridge-hookshot/defaults/main.yml
matrix_hookshot_github_oauth_redirect_uri was adding an extra https in front of matrix_hookshot_urlprefix, which already included that.
```yaml
matrix_hookshot_urlprefix: "https://{{ matrix_hookshot_public_hostname }}{{ matrix_hookshot_public_endpoint }}"
matrix_hookshot_github_oauth_redirect_uri: "https://{{ matrix_hookshot_urlprefix }}{{ matrix_hookshot_github_oauth_endpoint }}"
```
This caused the `redirect_uri` in hookshot's config to have `https://https://{{ url }}`.
=> Remove duplicate https from hookshot redirect_uri

roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/tasks/ext/synapse-auto-accept-invite/setup_install.yml
Add missing configuration matrix_synapse_ext_synapse_auto_accept_invite_accept_invites_only_from_local_users to specifies whether only invites from local users will be auto accepted.
=> Add missing configuration for synapse-auto-accept-invite role.

group_vars/matrix_servers
When generate `config.json` for element and/or schildichat web client the option `enable_presence_by_hs_url` get `"\n"` value if not `matrix_synapse_presence_enabled`. This PR changes yaml multiline formatting to strip trailing newline so it's value now just `""`.
=> Fix for 'enable_presence_by_hs_url' Element config option.

roles/custom/matrix-bridge-wechat/templates/config.yaml.j2
that's pretty useful to have them enabled, to match with other bridges supporting spaces
=> wechat: enable spaces by default

roles/custom/matrix-synapse/templates/goofys/systemd/matrix-goofys.service.j2
Commit 42247411308bd301b1c093ed132be0512368b885 missed a endfor statement in the goofys systemd service unit template. This adds it, avoiding a Jinja2 syntax error when using goofys.
=> fix(synapse/goofys): resolve Jinja2 syntax error in systemd service template

roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
`auto_join_mxid_localpart` defines the local part of the user id which is used to create auto-join rooms. The variable needs to be set to invite new users to any auto-join rooms which are set to invite-only.
=> Allow configuring synapse `auto_join_mxid_localpart`

docs/configuring-playbook-prometheus-grafana.md
Element seems to have moved their wiki to another url, so the link here deeded to be updated.
=> Update broken link in configuring-playbook-prometheus-grafana.md

roles/custom/matrix-bridge-hookshot/defaults/main.yml, roles/custom/matrix-bridge-hookshot/templates/config.yml.j2
Currently the webhooks for gitlab need to be manually added in your gitlab instance after adding a project using the hookshot bot. However according to the [Matrix Hookshot Documentation](https://matrix-org.github.io/matrix-hookshot/latest/usage/room_configuration/gitlab_project.html#setting-up) this step can be automated by adding the public url for the webhook endpoint. The needed configuration for the template is stated [here](https://matrix-org.github.io/matrix-hookshot/latest/setup/gitlab.html).
=> Autocreate webhook in Gitlab instance with Hookshot bot

docs/faq.md, docs/installing.md, docs/maintenance-upgrading-services.md, docs/prerequisites.md, justfile, requirements.yml
That's a common problem in the support room when people update the playbook, but don't update roles.
So, let's suggest a new command that will do everything at once - update the playbook and the roles at the same time.
That command is a modified version of etke.cc/ansible's update, that proved to be working flawlessly and (in this version) considers ansible-galaxy and agru existence in the system.
To simplify repo maintenance, that command supports `-u` flag to update requirements.yml file (only if you have agru installed) - this flag is considered for developers only.
So, here are examples of the new options:
* `just update` - similar to `git pull && just roles` before that PR, we should suggest using that command everywhere
* `just update -u` - similar to `git pull && just update` …
=> rewrite `just update` command to provide a one-line command to update everything

group_vars/matrix_servers
Fix for empty panels in grafana for some prometheus metrics. Solution from https://github.com/rfmoz/grafana-dashboards/issues/137
=> Sync grafana datasource and prometheus scrape intervals.

examples/reverse-proxies/nginx/matrix.conf
Two things changed (and I'm late to both parties):
1. Previous way of configuring HTTP2 was deprecated a while back, I updated it so less warnings are thrown.
2. I added support for QUIC and HTTP3
Hope the comments explaining the possible `quic reuseport` declaration are understandable, if someone sees this and has a better way of putting it, please do.
=> Update nginx fronting example: http2 config and enable quic+http3

docs/configuring-playbook-bot-draupnir.md, group_vars/matrix_servers, roles/custom/matrix-bot-draupnir/defaults/main.yml, roles/custom/matrix-bot-draupnir/tasks/setup_install.yml, roles/custom/matrix-bot-draupnir/templates/labels.j2, roles/custom/matrix-bot-draupnir/templates/production.yaml.j2, roles/custom/matrix-bot-draupnir/templates/systemd/matrix-bot-draupnir.service.j2
Mjolnir / Draupnir can receive abuse reports in the management room.
There are two options to configure this:
1. Poll reports from the admin-API
2. Redirect the endpoint to the draupnir container using a reverse proxy
The second option seems to be the preferred one.
This PR configures the MDAD-managed traefik to proxy the relevant requests to Draupnir (the second option). To enable it set `matrix_bot_draupnir_abuse_reporting_enabled: true`.
If this gets merged I'd be willing to create a PR adding the same options for Mjolnir, which should more or less be a big find and replace.
=> Draupnir proxy

docs/configuring-playbook-matrix-media-repo.md, group_vars/matrix_servers, roles/custom/matrix-media-repo/defaults/main.yml, roles/custom/matrix-media-repo/tasks/setup_install.yml
Automated signing key setup process described in https://docs.t2bot.io/matrix-media-repo/v1.3.5/installation/signing-key/
Homeserver backup key is kept alongside the merged signing key in case server administrator needs to revert.
=> Automated MMR signing key generation process

docs/configuring-playbook-ssl-certificates.md
I found https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/2673#issuecomment-1547488680 to be extremely useful, and I thought it would be good to include it in the official documentation. This configuration worked for me after setting `devture_traefik_config_certificatesResolvers_acme_dnsChallenge_enabled` to true, which was missing on the example of the commenter in the above issue. Also, after taking a look at https://github.com/devture/com.devture.ansible.role.traefik/blob/main/defaults/main.yml#L75-L103 I changed the options to reflect their example.
=> Add DNS-01 challenge to configuring-playbook-ssl-certificates.md

roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
This PR adds authenticated media configuration options ahead of this setting switching to default True. This is provided to easily enable users to set this to true prematurely before it becomes upstream default or to manually switch this off to extend the support window for clients that are not updated in time.
Edit: Please note that before Synapse 1.114.0rc1 this configuration option is supposedly broken with a workers deployment.
Edit 2: This option is according to reports in TWIM not broken on workers deployments if they are correctly configured but the RC removes the extra configuration burden.
=> Authenticated Media Configuration options

roles/custom/matrix-media-repo/tasks/setup_install.yml
Fixes issue #3516
Already running container had the same name `matrix_media_repo`.
Creating signing key using temporary container was not possible.
Adding suffix `-temp` to name made it work.
=> Add temp suffix for container name to avoid conflict

group_vars/matrix_servers
ref: https://github.com/etkecc/synapse-admin/?tab=readme-ov-file#protecting-appservice-managed-users
=> add system-managed users to synapse-admin

roles/custom/matrix-synapse-admin/defaults/main.yml, roles/custom/matrix-synapse-admin/templates/config.json.j2
This allows users to quickly find support in case of issues. The link is configurable via config.json - `supportURL`
=> synapse-admin v0.10.3-etke17: add `Contact support` menu item

roles/custom/matrix-bot-mjolnir/defaults/main.yml
github.com/matrix-org/mjolnir/issues/531
Any user not using E2EE support and therefore using User password auth is unable to launch updated Mjolnir. Due to this severe breakage its recomended to revert to before this bug is introduced until its fixed.
=> Revert Mjolnir version to 1.7.0 due to severe breakage.

roles/custom/matrix-client-cinny/templates/nginx.conf.j2
Cinny has added a service worker to support authenticated media and requires /sw,js to resolve to the serviceworker js file
=> Update Cinny nginx.conf.j2 to include service worker rewrite

docs/configuring-playbook-bot-maubot.md
Make the paragraph consistent with files such as:
- [docs/configuring-playbook-bot-baibot.md](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/13b9c8b1bf61e62a2a0a6e20e5d81b40c29c6761/docs/configuring-playbook-bot-baibot.md?plain=1#L389C1-L389C112)
- [docs/configuring-playbook-bot-buscarron.md](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/13b9c8b1bf61e62a2a0a6e20e5d81b40c29c6761/docs/configuring-playbook-bot-honoroit.md?plain=1#L44)
- [docs/configuring-playbook-bot-honoroit.md](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/13b9c8b1bf61e62a2a0a6e20e5d81b40c29c6761/docs/configuring-playbook-bot-buscarron.md?plain=1#L69)
=> Remove line breaks from docs/configuring-playbook-bot-maubot.md for consistency

docs/configuring-playbook-bot-maubot.md
Follow-up to https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3593
Update docs/configuring-playbook-bot-maubot.md for consistent expression for installing by making the paragraph consistent with files such as:
- [docs/configuring-playbook-bot-baibot.md](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/13b9c8b1bf61e62a2a0a6e20e5d81b40c29c6761/docs/configuring-playbook-bot-baibot.md?plain=1#L389C1-L389C112)
- [docs/configuring-playbook-bot-buscarron.md](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/13b9c8b1bf61e62a2a0a6e20e5d81b40c29c6761/docs/configuring-playbook-bot-honoroit.md?plain=1#L44)
- [docs/configuring-playbook-bot-honoroit.md](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/13b9c8b1bf61e62a2a0a6e20e5d81b40c29c6761/doc …
=> Update docs/configuring-playbook-bot-maubot.md for consistency

docs/configuring-playbook-bot-baibot.md, docs/configuring-playbook-matrix-registration.md, docs/configuring-playbook-shared-secret-auth.md
This PR intends to use a common expression for a password or secret: "Generate a strong secret (or password) here. Consider generating it with pwgen -s 64 1".
=> Use a common expression for password setting

docs/configuring-playbook-bot-maubot.md, docs/configuring-playbook-cactus-comments.md, docs/configuring-playbook-jitsi.md
This PR should move all colons on documentation outside of asterisks.
Please note that this does not touch files inside `.github` though there are files where colons are inside of them, as they indeed should look better if unchanged.
=> Move colons outside of asterisks

docs/configuring-playbook-bridge-mx-puppet-discord.md, docs/configuring-playbook-bridge-mx-puppet-groupme.md, docs/configuring-playbook-bridge-mx-puppet-instagram.md, docs/configuring-playbook-bridge-mx-puppet-slack.md, docs/configuring-playbook-bridge-mx-puppet-steam.md, docs/configuring-playbook-bridge-mx-puppet-twitter.md
This intends to remove line breaks inside a sentence on documentation (docs/configuring-playbook-bridge-mx*) so that translation can be managed easily.
=> Update docs/configuring-playbook-bridge-mx* - remove line breaks inside a sentence

docs/configuring-playbook-ssl-certificates.md
Redefinition of the providers file section through `traefik_configuration_extension_yaml` will disable traefik dashboard and auth middleware.
TLS setup should be placed in the `traefik_provider_configuration_extension_yaml` variable to extend _/config/provider.yml_ rather then _/config/traefik.yml_.
=> Clarify documentation about own ssl certificate setup

docs/configuring-playbook-cactus-comments.md
This is a follow-up to https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3638.
=> Update docs/configuring-playbook-cactus-comments.md: fix the example domain

docs/configuring-dns.md, docs/configuring-playbook-alertmanager-receiver.md, docs/configuring-playbook-bot-buscarron.md, docs/configuring-playbook-bot-go-neb.md, docs/configuring-playbook-bot-honoroit.md, docs/configuring-playbook-bot-maubot.md, docs/configuring-playbook-bridge-heisenbridge.md, docs/configuring-playbook-bridge-mautrix-wsproxy.md, docs/configuring-playbook-cactus-comments.md, docs/configuring-playbook-client-cinny.md, docs/configuring-playbook-client-element.md, docs/configuring-playbook-client-hydrogen.md, docs/configuring-playbook-client-schildichat.md, docs/configuring-playbook-dimension.md, docs/configuring-playbook-etherpad.md, docs/configuring-playbook-jitsi.md, docs/configuring-playbook-matrix-authentication-service.md, docs/configuring-playbook-matrix-registration.md, docs/configuring-playbook-ntfy.md, docs/configuring-playbook-prometheus-grafana.md, docs/configuring-playbook-rageshake.md, docs/configuring-playbook-sliding-sync-proxy.md, docs/configuring-playbook-sygnal.md, docs/configuring-playbook-synapse-admin.md, docs/configuring-playbook-synapse-usage-exporter.md
This adopts the structure of `docs/configuring-playbook-matrix-authentication-service.md` which was recently created.
Here is the template which this PR follows, based on that file.
````
- …
- Adjusting the playbook configuration
- … 
- Adjusting the (service name here) URL
- …
- Adjusting DNS records
- Installing
- …
````
The details of the instructions are slightly different between the documentations for components which require subdomain settings by default (such as `buscarron`) and the ones which do not (such as `matrix-alertmanager-receiver`). Each has been handled by the individual commits separately for easier review.
This also adds the description about the subdomain of Rageshake.
=> Update documentation for components about adjusting the URL and the DNS records

docs/configuring-playbook-alertmanager-receiver.md, docs/configuring-playbook-bot-buscarron.md, docs/configuring-playbook-bot-draupnir.md, docs/configuring-playbook-bot-go-neb.md, docs/configuring-playbook-bot-honoroit.md, docs/configuring-playbook-bot-mjolnir.md, docs/configuring-playbook-bridge-appservice-discord.md, docs/configuring-playbook-bridge-appservice-slack.md, docs/configuring-playbook-email2matrix.md, roles/custom/matrix-alertmanager-receiver/defaults/main.yml, roles/custom/matrix-bot-draupnir/templates/production.yaml.j2, roles/custom/matrix-bot-go-neb/defaults/main.yml, roles/custom/matrix-bot-mjolnir/templates/production.yaml.j2, roles/custom/matrix-bridge-appservice-irc/defaults/main.yml, roles/custom/matrix-bridge-appservice-slack/defaults/main.yml, roles/custom/matrix-bridge-go-skype-bridge/templates/config.yaml.j2, roles/custom/matrix-email2matrix/defaults/main.yml, roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
Related: https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3631
This PR intends to update room IDs and alias with ones on the Matrix Specification.
See:
- https://spec.matrix.org/v1.12/#room-structure where the room ID `!qporfwt:matrix.org` is used as an example.
- https://spec.matrix.org/v1.12/#room-aliases where the room ID `!aaabaa:matrix.org` is used as an example.
- https://spec.matrix.org/v1.12/#room-aliases where the room alias `#matrix:example.org` is used as an example.
If I am honest, I do not think those are nice choices... they should be something which looks more as example, but using ones on the specs should help us to keep consistency when they are updated on a future spec version.
=> Update room IDs and alias with ones on the Matrix Specification

CHANGELOG.md, YEAR-IN-REVIEW.md, docs/configuring-playbook-backup-borg.md, docs/configuring-playbook-postgres-backup.md, docs/configuring-playbook.md
In order to avoid confusions between the name of the program itself (BorgBackup and Borg in short) and the backups managed by BorgBackup, the official full name should be preferred where possible, minding capitalization.
- Borg or borg → BorgBackup
- Borg backup(s) → BorgBackup (if it means the program) / backups with BorgBackup (if it means the backups managed by the program)
Based on https://www.borgbackup.org/
=> Consistent usage of the words related to BorgBackup (Borg)

README.md, docs/configuring-playbook-bridge-mx-puppet-discord.md, docs/configuring-playbook-bridge-mx-puppet-slack.md, docs/container-images.md
This updates the documentation files docs/configuring-playbook-bridge-mx-puppet-discord.md and docs/configuring-playbook-bridge-mx-puppet-slack.md to reflect the fact that the transitions to the Beeper fork (https://gitlab.com/beeper/mx-puppet-monorepo) have been reverted for both mx-puppet-discord and mx-puppet-slack several years ago.
=> Update documentation regarding beeper forks

docs/configuring-playbook-synapse.md, docs/maintenance-and-troubleshooting.md
There are other links to the original repository such as `https://github.com/matrix-org/synapse/issues/3939` but an issue with the same number on the forked repository `https://github.com/element-hq/synapse/issues/3939` is used as a placeholder.
=> Replace existing links to matrix-org/synapse which should be replaced

CHANGELOG.md, README.md, docs/configuring-playbook-bridge-appservice-discord.md, docs/container-images.md, roles/custom/matrix-bridge-appservice-discord/defaults/main.yml, roles/custom/matrix-bridge-appservice-discord/templates/config.yaml.j2
The URL is changed from https://github.com/Half-Shot/matrix-appservice-discord to https://github.com/matrix-org/matrix-appservice-discord.
=> Update the URL to matrix-appservice-discord

README.md, docs/container-images.md, roles/custom/matrix-user-verification-service/defaults/main.yml
Matrix User Authentication Service itself has been available for Jitsi since 42e4e50f5be654b812939732114f0724865cdc78.
=> Add links to matrix-user-verification-service

docs/container-images.md
Since it apparently is quite easy to forget to add an entry to `docs/container-images.md`, I mentioned it on https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3631 :)
I've tested links but double check would be appreciated!
=> Update docs/container-images.md: add unlisted Docker images and create a section for container images of deprecated or unmaintained services

README.md
This PR is purely per my preference. As being obsolete, deprecated, or unmaintained does not technically mean being unsupported, removing them from the list might be too far, but it should be also right that we would not support those services positively even if the authors themselves stopped maintenance of them…
=> Update README.md: remove deprecated or unmaintained services from the supported services section

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/i-need-help.md
Please note that `suggestion` label needs to be created first as it does not exist for the repository.
=> Add labels to issue templates

docs/container-images.md
This is essentially an imitation of 59a01da for container images. It copies the entries order and descriptions on the table of README.md
There are several services which require self building, and `matrix-synapse-rest-auth`, `matrix-synapse-shared-secret-auth`, `matrix-synapse-ldap3`, `synapse-s3-storage-provider`, `synapse_auto_accept_invite`, and `synapse-simple-antispam` do not seem to have its container image.
=> Update docs/container-images.md: create tables following README.md

docs/configuring-playbook.md
Setting "optional" is redundant for those entries, as all of them are under the heading "Other configuration options" and it is obvious that those settings are optional.
=> Update docs/configuring-playbook.md: remove "optional" from links

docs/installing.md
Related to https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3741 and https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3739
=> Update docs/installing.md: add a note to avoid running the just recipe install-all, instead of ansible-playbook with install-all tag

README.md, docs/configuring-playbook-sliding-sync-proxy.md
I also confirm that Element X works just fine without using the proxy, running synapse 1.118.
=> Documentation: sliding sync proxy is not required for Synapse >1.114

docs/configuring-dns.md
The right next step of docs/configuring-dns.md is docs/getting-the-playbook.md, as shown on the last line.
=> Update docs/configuring-dns.md: remove an incorrect instruction to the next step

docs/configuring-playbook-sliding-sync-proxy.md
Linking to download pages are not necessary anymore as Element X clients can be downloaded in normal way.
=> Update docs/configuring-playbook-sliding-sync-proxy.md: Element X is no longer beta

examples/vars.yml, roles/custom/matrix-base/defaults/main.yml
Since a casual user might want to try another homeserver than Synapse without thinking about its consequence, it is important to clarify that it is not possible to switch homeservers once specified.
=> Edit the note about "matrix_homeserver_implementation" variable

docs/configuring-playbook-synapse.md
Keycloak exposes the issuer information on /realms/whatever, not /auth/realms/whatever.
=> Correct issuer URL in OIDC example section

.github/workflows/close-stale-issues.yml
The workflow itself should be fine. Perhaps `debug-only: true` should be enabled for testing, though I am not really sure how it works.
=> Add .github/workflows/close-stale-issues.yml: close stale issues automatically

.github/workflows/close-stale-issues.yml
Closes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3807
With this PR:
- Issues with `question` and/or `needs-info` label(s) will be labelled with `stale` after 60 days without activity and closed in 7 days after that. Stale counter to add `stale` label will restart whenever any update occurs or a comment is added to them.
- PRs with `needs-rebase` and/or `needs-info` label(s) will be labelled with `stale` after 1 year since creation without activity and closed in 30 days after that. Stale counter to add `stale` label will not restart.
- No issues or PRs assigned to @spantaleev and/or @aine-etke (not authored) will be closed.
=> Update .github/workflows/close-stale-issues.yml: include PRs

.github/workflows/close-stale-issues.yml
This should fix the issue that https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2192 (labelled with `needs-info` but not with `needs-rebase`) was not marked as stale.
=> Update .github/workflows/close-stale-issues.yml: edit stale messages and fix any-of-labels

roles/custom/matrix-bridge-hookshot/defaults/main.yml, roles/custom/matrix-bridge-hookshot/templates/registration.yml.j2
Usecase: I need to have a prefix for every non-person matrix account, so they dont mess  up my metrics, stats, scripts etc.
According to https://matrix-org.github.io/matrix-hookshot/latest/advanced/service_bots.html, you can define the localpart of the hookshot matrixID. I only renamed the hookshot bot localpart so this change should be easy, at least I couldnt see any problems with my change and it worked on my dev environment.
I set the default name to "hookshot", just as before, but with this, you can change it if you want/need to
=> hookshot: Allow the localpart of the hookshot-bot to be defined

roles/custom/matrix-bot-mjolnir/defaults/main.yml
This PR bumps mjolnir to https://github.com/matrix-org/mjolnir/releases/tag/v1.9.1
This release is listed as a security release.
=> Update Mjolnir from 1.9.0 to 1.9.1

LICENSES/AGPL-3.0-or-later.txt, conf.py, i18n/README.md, i18n/bin/build-translated-result.sh, i18n/bin/extract-translation-templates.sh, i18n/bin/sync-translation-templates-to-locales.sh, i18n/justfile, reuse.toml
For https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3859 and https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3796
REUSE is an initiative by FSFE, which intends to make licensing easier with best practices to display legal information through comment headers on source files that can be easily human and machine readable.
**Because these files are new and translation shall involve a lot of people as copyright holders, now is the best time to adopt REUSE.** As a first implementation, this commit intentionally limits the scope to i18n directory.
Cherry-picked from c737ed0612e5b8bd5837877df63932d77bdcfcf7 and a2445af6d0100a43d6011b31402b9ae8f0c38f0c
=> Start adopting REUSE on files for a brand new subproject (translation)

i18n/.gitignore, i18n/README.md, i18n/bin/build-translated-result.sh, i18n/justfile, i18n/translation-templates/i18n/README.pot
I think it is better to use the word "translations" on this context.
Note: this commit does not include PO files as I thought we might as well to update them from POT files, per an expected workflow.
=> Change "translated" → "translations"

docs/configuring-playbook-alertmanager-receiver.md, docs/configuring-playbook-bot-baibot.md, docs/configuring-playbook-bot-buscarron.md, docs/configuring-playbook-bot-chatgpt.md, docs/configuring-playbook-bot-draupnir.md, docs/configuring-playbook-bot-go-neb.md, docs/configuring-playbook-bot-honoroit.md, docs/configuring-playbook-bot-matrix-registration-bot.md, docs/configuring-playbook-bot-matrix-reminder-bot.md, docs/configuring-playbook-bot-maubot.md, docs/configuring-playbook-bot-mjolnir.md, docs/configuring-playbook-email2matrix.md, docs/howto-server-delegation.md, i18n/translation-templates/docs/configuring-playbook-alertmanager-receiver.pot, i18n/translation-templates/docs/configuring-playbook-bot-baibot.pot, i18n/translation-templates/docs/configuring-playbook-bot-buscarron.pot, i18n/translation-templates/docs/configuring-playbook-bot-chatgpt.pot, i18n/translation-templates/docs/configuring-playbook-bot-draupnir.pot, i18n/translation-templates/docs/configuring-playbook-bot-go-neb.pot, i18n/translation-templates/docs/configuring-playbook-bot-honoroit.pot, i18n/translation-templates/docs/configuring-playbook-bot-matrix-registration-bot.pot, i18n/translation-templates/docs/configuring-playbook-bot-matrix-reminder-bot.pot, i18n/translation-templates/docs/configuring-playbook-bot-maubot.pot, i18n/translation-templates/docs/configuring-playbook-bot-mjolnir.pot, i18n/translation-templates/docs/configuring-playbook-email2matrix.pot, i18n/translation-templates/docs/howto-server-delegation.pot
- Add "To use the bot" if it is not: follow the docs for bridges
- Add "Prerequisites" section if a certain API key or user account is required
- Use the common instruction for getting an access token
- Replace placeholders for access tokens on docs/configuring-playbook-bot-go.neb.md
=> Edit docs for bots: adopt the common format

docs/configuring-playbook-alertmanager-receiver.md, docs/configuring-playbook-bot-chatgpt.md, docs/configuring-playbook-bot-draupnir.md, docs/configuring-playbook-bot-go-neb.md, docs/configuring-playbook-bot-maubot.md, docs/configuring-playbook-bot-mjolnir.md, docs/configuring-playbook-bridge-appservice-kakaotalk.md, docs/configuring-playbook-bridge-mautrix-discord.md, docs/configuring-playbook-bridge-mautrix-facebook.md, docs/configuring-playbook-bridge-mautrix-gmessages.md, docs/configuring-playbook-bridge-mautrix-googlechat.md, docs/configuring-playbook-bridge-mautrix-hangouts.md, docs/configuring-playbook-bridge-mautrix-meta-instagram.md, docs/configuring-playbook-bridge-mautrix-meta-messenger.md, docs/configuring-playbook-bridge-mautrix-signal.md, docs/configuring-playbook-bridge-mautrix-slack.md, docs/configuring-playbook-bridge-mautrix-telegram.md, docs/configuring-playbook-bridge-mautrix-twitter.md, docs/configuring-playbook-bridge-mautrix-whatsapp.md, docs/configuring-playbook-dimension.md, docs/configuring-playbook-email2matrix.md, docs/configuring-playbook-user-verification-service.md, docs/maintenance-synapse.md, docs/obtaining-access-tokens.md
The warning message (based on docs/obtaining-access-tokens.md) is so important that I think it is worthwhile to repeat it in each instance.
=> Edit docs for obtaining an access token

roles/custom/matrix-client-element/defaults/main.yml, roles/custom/matrix-client-element/templates/config.json.j2
One of our customers requested to have a redirect url for SSO logout (see [element-web documentation](https://github.com/element-hq/element-web/blob/develop/docs/config.md#sso-setup)).
The option wasn't implemented in the role so here's the commit for that :)
Don't hesitate if anything isn't up to contributing standards, I'll happily amend the commit!
=> Add logout_redirect_url var and option templating for matrix element client

group_vars/matrix_servers, roles/custom/matrix-base/defaults/main.yml
I’m one of those crazy people who use this playbook with `matrix_playbook_reverse_proxy_type: none` set. Everything works perfectly, except for `synapse-admin`.
`synapse-admin` connects to additional docker networks here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/c0559870b50ad9e3848533c10066f985ff4b3ae0/roles/custom/matrix-synapse-admin/templates/systemd/matrix-synapse-admin.service.j2#L39-L41
This defaults to `'traefik'` through `matrix_playbook_reverse_proxy_container_network`, which should not happen when `matrix_playbook_reverse_proxy_type` is set to `none`.
=> Fix docker networking when no reverse-proxy is used

.github/workflows/close-stale-issues.yml
Apparently checking issues or PRs which have been labelled with "stale" consumes more operations than checking ones without labelled, and the current amount (100) is not enough. See an example: https://github.com/spantaleev/matrix-docker-ansible-deploy/actions/runs/12566424393/job/35031806537#step:2:4083
Since the total amount of GitHub API rate is 5000, reserving 10 per cent for this action should not be an issue for now. Let's increase again if it is still too low.
=> Update .github/workflows/close-stale-issues.yml: increase operations-per-run from 100 to 500

docs/configuring-playbook-bridge-appservice-kakaotalk.md, docs/configuring-playbook-bridge-beeper-linkedin.md, docs/configuring-playbook-bridge-go-skype-bridge.md, docs/configuring-playbook-bridge-mautrix-bridges.md, docs/configuring-playbook-bridge-mautrix-discord.md, docs/configuring-playbook-bridge-mautrix-facebook.md, docs/configuring-playbook-bridge-mautrix-gmessages.md, docs/configuring-playbook-bridge-mautrix-googlechat.md, docs/configuring-playbook-bridge-mautrix-hangouts.md, docs/configuring-playbook-bridge-mautrix-instagram.md, docs/configuring-playbook-bridge-mautrix-meta-instagram.md, docs/configuring-playbook-bridge-mautrix-meta-messenger.md, docs/configuring-playbook-bridge-mautrix-signal.md, docs/configuring-playbook-bridge-mautrix-slack.md, docs/configuring-playbook-bridge-mautrix-telegram.md, docs/configuring-playbook-bridge-mautrix-twitter.md, docs/configuring-playbook-bridge-mautrix-whatsapp.md, docs/configuring-playbook-bridge-mautrix-wsproxy.md
This PR intends to be a follow-up to https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3914.
Main changes:
- update usage descriptions based on the official docs
- fix the internal anchor links
- add descriptions for each mautrix bridge about the bridges behavior after logging in
- simplify usage descriptions of the bridges for discord and slack
- update docs/configuring-playbook-bridge-go-skype-bridge.md for go-skype-bridge, which was created based on mautrix-whatsapp
=> Update docs for mautrix bridges (follow-up)

docs/configuring-playbook-client-element-web.md, docs/configuring-playbook-client-schildichat-web.md
- Add the common section "Extending the configuration"
- Add examples of extending the configuration
- Edit descriptions about themes
=> Update docs for Element Web and SchildiChat Web

CHANGELOG.md, docs/ansible.md, docs/configuring-playbook-bot-baibot.md, docs/configuring-playbook-bridge-postmoogle.md, docs/configuring-playbook-matrix-corporal.md, docs/configuring-playbook-ssl-certificates.md, docs/configuring-playbook-sygnal.md, docs/configuring-playbook-synapse-s3-storage-provider.md, docs/configuring-playbook-synapse.md, docs/faq.md, docs/installing.md, group_vars/matrix_servers, i18n/justfile
You can directly type `…` by inputting <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>u</kbd> followed by [`2026`](https://www.compart.com/en/unicode/U+2026) (see [here](https://superuser.com/questions/59418/how-to-type-special-characters-in-linux/59435#59435)). You can also use a Japanese IME to convert three dots into a horizontal ellipsis.
=> Replace double or triple dots with horizontal ellipses (“…” U+2026)

docs/configuring-playbook-jitsi.md, docs/configuring-playbook-user-verification-service.md
This also intends to be a first trial of placing the instruction about adjusting DNS records above the section for adjusting the URL, to make the configuration workflow more natural. Once it is confirmed that this change makes sense, the other instances will be addressed with another PR.
Though working on Jitsi integration stuff might no longer be as worth as it has been thanks to Element Call, improving the docs should always help us some way :)
=> Tidy up docs/configuring-playbook-jitsi.md and another related file

group_vars/matrix_servers
Please let me know if the variable is still useful somehow. Thanks in advance!
=> Remove an obsolete variable: backup_borg_retention_prefix

docs/configuring-playbook-email.md
This commit applies the common format to the file.
=> Update docs/configuring-playbook-email.md: tidy up

docs/configuring-playbook-bot-maubot.md, docs/configuring-playbook-bridge-appservice-irc.md, docs/configuring-playbook-bridge-appservice-webhooks.md, docs/configuring-playbook-bridge-go-skype-bridge.md, docs/configuring-playbook-bridge-heisenbridge.md, docs/configuring-playbook-bridge-matrix-bridge-sms.md, docs/configuring-playbook-dynamic-dns.md, docs/configuring-playbook-matrix-authentication-service.md, docs/configuring-playbook-matrix-corporal.md, docs/configuring-playbook-matrix-registration.md, roles/custom/matrix-bridge-appservice-irc/templates/config.yaml.j2, roles/custom/matrix-bridge-appservice-webhooks/defaults/main.yml, roles/custom/matrix-bridge-go-skype-bridge/defaults/main.yml
Update docs and config files by adopting the common format to:
- maubot
- appservice-irc
- appservice-webhooks
- heisenbridge
- corporal
- matrix-registration
- dynamic-dns
- go-skype-bridge
- matrix-authentication-service
- matrix-sms-bridge
=> Update docs and config files for various components

docs/configuring-playbook-bot-mjolnir.md, docs/configuring-playbook-bridge-appservice-discord.md, docs/configuring-playbook-client-cinny.md, docs/configuring-playbook-client-hydrogen.md, docs/configuring-playbook-conduit.md, docs/configuring-playbook-dendrite.md, docs/configuring-playbook-jitsi.md, docs/configuring-playbook-matrix-media-repo.md, docs/configuring-playbook-sygnal.md, docs/configuring-playbook-synapse-admin.md, docs/configuring-playbook-synapse-usage-exporter.md, roles/custom/matrix-bot-mjolnir/templates/production.yaml.j2, roles/custom/matrix-bridge-appservice-discord/templates/config.yaml.j2
This PR intends to update docs and configuration files in bulk for:
- Appservice-discord
- Conduit
- Dendrite
- Client-cinny
- Client-hydrogen
- Matrix-media-repo
- Synapse-usage-exporter
- Synapse-admin
- Mjolnir
- Jitsi
- Sygnal
=> Update docs and config files for various services

docs/configuring-playbook-bot-matrix-registration-bot.md, docs/configuring-playbook-bridge-appservice-webhooks.md, docs/configuring-playbook-bridge-hookshot.md, docs/configuring-playbook-bridge-mautrix-discord.md, docs/configuring-playbook-bridge-mautrix-facebook.md, docs/configuring-playbook-bridge-mautrix-gmessages.md, docs/configuring-playbook-bridge-mautrix-googlechat.md, docs/configuring-playbook-bridge-mautrix-instagram.md, docs/configuring-playbook-bridge-mautrix-meta-instagram.md, docs/configuring-playbook-bridge-mautrix-meta-messenger.md, docs/configuring-playbook-bridge-mautrix-signal.md, docs/configuring-playbook-bridge-mautrix-slack.md, docs/configuring-playbook-bridge-mautrix-telegram.md, docs/configuring-playbook-bridge-mautrix-twitter.md, docs/configuring-playbook-bridge-mautrix-whatsapp.md, docs/configuring-playbook-bridge-mautrix-wsproxy.md, docs/configuring-playbook-bridge-wechat.md, docs/configuring-playbook-jitsi.md, docs/configuring-playbook-postgres-backup.md, docs/configuring-playbook-prometheus-grafana.md, docs/configuring-playbook-s3-goofys.md, roles/custom/matrix-bridge-mautrix-discord/defaults/main.yml, roles/custom/matrix-bridge-mautrix-gmessages/defaults/main.yml, roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml, roles/custom/matrix-bridge-mautrix-slack/defaults/main.yml, roles/custom/matrix-bridge-mautrix-twitter/defaults/main.yml, roles/custom/matrix-bridge-mautrix-whatsapp/defaults/main.yml
This PR intends to complete adding the common section "Troubleshooting" to documents except some of them (such as mx bridges, etc). I checked against `group_vars/matrix_servers`, and fixed some incorrect instructions as well.
=> Update docs to add the common section "Troubleshooting"

docs/configuring-playbook-backup-borg.md
This PR intends to be a preparation for improving the docs for BorgBackup at the MASH project [here](https://github.com/mother-of-all-self-hosting/ansible-role-backup_borg/blob/f659bd250d22f3b95948ea579b8ef7679c852988/docs/configure-backup-borg.md).
For https://github.com/mother-of-all-self-hosting/ansible-role-backup_borg/pull/3
=> Update docs/configuring-playbook-backup-borg.md for the MASH project

docs/configuring-well-known.md
As discussed some time ago on the matrix channel for this project, a 302 redirect from the base domain (rather than a reverse proxy) is a little more realistic in a large institution (this is what we have done in epfl.ch).
Just adding a few words to clarify that this is an option
=> add 302 redirect option as well as reverse-proxy

docs/configuring-playbook-postgres-backup.md
This is a preparation to copy the document to its own repository at the MASH project (https://github.com/mother-of-all-self-hosting/ansible-role-postgres-backup).
=> Update docs/configuring-playbook-postgres-backup.md: add the copyright header

docs/configuring-playbook-postgres-backup.md
This PR intends to replace the instruction with the reference to [the document copied to the MASH project](https://github.com/mother-of-all-self-hosting/ansible-role-postgres-backup/blob/main/docs/configuring-postgres-backup.md).
This follows the change for docs on BorgBackup with 414445b6bf09d29dc1075e8954fb78a66d26a53a.
=> Update docs/configuring-playbook-postgres-backup.md: replace the instruction with the reference to MASH project

docs/configuring-playbook-etherpad.md
- Add links to the role at MASH project and its document
- Replace common instructions with the links to the role at MASH project
=> Make docs/configuring-playbook-etherpad.md slim

docs/README.md, docs/configuring-dns.md, docs/getting-the-playbook.md, docs/installing.md, docs/maintenance-and-troubleshooting.md, docs/maintenance-upgrading-services.md, docs/prerequisites.md, docs/uninstalling.md
This commit adds copyright headers to the same kind of docs as ones linked from https://github.com/mother-of-all-self-hosting/mash-playbook/tree/e48af8a3273b416188b1fa4bc9009ef7e923235f/docs/README.md, so that these files can be reused over there.
=> Update docs: add copyright headers for the MASH project

docs/just.md, docs/playbook-tags.md
Those two files are linked from installing.md and it will be useful to add the headers to them as well.
=> Update docs: add copyright headers to docs linking to installing.md

docs/ansible.md
This change should make it easier to maintain the file, once the same kind of change is (re-)applied to mash-playbook ([here](https://github.com/mother-of-all-self-hosting/mash-playbook/blob/main/docs/ansible.md)) too.
=> Update docs/ansible.md: copy from the MASH project and minor changes

docs/alternative-architectures.md, docs/configuring-playbook.md
This intends to add copyright headers for making it possible for the files to be reused at the MASH project.
=> Update docs: add copyright headers

docs/configuring-playbook-bridge-mautrix-hangouts.md, docs/configuring-playbook-email2matrix.md
This commit updates titles of the docs for removed components, following 0bc4ef8f4d6611f4b18a94d0b4439f69922a8279.
=> Update docs: edit titles of the removed components

docs/configuring-playbook-bot-matrix-reminder-bot.md, docs/configuring-playbook-bridge-go-skype-bridge.md, roles/custom/matrix-bot-matrix-reminder-bot/defaults/main.yml, roles/custom/matrix-bot-matrix-reminder-bot/tasks/main.yml, roles/custom/matrix-bot-matrix-reminder-bot/tasks/setup_install.yml, roles/custom/matrix-bot-matrix-reminder-bot/tasks/setup_uninstall.yml, roles/custom/matrix-bot-matrix-reminder-bot/tasks/validate_config.yml, roles/custom/matrix-bot-matrix-reminder-bot/templates/config.yaml.j2.license, roles/custom/matrix-bot-matrix-reminder-bot/templates/systemd/matrix-bot-matrix-reminder-bot.service.j2.license, roles/custom/matrix-bridge-go-skype-bridge/defaults/main.yml, roles/custom/matrix-bridge-go-skype-bridge/tasks/main.yml, roles/custom/matrix-bridge-go-skype-bridge/tasks/setup_install.yml, roles/custom/matrix-bridge-go-skype-bridge/tasks/setup_uninstall.yml, roles/custom/matrix-bridge-go-skype-bridge/tasks/validate_config.yml, roles/custom/matrix-bridge-go-skype-bridge/templates/config.yaml.j2.license, roles/custom/matrix-bridge-go-skype-bridge/templates/systemd/matrix-go-skype-bridge.service.j2.license, roles/custom/matrix-prometheus-nginxlog-exporter/defaults/main.yml, roles/custom/matrix-prometheus-nginxlog-exporter/examples/grafana.png.license, roles/custom/matrix-prometheus-nginxlog-exporter/examples/metrics.png.license, roles/custom/matrix-prometheus-nginxlog-exporter/tasks/main.yml, roles/custom/matrix-prometheus-nginxlog-exporter/tasks/setup_install.yml, roles/custom/matrix-prometheus-nginxlog-exporter/tasks/setup_uninstall.yml, roles/custom/matrix-prometheus-nginxlog-exporter/tasks/validate_config.yml, roles/custom/matrix-prometheus-nginxlog-exporter/templates/grafana/nginx-proxy.json.license, roles/custom/matrix-prometheus-nginxlog-exporter/templates/labels.j2, roles/custom/matrix-prometheus-nginxlog-exporter/templates/nginx-proxy.json.license, roles/custom/matrix-prometheus-nginxlog-exporter/templates/prometheus-nginxlog-exporter.yaml.j2, roles/custom/matrix-prometheus-nginxlog-exporter/templates/systemd/matrix-prometheus-nginxlog-exporter.service.j2.license
This PR intends to:
- add license information to files for matrix-bot-matrix-reminder-bot
- add license information to files for matrix-bridge-go-skype-bridge
- add license information to files for matrix-prometheus-nginxlog-exporter
=> Add license information to files for quiet projects

docs/configuring-playbook-alertmanager-receiver.md, docs/configuring-playbook-appservice-double-puppet.md, roles/custom/matrix-alertmanager-receiver/defaults/main.yml, roles/custom/matrix-alertmanager-receiver/tasks/install.yml, roles/custom/matrix-alertmanager-receiver/tasks/main.yml, roles/custom/matrix-alertmanager-receiver/tasks/uninstall.yml, roles/custom/matrix-alertmanager-receiver/tasks/validate_config.yml, roles/custom/matrix-alertmanager-receiver/templates/config.yaml.j2.license, roles/custom/matrix-alertmanager-receiver/templates/labels.j2, roles/custom/matrix-alertmanager-receiver/templates/systemd/matrix-alertmanager-receiver.service.j2.license, roles/custom/matrix-appservice-double-puppet/defaults/main.yml, roles/custom/matrix-appservice-double-puppet/tasks/install.yml, roles/custom/matrix-appservice-double-puppet/tasks/main.yml, roles/custom/matrix-appservice-double-puppet/tasks/uninstall.yml, roles/custom/matrix-appservice-double-puppet/tasks/validate_config.yml, roles/custom/matrix-appservice-double-puppet/templates/registration.yaml.j2
This one is for matrix-alertmanager-receiver and appservice-double-puppet.
=> Add license information to files for two components

roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
This PR enables the room summary API as specified in MSC3266 (https://github.com/matrix-org/matrix-spec-proposals/pull/3266) by default as it is a hard requirement for the Element X clients (https://github.com/element-hq/element-x-ios/issues/3713#issuecomment-2620958291).
I tested this on two of our private/non-federating instances with the current Element X codebase on iOS and Android. It fixes the issue of not being able to accept/decline room invites.
=> Enable room summary API (MSC3266) support for Synapse

docs/playbook-tags.md
The tag has been introduced with 54babc5de0664622edb13e2a07ad099e68b95c80.
=> Add ensure-users-created to the list of available tags on playbook-tags.md

roles/custom/matrix-synapse/defaults/main.yml, roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
This adds a new variable for enabling custom profile fields with synapse.
This is my first contribution to this project so I figured I'd start with something small :)
=> Add support for configuring Synapse's MSC4133 (Custom Profile Fields)

justfile
If this repository was checked out in a location with spaces in the path, certain `just` tasks would fail.
This fixes those cases by wrapping necessary paths in quotes.
=> fix: Justfile works when checked out in locations with spaces
