- roles/matrix-server/defaults/main.yml
- roles/matrix-server/tasks/main.yml
- roles/matrix-server/tasks/setup/main.yml
I am trying to use this as a role from my own playbook. This is the simplest (and most minimal) change I could think of to allow me to select which bits I want to run.
> Allow specifying which parts of the role run from playbooks

- CHANGELOG.md
- roles/matrix-server/defaults/main.yml
- roles/matrix-server/templates/nginx-conf.d/matrix-riot-web.conf.j2
- roles/matrix-server/templates/nginx-conf.d/matrix-synapse.conf.j2
Feel free to close if you think TLS 1.0 comparability is important but this is how I have my server setup. (Actually on mine I also disabled 1.1)
> Disable TLS 1.0

- CHANGELOG.md
- roles/matrix-server/defaults/main.yml
- roles/matrix-server/templates/riot-web/config.json.j2
> Allow a few parts of Riot config.json to be configured (#24)

- docs/configuring-playbook.md
Missing file ending results in 404
> Updated "Controlling Matrix federation" link

- docs/README.md
- docs/maintenance-and-troubleshooting.md
> Add initial version of maintenance and troubleshooting doc

- CHANGELOG.md
- roles/matrix-server/defaults/main.yml
- roles/matrix-server/templates/synapse/synapse.log.config.j2
> Allow Synapse log levels to be configured (#23)

- roles/matrix-server/tasks/self_check/self_check_well_known.yml
> Fix well known self check

- README.md
> Update README to link to bubuntux/riot-web

- .editorconfig
https://editorconfig.org/
Only a suggestion, change as you would see fit.
> Adding .editorconfig.

- docs/configuring-playbook-telemetry.md
host_vars was left out of the path
> fixed a small path typo in playbook telemetry docs

- roles/matrix-riot-web/defaults/main.yml
Untested but see no reason why it wouldn't work
> Upgrade riot-web to v1.0.3

- README.md
- docs/configuring-dns.md
- docs/configuring-playbook-dimension.md
- docs/configuring-playbook.md
- docs/installing.md
I have written short documentation about Dimension
> Provide Dimension documentation

- roles/matrix-synapse/tasks/ext/appservice-irc/setup.yml
- roles/matrix-synapse/templates/ext/appservice-irc/systemd/matrix-appservice-irc.service.j2
I've tested this on my personal homeserver and it works just fine.
> Start appservice-irc as non-root

- roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
The sentry integration looks like it could be interesting
> Update homeserver.yaml with some new options we could enable

- roles/matrix-synapse/defaults/main.yml
- roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
> Add variable to disable homeserver url preview

- roles/matrix-dimension/defaults/main.yml
- roles/matrix-mxisd/defaults/main.yml
- roles/matrix-synapse/defaults/main.yml
This yaml template wouldn't compile until I changed all the flow control lines to two leading spaces.
> Fix template indentation

- docs/maintenance-checking-services.md
The previous URL returns a 404.
> Update URL for Matrix federation tester

- docs/updating-users-passwords.md
and provide an example for using the admin API
Follow up to #175
> Move around options on updating-users-passwords.md

- roles/matrix-common-after/tasks/main.yml
- roles/matrix-common-after/tasks/stop.yml
Complementary to the `start` tag, how about a `stop` tag? 😋
> Add a task to stop services (and remove containers)

- roles/matrix-postgres/defaults/main.yml
- roles/matrix-postgres/templates/systemd/matrix-postgres.service.j2
Can probably do this with extra arguments but probably nice to just have this built in
> Add config option to be able to access database outside of container

- docs/installing.md
- docs/maintenance-migrating.md
A few days ago, I had to migrate matrix from one server to another.
This markdown file reflects the way I achieved migration. It's not a copy-paste step-by-step instruction, but rather a guide which I want to share. 
There might be bridges which don't migrate that well. However, I haven't experienced any issues with a basic and simple setup.
> Added a basic guide on migrating to another server

- roles/matrix-riot-web/defaults/main.yml
- roles/matrix-riot-web/templates/config.json.j2
Not really big PR, but probably useful for somebody
> introduce configuration to change riot branding / title

- group_vars/matrix_servers
- roles/matrix-bridge-mautrix-hangouts/defaults/main.yml
- roles/matrix-bridge-mautrix-hangouts/tasks/init.yml
- roles/matrix-bridge-mautrix-hangouts/tasks/main.yml
- roles/matrix-bridge-mautrix-hangouts/tasks/setup_install.yml
- roles/matrix-bridge-mautrix-hangouts/tasks/setup_uninstall.yml
- roles/matrix-bridge-mautrix-hangouts/tasks/validate_config.yml
- roles/matrix-bridge-mautrix-hangouts/templates/systemd/matrix-mautrix-hangouts.service.j2
- roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2
- roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-synapse.conf.j2
- setup.yml
This is just a naive copy and find-replace of the facebook -> hangouts right now. I imagine there are some details that need to be worked out, but posting here for discussion.
> add hangouts bridge by copying facebook bridge and find-replacing

- roles/matrix-base/tasks/setup_matrix_base.yml
- roles/matrix-coturn/tasks/setup_coturn.yml
Allow to run the playbook in check mode:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html
> Disable docker network tasks in check mode to allow running the playbook in check mode (--check --diff)

- docs/configuring-playbook-mxisd.md
- docs/maintenance-and-troubleshooting.md
- roles/matrix-mxisd/defaults/main.yml
- roles/matrix-mxisd/templates/systemd/matrix-mxisd.service.j2
This is something that I have used to debug LDAP authentication with mxisd and found useful. Do you think we can add this variable to this project?
> Add variable to enable verbose logging for mxisd

- docs/configuring-playbook-ldap-auth.md
- docs/configuring-playbook-mxisd.md
> Document LDAP authentication using mxisd

- docs/configuring-playbook-own-webserver.md
@spantaleev helped me get this working with Traefik as a reverse proxy. I've added my working configuration to the docs with ample comments and explanation.
> Added Traefik configuration example to own webserver docs

- README.md
- docs/configuring-playbook-bridge-appservice-webhooks.md
- group_vars/matrix_servers
- roles/matrix-bridge-appservice-webhooks/defaults/main.yml
- roles/matrix-bridge-appservice-webhooks/tasks/init.yml
- roles/matrix-bridge-appservice-webhooks/tasks/main.yml
- roles/matrix-bridge-appservice-webhooks/tasks/setup_install.yml
- roles/matrix-bridge-appservice-webhooks/tasks/setup_uninstall.yml
- roles/matrix-bridge-appservice-webhooks/tasks/validate_config.yml
- roles/matrix-bridge-appservice-webhooks/templates/database.json.j2
- roles/matrix-bridge-appservice-webhooks/templates/schema.yml.j2
- roles/matrix-bridge-appservice-webhooks/templates/systemd/matrix-appservice-webhooks.service.j2
- setup.yml
Added matrix-appservice-webhooks to the playbook, adjusted group_vars and setup.yml.
> Add matrix-appservice-webhooks role.

- roles/matrix-corporal/tasks/self_check_corporal.yml
- roles/matrix-mxisd/tasks/self_check_mxisd.yml
- roles/matrix-nginx-proxy/tasks/self_check_well_known.yml
- roles/matrix-nginx-proxy/tasks/self_check_well_known_file.yml
- roles/matrix-riot-web/tasks/self_check_riot_web.yml
- roles/matrix-synapse/tasks/self_check_client_api.yml
- roles/matrix-synapse/tasks/self_check_federation_api.yml
Documented here: https://docs.ansible.com/ansible/2.9/modules/uri_module.html
> uri.follow_redirects is now a string field

- docs/configuring-playbook-bridge-appservice-webhooks.md
Added steps to configure appservice webhooks in the dimension manager.
> Configuring webhooks

- docs/configuring-playbook-dimension.md
I am new to synapse. Thanks so much for these playbooks!
I wasn't sure how you actual activate dimensions after setting these variables. Should you re run 
ansible-playbook -i inventory/hosts setup.yml --tags=setup-all
ansible-playbook -i inventory/hosts setup.yml --tags=start
? If so perhaps you could tell the readers to do this somewhere in the help file.
PS I don't know how to use gitbub so sorry if what I'm doing is incorrect.
Thanks =]
> how to activate dimensions

- roles/matrix-synapse/defaults/main.yml
Release notes here:
https://github.com/matrix-org/synapse/releases/tag/v1.12.0
> Release synapse v.1.12.0

- docs/configuring-playbook-shared-secret-auth.md
added path to the correct vars.yaml in matrix-synapse to help better configuration for beginners
> clarify the config path

- docs/prerequisites.md
- roles/matrix-base/tasks/sanity_check.yml
- roles/matrix-base/tasks/server_base/setup.yml
- roles/matrix-base/tasks/server_base/setup_archlinux.yml
- roles/matrix-common-after/tasks/start.yml
- roles/matrix-mxisd/tasks/setup_mxisd.yml
- roles/matrix-nginx-proxy/tasks/ssl/setup_ssl_self_signed.yml
- roles/matrix-synapse/tasks/ext/synapse-simple-antispam/setup_install.yml
- roles/matrix-synapse/tasks/update_user_password.yml
As promised on IRC I worked my way through the files and tried to port everything to Archlinux.
I assume it is working so far at least for installing. I ask you to review things here so that I can correct things if needed.
> Added support for arch linux

- roles/matrix-jitsi/templates/web/config.js.j2
According to [docker-jitsi-meet](https://github.com/jitsi/docker-jitsi-meet/blob/fabfb2a676175894510f78ec8de5d10ae8c10e8c/web/rootfs/etc/cont-init.d/10-config#L89-L99) repo
> fix jitsi guests mode according to docker-jitsi-meet repo

- docs/configuring-playbook-bridge-mx-bridge-skype.md
- group_vars/matrix_servers
- roles/matrix-bridge-mx-puppet-skype/defaults/main.yml
- roles/matrix-bridge-mx-puppet-skype/tasks/init.yml
- roles/matrix-bridge-mx-puppet-skype/tasks/main.yml
- roles/matrix-bridge-mx-puppet-skype/tasks/setup_install.yml
- roles/matrix-bridge-mx-puppet-skype/tasks/setup_uninstall.yml
- roles/matrix-bridge-mx-puppet-skype/tasks/validate_config.yml
- roles/matrix-bridge-mx-puppet-skype/templates/systemd/matrix-mx-puppet-skype.service.j2
- setup.yml
Role for https://github.com/Sorunome/mx-puppet-skype
> Initial mx-puppet-skype bridge role

- docs/alternative-architectures.md
- docs/prerequisites.md
- docs/self-building.md
- group_vars/matrix_servers
- roles/matrix-nginx-proxy/defaults/main.yml
Add better support for non amd64 architectures, hopefully replacing the self-building nomenclature which (in my opinion) is a little user hostile. :)
> Architecture

- docs/configuring-playbook-jitsi.md
Modification of documentation to help people configure playbook to have client in LAN working
> Add information to make jitsi work with a client in LAN

- CHANGELOG.md
- roles/matrix-bridge-appservice-irc/defaults/main.yml
Note the potential breaking change
Resolves #474
> Update matrix-appservice-irc to 0.16.0

- docs/configuring-well-known.md
The provided example for federation seems to be for Caddy 2.
As I am stuck with Caddy 1 for now, this is the proxy setting for Caddy 1.
> Add caddy 1 well-known example

- docs/configuring-playbook-turn.md
Just by chance stumbled upon a small piece of missing information during reading.
> Added a documentation enhancement regarding external TURN server

- roles/matrix-base/defaults/main.yml
- roles/matrix-base/tasks/main.yml
- roles/matrix-base/tasks/setup_matrix_base.yml
- roles/matrix-base/tasks/setup_matrix_user.yml
As on my system 991 is already take, and also as I agree with : https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/65
Thank you for the great work !
> Remove default UID/GID

- docs/maintenance-synapse.md
.. because less pain :sweat_smile:
> Document how to administer synapse database via tunneled web-frontend

- roles/matrix-synapse/defaults/main.yml
- roles/matrix-synapse/tasks/ext/synapse-simple-antispam/setup_install.yml
- roles/matrix-synapse/tasks/validate_config.yml
- roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
- roles/matrix-synapse/templates/synapse/systemd/matrix-synapse.service.j2
> Synapse v.1.14.0

- docs/configuring-playbook-jitsi.md
> Documentation of the variables added in the PR #548

- README.md
- docs/configuring-playbook-bridge-mx-puppet-instagram.md
- group_vars/matrix_servers
- roles/matrix-bridge-mx-puppet-instagram/defaults/main.yml
- roles/matrix-bridge-mx-puppet-instagram/tasks/init.yml
- roles/matrix-bridge-mx-puppet-instagram/tasks/main.yml
- roles/matrix-bridge-mx-puppet-instagram/tasks/setup_install.yml
- roles/matrix-bridge-mx-puppet-instagram/tasks/setup_uninstall.yml
- roles/matrix-bridge-mx-puppet-instagram/tasks/validate_config.yml
- roles/matrix-bridge-mx-puppet-instagram/templates/config.yaml.j2
- roles/matrix-bridge-mx-puppet-instagram/templates/systemd/matrix-mx-puppet-instagram.service.j2
- setup.yml
Adds https://github.com/Sorunome/mx-puppet-instagram.
Still needs documentation and testing
> Add mx-puppet-instagram

- README.md
- docs/configuring-playbook-bridge-mx-puppet-discord.md
- group_vars/matrix_servers
- roles/matrix-bridge-mx-puppet-discord/defaults/main.yml
- roles/matrix-bridge-mx-puppet-discord/tasks/init.yml
- roles/matrix-bridge-mx-puppet-discord/tasks/main.yml
- roles/matrix-bridge-mx-puppet-discord/tasks/setup_install.yml
- roles/matrix-bridge-mx-puppet-discord/tasks/setup_uninstall.yml
- roles/matrix-bridge-mx-puppet-discord/tasks/validate_config.yml
- roles/matrix-bridge-mx-puppet-discord/templates/config.yaml.j2
- roles/matrix-bridge-mx-puppet-discord/templates/systemd/matrix-mx-puppet-discord.service.j2
- setup.yml
The one last issue is that there is no official docker image, the one specified is 3 months old, and gives no guarantees on what's in it 
I opened an issue on mx-puppet-discord
https://github.com/matrix-discord/mx-puppet-discord/issues/80
#469 
https://github.com/matrix-discord/mx-puppet-discord
> Add mx-puppet-discord

- README.md
- docs/configuring-playbook-bridge-mx-puppet-steam.md
- group_vars/matrix_servers
- roles/matrix-bridge-mx-puppet-steam/defaults/main.yml
- roles/matrix-bridge-mx-puppet-steam/tasks/init.yml
- roles/matrix-bridge-mx-puppet-steam/tasks/main.yml
- roles/matrix-bridge-mx-puppet-steam/tasks/setup_install.yml
- roles/matrix-bridge-mx-puppet-steam/tasks/setup_uninstall.yml
- roles/matrix-bridge-mx-puppet-steam/tasks/validate_config.yml
- roles/matrix-bridge-mx-puppet-steam/templates/config.yaml.j2
- roles/matrix-bridge-mx-puppet-steam/templates/systemd/matrix-mx-puppet-steam.service.j2
- setup.yml
Successfully tested and working
https://github.com/icewind1991/mx-puppet-steam
It's basically the mx-puppet-discord commit with discord replaced to steam and the right docker image set.
> Add mx-puppet-steam

- README.md
links from Discord and twitter was mixed up
> swap links

- roles/matrix-bridge-mautrix-telegram/defaults/main.yml
fixes matrix users unable to delete messages
> Bump version of mautrix-telegram to 0.8.2

- docs/configuring-playbook-dimension.md
Potentially the CURLing could be a better approach, since then you don't leave spare sessions hanging.
> Add a secondary option on how to get access token

- README.md
Stating "many times" makes me think there is a finite amount of times I can run it before it *will* start causing trouble. But this is not true. So just state it can me ran more than once without causing trouble :)
> Update README.md -> 'many times' -> 'more than once'

- examples/caddy2/Caddyfile
I did a failure, so the identity server wasn't reachable. But now it should work.
> Corrects the Caddyfile

- roles/matrix-client-element/templates/welcome.html.j2
fix #659 missing translations when guest users are allowed on Element
> Element web : update welcome page template

- docs/maintenance-and-troubleshooting.md
- roles/matrix-common-after/tasks/main.yml
- roles/matrix-common-after/tasks/run_docker_prune.yml
Related to https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/536
Tested on my own instance.
I have put it in **matrix-common-after**, but maybe it should be in **matrix-base**, or in a new role ... I don't know...
> Add docker prune

- roles/matrix-bot-matrix-reminder-bot/templates/systemd/matrix-bot-matrix-reminder-bot.service.j2
- roles/matrix-bridge-appservice-discord/templates/systemd/matrix-appservice-discord.service.j2
- roles/matrix-bridge-appservice-irc/templates/systemd/matrix-appservice-irc.service.j2
- roles/matrix-bridge-appservice-slack/templates/systemd/matrix-appservice-slack.service.j2
- roles/matrix-bridge-appservice-webhooks/templates/systemd/matrix-appservice-webhooks.service.j2
- roles/matrix-bridge-mautrix-facebook/templates/systemd/matrix-mautrix-facebook.service.j2
- roles/matrix-bridge-mautrix-hangouts/templates/systemd/matrix-mautrix-hangouts.service.j2
- roles/matrix-bridge-mautrix-telegram/templates/systemd/matrix-mautrix-telegram.service.j2
- roles/matrix-bridge-mautrix-whatsapp/templates/systemd/matrix-mautrix-whatsapp.service.j2
- roles/matrix-bridge-mx-puppet-discord/templates/systemd/matrix-mx-puppet-discord.service.j2
- roles/matrix-bridge-mx-puppet-instagram/templates/systemd/matrix-mx-puppet-instagram.service.j2
- roles/matrix-bridge-mx-puppet-skype/templates/systemd/matrix-mx-puppet-skype.service.j2
- roles/matrix-bridge-mx-puppet-slack/templates/systemd/matrix-mx-puppet-slack.service.j2
- roles/matrix-bridge-mx-puppet-steam/templates/systemd/matrix-mx-puppet-steam.service.j2
- roles/matrix-bridge-mx-puppet-twitter/templates/systemd/matrix-mx-puppet-twitter.service.j2
- roles/matrix-bridge-sms/templates/systemd/matrix-sms-bridge-database.service.j2
- roles/matrix-bridge-sms/templates/systemd/matrix-sms-bridge.service.j2
You wanted this in https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/649
> Shameless refactor of all systemd descriptions for bridges

- docs/configuring-playbook-own-webserver.md
Fixes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/687
> Added docker-compose example for launching Traefik.

- roles/matrix-bridge-mautrix-telegram/defaults/main.yml
https://github.com/tulir/mautrix-telegram/releases/tag/v0.9.0
> update mautrix-telegram to 0.9.0

- group_vars/matrix_servers
That could save someone a lot of trouble...
> Note about the max length of the postgres password

- docs/configuring-playbook-jitsi.md
comments in config.js must begin with two slashes
> fixes config.js

- ansible.cfg
- examples/caddy2/Caddyfile
- examples/caddy2/README.md
Added the tls directive again, but added a Readme-File to link to the Documentation and Describe a bit of the directives.
> Example Files for Caddy2

- roles/matrix-registration/tasks/list_tokens.yml
- roles/matrix-registration/tasks/main.yml
ansible-playbook -i inventory/hosts setup.yml --tags=list-matrix-registration-tokens
> Call API list tokens enpoint

- docs/configuring-playbook-bridge-mautrix-telegram.md
- group_vars/matrix_servers
- roles/matrix-bridge-mautrix-telegram/defaults/main.yml
- roles/matrix-bridge-mautrix-telegram/tasks/setup_install.yml
I have tested it today with my RPi4 and it works. Without this, you cannot use the telegram bridge unless you have a 64-bit intel/amd processor.
> Local rebuild for Telegram

- roles/matrix-client-element/defaults/main.yml
https://github.com/vector-im/element-web/releases/tag/v1.7.17
https://hub.docker.com/layers/vectorim/element-web/v1.7.17/images/sha256-d5a1e04cf8fb8d6a1bdab378adaa6b72b4dcfc5d46cbb73e736bb6d799354f1a?context=explore
> Update element-web (1.7.16 -> 1.7.17)

- CHANGELOG.md
propose explicit showing single quotes around the password, since I forgot to put them there.
> small fix to CHANGELOG.md

- docs/faq.md
Thanks for the nice FAQ. While reading it, I tried to correct what seemed to be typos to me. Feel free to just discard the changes if they are not helpful.
> Correct some typos in FAQ

- roles/matrix-synapse/tasks/rust-synapse-compress-state/compress_room.yml
Fixes:
https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/833
> Name the Synapse database on state compression import

- README.md
I also moved matrix-sms-bridge up to match the order from container-images.md
> Add mx-puppet-skype and mx-puppet-slack to README

- roles/matrix-base/tasks/server_base/setup_debian.yml
Oops.
Fixes https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/841#issuecomment-770189542
> Fixed missing quotes

- roles/matrix-bridge-appservice-irc/defaults/main.yml
> Update IRC bridge to 0.23.0

- roles/matrix-client-element/defaults/main.yml
https://github.com/vector-im/element-web/releases/tag/v1.7.20
https://hub.docker.com/layers/vectorim/element-web/v1.7.20/images/sha256-44cae3a532d86c16940deb70866b522ba6acc8c5d7adf3c661cfc8b06f1de681?context=explore
>  Upgrade Element (1.7.19 -> 1.7.20)

- docs/configuring-playbook-etherpad.md
Warn users of the known bug https://github.com/turt2live/matrix-dimension/issues/395
Merging would close https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/849
> Etherpad docs: Padname length bug

- docs/configuring-well-known.md
Added instructions for Netlify hosting in 'configuring-well-known.md'
> Add Netlify instructions

- docs/configuring-playbook-bridge-mautrix-telegram.md
Thank you so much for putting together this playbook. It definitely helped me to setup my synapse server
When setting my Telegram bridge up I noticed that this markdown document was not using the correct tag. Definitely very minor change :)
> Update Telegram bridge setup link

- docs/configuring-playbook.md
instead of bullet points which make it more difficult to tell whether or not you completed all of the steps
> Make steps in configuring-playbook.md numbered

- README.md
- docs/configuring-dns.md
- docs/configuring-playbook-bot-go-neb.md
- group_vars/matrix_servers
- roles/matrix-base/defaults/main.yml
- roles/matrix-bot-go-neb/defaults/main.yml
- roles/matrix-bot-go-neb/tasks/init.yml
- roles/matrix-bot-go-neb/tasks/main.yml
- roles/matrix-bot-go-neb/tasks/setup_install.yml
- roles/matrix-bot-go-neb/tasks/setup_uninstall.yml
- roles/matrix-bot-go-neb/tasks/validate_config.yml
- roles/matrix-bot-go-neb/templates/config.yaml.j2
- roles/matrix-bot-go-neb/templates/systemd/matrix-bot-go-neb.service.j2
- roles/matrix-nginx-proxy/defaults/main.yml
- roles/matrix-nginx-proxy/tasks/setup_nginx_proxy.yml
- roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-bot-go-neb.conf.j2
- setup.yml
Hello!
I added support for the [Go-NEB](https://github.com/matrix-org/go-neb) bot. I pretty much just copied the [matrix-reminder-bot](https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/roles/matrix-bot-matrix-reminder-bot) and modified it to my needs.
Please let me know if I need to make changes. The configuration of the bot is quite dynamic, so I opted to keep the original config structure. Because of this the vars.yml file might become too large.
> Added support for the Go-NEB bot

- roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-domain.conf.j2
Missed by https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/9b72384df7a7663079b41ad17768ff9e9b4b9320
> Set X-Forwarded-Proto on federation requests

- roles/matrix-bridge-appservice-irc/defaults/main.yml
Update to 0.25; doesn't seem to change much.
https://github.com/matrix-org/matrix-appservice-irc/releases
> Update IRC appservice

- roles/matrix-synapse/defaults/main.yml
Note: ARM image is not available yet
> Updated synapse 1.29.0 -> 1.30.0

- docs/configuring-dns.md
> Make ma1sd's SRV record optional

- roles/matrix-bridge-mautrix-signal/templates/config.yaml.j2
See these last commits:
tulir/mautrix-signal@4fc34330c1f6947aece67863b0d04da34c776f80
tulir/mautrix-signal@64bc5c36a509ba435a0b01cf44afb1b5d2642efd
tulir/mautrix-signal@ddda1666d41d28750cc59d070e4388b24add6ad9
> Updates to mautrix-signal config

- docs/maintenance-postgres.md
- docs/maintenance-synapse.md
Fixes #57
Documents #532 but would still be nice to set some good defaults
>  Add some advice about making Synapse faster

- README.md
- docs/configuring-playbook-bot-mjolnir.md
- docs/configuring-playbook.md
- docs/container-images.md
- group_vars/matrix_servers
- roles/matrix-bot-mjolnir/defaults/main.yml
- roles/matrix-bot-mjolnir/tasks/init.yml
- roles/matrix-bot-mjolnir/tasks/main.yml
- roles/matrix-bot-mjolnir/tasks/setup_install.yml
- roles/matrix-bot-mjolnir/tasks/setup_uninstall.yml
- roles/matrix-bot-mjolnir/tasks/validate_config.yml
- roles/matrix-bot-mjolnir/templates/production.yaml.j2
- roles/matrix-bot-mjolnir/templates/systemd/matrix-bot-mjolnir.service.j2
- setup.yml
Fixes #353
This is just the bot portion of mjolnir, not the synapse module.
Todo:
- It seems to start before Synapse so it crashes but after it automatically restarts then it works fine. I thought this is what the `..systemd_required_services_list` variable was for but I have Synapse in there and it doesn't seem to make a difference.
> Add mjolnir

- docs/configuring-playbook-bot-mjolnir.md
- docs/configuring-playbook.md
I always notice more things once it gets merged 😅
> Couple of additional tweaks to the mjolnir docs

- docs/configuring-playbook-prometheus-grafana.md
- roles/matrix-grafana/defaults/main.yml
- roles/matrix-grafana/templates/grafana.ini.j2
> Allow special characters in Grafana password and upgrade Grafana 

- roles/matrix-bridge-appservice-webhooks/tasks/init.yml
Fix for #966 .
Please test. Works for me.
Generic configuration branch is untested.
> Fix for"nginx and two other services boot loops" #966

- docs/configuring-awx-system.md
- roles/matrix-awx/tasks/purge_media_local.yml
- roles/matrix-awx/tasks/purge_media_main.yml
- roles/matrix-awx/tasks/purge_media_remote.yml
- Fix remote and local media purge
- base_domain_used can now be seamlessly changed after initial provision
- Jitsi now disabled for Micro to Medium sized droplets
- Minor fixes
For updates on this project visit: [#general:gomatrixhosting.com](https://matrix.to/#/#general:gomatrixhosting.com)
> GoMatrixHosting v0.4.5 update

- roles/matrix-jitsi/defaults/main.yml
- roles/matrix-jitsi/templates/prosody/env.j2
- roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-jitsi.conf.j2
> Update Jitsi (5142 -> 5765-1)

- docs/configuring-playbook-own-webserver.md
> Mention updating Nginx

- docs/configuring-awx-system.md
- roles/matrix-awx/tasks/main.yml
- roles/matrix-awx/tasks/purge_database_build_list.yml
- roles/matrix-awx/tasks/purge_database_events.yml
- roles/matrix-awx/tasks/purge_database_main.yml
- roles/matrix-awx/tasks/purge_database_no_local.yml
- roles/matrix-awx/tasks/purge_database_users.yml
- roles/matrix-awx/tasks/purge_media_remote.yml
- roles/matrix-common-after/tasks/awx_post.yml
- roles/matrix-synapse/tasks/rust-synapse-compress-state/main.yml
- Add database purge section.
- Add markdown copy of User manual.
- Tweak compress state find rooms timeout.
- Update compile AWX instructions for custom branding and radius fix.
To join in on the discussion about this project visit the Matrix room: #general:gomatrixhosting.com
> GoMatrixHosting v0.4.6

- README.md
Hi,
After discussion with Slavi ([link to private chat](https://matrix.to/#/!GWNJzoHiCybWdouIiP:etke.cc/$_XpK8-ucbWvxY667IVZ9ROZPqSVkG2UGglNagrbDQmw?via=etke.cc&via=devture.com)), we agreed on adding services that use matrix-docker-ansible-deploy as a core to list in README file.
@GoMatrixHosting could you approve the description is correct, please? (Sorry, I just put what I know about your service)
> Added services built by community

- roles/matrix-grafana/defaults/main.yml
- roles/matrix-prometheus/defaults/main.yml
-  Update prometheus (2.26.0->2.27.0)
-  Update grafana (7.5.5->7.5.6)
>  Update prometheus & grafana

- README.md
- docs/configuring-playbook-bridge-heisenbridge.md
- docs/configuring-playbook.md
- group_vars/matrix_servers
- roles/matrix-bridge-heisenbridge/defaults/main.yml
- roles/matrix-bridge-heisenbridge/tasks/init.yml
- roles/matrix-bridge-heisenbridge/tasks/main.yml
- roles/matrix-bridge-heisenbridge/tasks/setup_install.yml
- roles/matrix-bridge-heisenbridge/tasks/setup_uninstall.yml
- roles/matrix-bridge-heisenbridge/templates/systemd/matrix-heisenbridge.service.j2
- setup.yml
This is based on the SMS bridge as it seemed the most simple.
Registration file generation differs from most other bridges as it doesn't use a template but a generator command during setup phase.
> Add Heisenbridge

- roles/matrix-grafana/defaults/main.yml
** With some minor fixed https://github.com/grafana/grafana/releases/tag/v7.5.7 **
> Update grafana (7.5.6->7.5.7)

- roles/matrix-client-hydrogen/tasks/setup.yml
- roles/matrix-client-hydrogen/templates/nginx.conf.j2
- roles/matrix-client-hydrogen/templates/systemd/matrix-client-hydrogen.service.j2
Fixes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1077
> Fix hydrogen

- docs/configuring-playbook-bot-mjolnir.md
- roles/matrix-synapse/defaults/main.yml
- roles/matrix-synapse/tasks/ext/mjolnir-antispam/setup.yml
- roles/matrix-synapse/tasks/ext/mjolnir-antispam/setup_install.yml
- roles/matrix-synapse/tasks/ext/mjolnir-antispam/setup_uninstall.yml
- roles/matrix-synapse/tasks/ext/setup.yml
Mjolnir antispam modul added to playbook
Docs updated
> Mjolnir antispam

- docs/maintenance-postgres.md
Added a mid-sized VPS configuration with configuration changes to the PostgreSQL database config.
Deleted single quotes in one of the examples to unify the examples
> Update PostgreSQL Maintenance page

- docs/maintenance-migrating.md
Clarify that migration as per this document is only applicable between servers of same architecture
> Server migration doc update

- roles/matrix-client-hydrogen/defaults/main.yml
Update hydrogen-web version to v0.1.56
> Update hydrogen-web version to v0.1.56

- roles/matrix-client-hydrogen/defaults/main.yml
https://github.com/vector-im/hydrogen-web/releases/tag/v0.1.57
> update hydrogen v0.1.56 -> v0.1.57

- roles/matrix-awx/tasks/backup_server.yml
- roles/matrix-awx/tasks/export_server.yml
- roles/matrix-awx/tasks/import_awx.yml
- roles/matrix-awx/tasks/main.yml
- Avoid keeping a copy of the media repository locally, saves space in /chroot/export.
- Improve synchronization with backups and exports between the copying the configs + media repository and the database snapshot.
- Improve recovery process to ensure downtime only during DNS changes.
- Add 'Export Server' job template for generating SFTP export.
- Fix for broken SSL renewal on AWX.
- Fixed a bug with deleting subscriptions.
> GoMatrixHosting v0.5.0

- roles/matrix-grafana/defaults/main.yml
Ref: https://github.com/grafana/grafana/releases/tag/v8.0.3
> Update grafana 8.0.2 -> 8.0.3

- roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-element.conf.j2
Adopted From Here: [element-web#configuration-best-practices](https://github.com/vector-im/element-web#configuration-best-practices)
> Content-Security-Policy For Element Web

- roles/matrix-coturn/defaults/main.yml
https://github.com/coturn/coturn/blob/master/docker/coturn/CHANGELOG.md
> Coturn update 4.5.2 -> 4.5.2-r2

- roles/matrix-client-hydrogen/defaults/main.yml
> Update hydrogen main.yml

- roles/matrix-bridge-heisenbridge/tasks/setup_uninstall.yml
> heisenbridge: fix service name in setup_uninstall.yml

- roles/matrix-bridge-appservice-irc/defaults/main.yml
https://github.com/matrix-org/matrix-appservice-irc/releases/tag/0.27.0
The default settings should probably be updated, but I think it's fine for now.
> Update IRC bridge

- roles/matrix-synapse/defaults/main.yml
https://github.com/matrix-org/synapse/releases/tag/v1.37.1
> Updating to latest synapse release (performance regression)

- roles/matrix-awx/tasks/set_variables_synapse.yml
GoMatrixHosting v0.5.1
- Add '00 - Create Wireguard Server' template for AWX admin to provision Wireguard servers that on-premises servers can use to connect.
- Subscription involved can view an additional '0 - {{ subscription_id }} - Provision Wireguard Server' template.
- Add /docs/Setup_Wireguard_Server.md guide.
- Add onboarding script for Windows 10 users.
- Raise maximum download size to 200MB.
> GoMatrixHosting v0.5.1

- examples/apache/matrix-synapse.conf
Added some optional reverse proxy passthroughs for synapse-admin and the admin api.
> Added proxy config for synapse-admin

- roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-base-domain.conf.j2
`root /nginx-data/matrix-domain;` should be root `/matrix/nginx-proxy/data/matrix-domain;`
> root path for the base domain is wrong

- roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml
See https://github.com/mautrix/whatsapp/releases/tag/v0.1.8
> whatsapp bridge has new docker image location

- group_vars/matrix_servers
- roles/matrix-awx/tasks/customise_website_access_export.yml
- roles/matrix-common-after/tasks/awx_post.yml
- roles/matrix-nginx-proxy/defaults/main.yml
- roles/matrix-nginx-proxy/tasks/setup_nginx_proxy.yml
- roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-base-domain.conf.j2
GoMatrixHosting v0.5.7
- Prevent Provision stage re-writing variables it should only write on the first run, see [#12](https://gitlab.com/GoMatrixHosting/ansible-provision-server/-/issues/12).
- Fix SFTP website upload, see [#10](https://gitlab.com/GoMatrixHosting/gomatrixhosting-matrix-docker-ansible-deploy/-/issues/10).
If there's anything problematic about this release please let me know, we can revise it.  :+1:
> GoMatrixHosting v0.5.7

- roles/matrix-client-element/defaults/main.yml
Element web/desktop has just been updated to fix some regressions in regard to VoIP.
>  Upgrade Element (1.8.0 -> 1.8.1)

- README.md
- docs/configuring-playbook-bridge-mautrix-facebook.md
- docs/configuring-playbook-bridge-mautrix-hangouts.md
- docs/configuring-playbook-bridge-mautrix-instagram.md
- docs/configuring-playbook-bridge-mautrix-signal.md
- docs/configuring-playbook-bridge-mautrix-telegram.md
- docs/configuring-playbook-bridge-mautrix-whatsapp.md
- docs/container-images.md
- roles/matrix-bridge-mautrix-facebook/defaults/main.yml
- roles/matrix-bridge-mautrix-hangouts/defaults/main.yml
- roles/matrix-bridge-mautrix-instagram/defaults/main.yml
- roles/matrix-bridge-mautrix-signal/templates/config.yaml.j2
- roles/matrix-bridge-mautrix-signal/templates/registration.yaml.j2
- roles/matrix-bridge-mautrix-telegram/defaults/main.yml
- roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml
In this PR I updated docker images and links to the mautrix bridges repos, every link mentioning tulir should've been changed.
> Update mautrix links

- roles/matrix-bridge-appservice-irc/defaults/main.yml
https://github.com/matrix-org/matrix-appservice-irc/releases/tag/0.30.0
> Update IRC appservice to version v0.30.0

- roles/matrix-postgres/defaults/main.yml
https://www.postgresql.org/about/news/postgresql-134-128-1113-1018-9623-and-14-beta-3-released-2277/
> Postgres Minor Updates

- docs/configuring-playbook-jitsi.md
- roles/matrix-jitsi/defaults/main.yml
- roles/matrix-jitsi/templates/prosody/env.j2
- add support for A/V Moderation [matrix_jitsi_enable_av_moderation default True]
- add ability to configure external TURN server
> Jitsi Update (stable-5963 -> stable-6173)

- roles/matrix-nginx-proxy/defaults/main.yml
> nginx update v1.21.2

- roles/matrix-bridge-heisenbridge/defaults/main.yml
> Bump Heisenbridge to v1.0.1

- roles/matrix-nginx-proxy/defaults/main.yml
- roles/matrix-nginx-proxy/templates/nginx/nginx.conf.j2
> Added variable matrix_nginx_proxy_request_timeout

- roles/matrix-grafana/defaults/main.yml
Upgrade grafana (8.1.2 -> 8.1.3)
> Upgrade grafana (8.1.2 -> 8.1.3)

- roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.1.0
> Upgrade Heisenbridge (1.0.1 -> 1.1.0)

- roles/matrix-bridge-heisenbridge/defaults/main.yml
Bug fixes for this weeks release :pray:
> Upgrade Heisenbridge (1.1.0 -> 1.1.1)

- roles/matrix-bot-mjolnir/defaults/main.yml
Upgrade mjolnir (v0.1.19 -> v1.1.20)
Remark: interesting version number increase :-)
> Upgrade mjolnir (v0.1.19 -> v1.1.20)

- roles/matrix-bridge-appservice-irc/defaults/main.yml
Update irc bridge version (release-0.30.0 -> release-0.31.0)
> Update irc bridge version (release-0.30.0 -> release-0.31.0)

- roles/matrix-bridge-heisenbridge/defaults/main.yml
Some regressions fixed and birdge read receipts added
> Upgrade Heisenbridge (1.2.0 -> 1.2.1)

- docs/configuring-playbook-prometheus-grafana.md
i set it up like this. thoughts?
could also go in an extra document, i'm not sure how commonly this is needed vs how advanced it is.
> doc: how to export node and postgres sans grafana

- README.md
- roles/matrix-awx/tasks/backup_server.yml
- roles/matrix-awx/tasks/create_session_token.yml
- roles/matrix-awx/tasks/create_user.yml
- roles/matrix-awx/tasks/customise_website_access_export.yml
- roles/matrix-awx/tasks/delete_session_token.yml
- roles/matrix-awx/tasks/export_server.yml
- roles/matrix-awx/tasks/load_hosting_and_org_variables.yml
- roles/matrix-awx/tasks/main.yml
- roles/matrix-awx/tasks/purge_database_main.yml
- roles/matrix-awx/tasks/purge_media_main.yml
- roles/matrix-awx/tasks/rotate_ssh.yml
- roles/matrix-awx/tasks/set_variables_corporal.yml
- roles/matrix-awx/tasks/set_variables_dimension.yml
- roles/matrix-awx/tasks/set_variables_element.yml
- roles/matrix-awx/tasks/set_variables_element_subdomain.yml
- roles/matrix-awx/tasks/set_variables_jitsi.yml
- roles/matrix-awx/tasks/set_variables_ma1sd.yml
- roles/matrix-awx/tasks/set_variables_mailer.yml
- roles/matrix-awx/tasks/set_variables_synapse.yml
- roles/matrix-awx/tasks/set_variables_synapse_admin.yml
GoMatrixHosting v0.6.1
- Use proper 'awx.awx.tower_token' module method to generate a persistent 'master token' then 'session tokens' for each individial run. Avoids storing the AWX admins password in plaintext on the AWX server. See [#2](https://gitlab.com/GoMatrixHosting/matrix-docker-ansible-deploy/-/issues/2) and [#13](https://gitlab.com/GoMatrixHosting/gomatrixhosting-matrix-docker-ansible-deploy/-/issues/13).
- Disable scm_update_on_launch on new users deploy project and make the hourly "Deploy/Update All Servers" update those projects, improves the speed of deploy stage jobs. See [#7](https://gitlab.com/GoMatrixHosting/ansible-create-delete-subscription-membership/-/issues/7).
Follow us on [GitLab](https://gitlab.com/GoMatrixHosting), or come say hello at …
> Gomatrixhosting testing

- roles/matrix-awx/surveys/bridge_discord_appservice.json.j2
GoMatrixHosting v0.6.4 :rocket: 
```
- Fix FreeRADIUS/OAuth timeout issue. See [#21](https://gitlab.com/GoMatrixHosting/create-awx-system/-/issues/21).
- Upgraded Wireguard servers to support Debian 11.
- Update 'Rotate_AWX_Passwords_Keys.md' doc to include Wireguard server SSH rotation. See [#8](https://gitlab.com/GoMatrixHosting/ansible-create-delete-subscription-membership/-/issues/8).
- Added missing "ansible_connection: local" variable to AWX admins localhost.
```
Upgrade Notes v0.6.4 :rocket: 
```
- Re-install AWX.
- Re-provision all servers.
```
Follow us on [GitLab](https://gitlab.com/GoMatrixHosting), or come say hello at [GoMatrixHosting](https://matrix.to/#/#general:gomatrixhosting.com)!
> GoMatrixHosting v0.6.4

- roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.4.1
I used the web editor on mobile to edit the file, hope it works 🤞
> Upgrade Heisenbridge (1.4.0 -> 1.4.1)

- group_vars/matrix_servers
- roles/matrix-awx/tasks/set_variables_ma1sd.yml
- roles/matrix-ma1sd/defaults/main.yml
- roles/matrix-ma1sd/templates/systemd/matrix-ma1sd.service.j2
- roles/matrix-nginx-proxy/defaults/main.yml
Changed hard coded port 8090 to `matrix_ma1sd_default_port` wherever possible.
> change port 8090 to matrix_ma1sd_default_port

- docs/configuring-playbook-prometheus-grafana.md
So obviously I am submitting this PR because I put the password in plain text first, and at some point I found the explanation in https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/4586efebd7b7feb9d1936485168d84d25ff250dc/roles/matrix-nginx-proxy/defaults/main.yml#L187.
> chore: adding some explanations about setting prometheus password

- roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.5.0 :partying_face:
> Upgrade Heisenbridge (1.4.1 -> 1.5.0)

- roles/matrix-client-element/defaults/main.yml
https://github.com/vector-im/element-web/releases/tag/v1.9.4
https://hub.docker.com/layers/vectorim/element-web/v1.9.4/images/sha256-047dc6f84a815db0aaac1295213b3447ac6ee1e38a5e7b54ce0853ac2e3e2740?context=explore
> Upgrade Element (v1.9.4)

- roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.6.0
> Upgrade Heisenbridge (1.5.0 -> 1.6.0)

- roles/matrix-bridge-mautrix-facebook/defaults/main.yml
Upgrade to latest version 0.3.2
> Upgrade Mautrix Facebook bridge version

- group_vars/matrix_servers
- roles/matrix-dimension/defaults/main.yml
- roles/matrix-nginx-proxy/defaults/main.yml
- roles/matrix-synapse/defaults/main.yml
- roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
- roles/matrix-synapse/templates/synapse/systemd/matrix-synapse.service.j2
> Synapse container federation port

- roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.7.0 :partying_face:
> Upgrade Heisenbridge (1.6.0 -> 1.7.0)

- roles/matrix-client-element/defaults/main.yml
Upgrade Element version (1.9.4 --> 1.9.5)
> Upgrade Element version (1.9.4 --> 1.9.5)

- roles/matrix-bridge-mautrix-telegram/defaults/main.yml
> Update matrix-bridge-mautrix-telegram version

- roles/matrix-grafana/defaults/main.yml
Update version grafana (8.2.2 -> 8.3.0)
> Update version grafana (8.2.2 -> 8.3.0)

- roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
> Fix email sending broken by #1406

- .github/workflows/ansible-lint.yml
avoiding common pitfalls that can easily lead to bugs or make code harder to maintain
> ansible lint workflow

- roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.8.0
> Upgrade Heisenbridge (1.7.1 -> 1.8.0)

- roles/matrix-etherpad/defaults/main.yml
- roles/matrix-etherpad/templates/settings.json.j2
Extend the config template with the lines added in the past year
> Upgrade Etherpad to 1.8.16

- roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.9.0
> Upgrade Heisenbridge (1.8.2 -> 1.9.0)

- README.md
- docs/configuring-dns.md
- docs/configuring-playbook-client-cinny.md
- docs/configuring-playbook.md
- docs/self-building.md
- group_vars/matrix_servers
- roles/matrix-base/defaults/main.yml
- roles/matrix-client-cinny/defaults/main.yml
- roles/matrix-client-cinny/tasks/init.yml
- roles/matrix-client-cinny/tasks/main.yml
- roles/matrix-client-cinny/tasks/self_check.yml
- roles/matrix-client-cinny/tasks/setup_install.yml
- roles/matrix-client-cinny/tasks/setup_uninstall.yml
- roles/matrix-client-cinny/tasks/validate_config.yml
- roles/matrix-client-cinny/templates/config.json.j2
- roles/matrix-client-cinny/templates/nginx.conf.j2
- roles/matrix-client-cinny/templates/systemd/matrix-client-cinny.service.j2
- roles/matrix-nginx-proxy/defaults/main.yml
- roles/matrix-nginx-proxy/tasks/setup_nginx_proxy.yml
- roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-client-cinny.conf.j2
- setup.yml
Hi there,
That PR adds matrix-client-cinny role
closes #1212
> added matrix-client-cinny

- README.md
- docs/configuring-playbook-bot-honoroit.md
- docs/configuring-playbook.md
- docs/container-images.md
- docs/self-building.md
- group_vars/matrix_servers
- roles/matrix-bot-honoroit/defaults/main.yml
- roles/matrix-bot-honoroit/tasks/init.yml
- roles/matrix-bot-honoroit/tasks/main.yml
- roles/matrix-bot-honoroit/tasks/setup_install.yml
- roles/matrix-bot-honoroit/tasks/setup_uninstall.yml
- roles/matrix-bot-honoroit/tasks/validate_config.yml
- roles/matrix-bot-honoroit/templates/env.j2
- roles/matrix-bot-honoroit/templates/systemd/matrix-bot-honoroit.service.j2
- setup.yml
Hi there,
That PR adds Honoroit - a helpdesk bot (https://gitlab.com/etke.cc/honoroit)
> added honoroit

- group_vars/matrix_servers
- roles/matrix-bot-matrix-reminder-bot/defaults/main.yml
- roles/matrix-bot-matrix-reminder-bot/tasks/setup_install.yml
- roles/matrix-bot-matrix-reminder-bot/tasks/validate_config.yml
- roles/matrix-bridge-appservice-irc/defaults/main.yml
- roles/matrix-bridge-appservice-irc/tasks/init.yml
- roles/matrix-bridge-appservice-irc/tasks/setup_install.yml
- roles/matrix-bridge-appservice-irc/tasks/validate_config.yml
- roles/matrix-bridge-appservice-slack/defaults/main.yml
- roles/matrix-bridge-appservice-slack/tasks/init.yml
- roles/matrix-bridge-appservice-slack/tasks/setup_install.yml
- roles/matrix-bridge-appservice-slack/tasks/validate_config.yml
- roles/matrix-bridge-mautrix-signal/defaults/main.yml
- roles/matrix-bridge-mautrix-signal/tasks/setup_install.yml
- roles/matrix-bridge-mautrix-signal/tasks/validate_config.yml
- roles/matrix-bridge-mautrix-telegram/defaults/main.yml
- roles/matrix-bridge-mautrix-telegram/tasks/init.yml
- roles/matrix-bridge-mautrix-telegram/tasks/setup_install.yml
- roles/matrix-bridge-mautrix-telegram/tasks/validate_config.yml
- roles/matrix-synapse-admin/defaults/main.yml
- roles/matrix-synapse-admin/tasks/init.yml
- roles/matrix-synapse-admin/tasks/setup.yml
- roles/matrix-synapse-admin/tasks/validate_config.yml
Hi there,
that PR fixes consistency of self-build vars, to avoid #1513 in future
> self-build consistency

- roles/matrix-bridge-appservice-webhooks/defaults/main.yml
as requested https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1491#issuecomment-1002184609
I have this deployed for a day now, works splendidly.
> pin appservice-webhooks version v1.0.2-01

- docs/configuring-awx-system.md
- roles/matrix-awx/tasks/main.yml
- roles/matrix-awx/tasks/rename_variables.yml
- roles/matrix-awx/tasks/update_variables.yml
okay this update preserves the old matrix_synapse_macaroon_secret_key :+1:
> update new variable for matrix-awx, update documentation

- roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.10.0
> Upgrade Heisenbridge (1.9.0 -> 1.10.0)

- roles/matrix-client-hydrogen/defaults/main.yml
- roles/matrix-client-hydrogen/tasks/setup_install.yml
Fixes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1536
> Upgrade Hydrogen (0.2.19 -> 0.2.23)

- roles/matrix-dynamic-dns/defaults/main.yml
Updates the ddclient image to v3.9.1-ls76. This updates the base image of ddclient.
Closes #1537
> Updated: ddclient to v3.9.1-ls76

- roles/matrix-bridge-appservice-slack/defaults/main.yml
- roles/matrix-bridge-appservice-slack/templates/config.yaml.j2
Updated: appservice slack to v1.10.0. I've rearranged a few things in the config. But as far as I can see, there's no need for further changes.
Closes #1532
> Updated: slack to 1.10.0

- roles/matrix-prometheus-node-exporter/defaults/main.yml
Updates the node-exporter image tag to v1.3.1.
Closes #1539
> Updated: node-exporter to v1.3.1

- roles/matrix-jitsi/defaults/main.yml
Updates the jitsi image tag to stable-6726-2.
Closes #1538
> Updated: version to stable-6726-2

- roles/matrix-nginx-proxy/defaults/main.yml
I've updated certbot to v1.22.0. Everything should behave as usual.
> Updated: Certbot to v1.22.0

- roles/matrix-client-element/defaults/main.yml
Updated element-web to version 1.9.9
https://github.com/vector-im/element-web/releases/tag/v1.9.9
> Updated: element-web to v1.9.9

- roles/matrix-base/tasks/util/ensure_openssl_installed.yml
- roles/matrix-bridge-appservice-irc/tasks/setup_install.yml
- roles/matrix-jitsi/tasks/setup_jitsi_base.yml
- roles/matrix-nginx-proxy/tasks/ssl/setup_ssl_self_signed.yml
Changes not applied to [hookshot PR](https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1505).
> only enable openssl if necessary, closes #1510 

- roles/matrix-bot-honoroit/defaults/main.yml
New version brings in-memory cache that significantly decreases amount of requests to resolve threads relations
> Update honoroit (v0.9.3 -> v0.9.4)

- roles/matrix-bridge-mautrix-facebook/defaults/main.yml
Not tested but shouldn't break something
> Upgrade Mautrix/Facebook (0.3.2 -> 0.3.3)

- roles/matrix-bridge-heisenbridge/defaults/main.yml
Updated: Heisenbridge to 1.10.1
> Updated: Heisenbridge to 1.10.1

- roles/matrix-dynamic-dns/defaults/main.yml
Updated: ddclient to v3.9.1-ls77
> Updated: ddclient to v3.9.1-ls77

- roles/matrix-grafana/defaults/main.yml
> Updated: grafana to 8.3.4

- roles/matrix-nginx-proxy/defaults/main.yml
Updated: nginx to 1.21.6-alpine
> Updated: nginx to 1.21.6-alpine

- roles/matrix-prometheus/defaults/main.yml
Updated: prometheus to v.2.33.1
> Updated: prometheus to v.2.33.1

- .github/workflows/matrix.yml
- .yamllint
> some yamllint ignoring

- roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml
This fixes #1633 (at least for now). Probably should figure out a better solution or mention this in the changelog as a breaking change.
> Changed to: mautrix-whatsapp v0.2.4 tag

- roles/matrix-bridge-mautrix-signal/defaults/main.yml
Updated mautrix-signal to v0.2.3 & signald to 0.17.0
> Updated: mautrix-signal to v0.2.3

- roles/matrix-bridge-mautrix-telegram/defaults/main.yml
Updated mautrix-telegram to v0.11.2
> Updated: mautrix-telegram to v0.11.2

- roles/matrix-nginx-proxy/defaults/main.yml
> Updated: certbot to v1.23.0

- roles/matrix-prometheus/defaults/main.yml
Updated: prometheus to v2.33.3
> Updated: prometheus to v2.33.3

- roles/matrix-synapse-admin/defaults/main.yml
Updated: synapse-admin to 0.8.5
> Updated: synapse-admin to 0.8.5

- roles/matrix-awx/tasks/update_variables.yml
stop re-writing of matrix_homeserver_generic_secret_key variable
> GoMatrixHosting v0.6.9

- roles/matrix-jitsi/defaults/main.yml
It looks like we don't need to change anything on the configurations on our side. But I would be happy if someone could double check this
> Updated: jitsi to stable-6865

- roles/matrix-bot-honoroit/defaults/main.yml
- roles/matrix-bot-honoroit/templates/env.j2
Hi there,
new version of Honoroit with following changes:
* changed cache algorithm to LRU
* added cache size config var
* deeper sentry integration
> updated honoroit 0.9.4 -> 0.9.5

- roles/matrix-bridge-hookshot/templates/registration.yml.j2
this is very poorly documented at hookshot right now, but based on comments in chat:
https://matrix.to/#/!TlZdPIYrhwNvXlBiEk:half-shot.uk/$RbG6itEHVV8J_u5ry1HiFdC76n19M3vmopfQOyRmkKU?via=half-shot.uk&via=matrix.org&via=envs.net
has been merged "upstream" https://github.com/Half-Shot/matrix-hookshot/pull/189
> update hookshot registration.yml

- group_vars/matrix_servers
- roles/matrix-bridge-hookshot/defaults/main.yml
ref: https://github.com/Half-Shot/matrix-hookshot/issues/206
kindly requesting for @Half-Shot to glance over this before merging
> Update hookshot to respect protocol and custom ports

- roles/matrix-bridge-hookshot/defaults/main.yml
all features were actually already silently supported :tada:
upstream changelog: https://github.com/matrix-org/matrix-hookshot/releases/tag/1.2.0
> Upgrade Hookshot (1.1.0 -> 1.2.0)

- docs/configuring-playbook-dimension.md
I hope that helps users to find the admin interface.
> beeing a bit more specific how to access the dimension admin interface

- group_vars/matrix_servers
addresses this complaint https://matrix.to/#/!cNSQwPqhHKkIZdBnvt:devture.com/$M8bwywhf6ywXPahT08Ntq4g9MP6CyAfMMCqSAV9ak3k?via=devture.com&via=matrix.org&via=tu-dresden.de
> add default for matrix_prometheus_scraper_hookshot_enabled

- roles/matrix-ma1sd/tasks/setup_install.yml
Adding when clause to ma1sd image build task to avoid image being built if not needed.
> Add check for ma1sd repo changes on image self build

- docs/configuring-playbook-dimension.md
It is not meant to be opened in this way.
> Don't recommend that the Dimension admin interface be opened in a web browser

- docs/configuring-playbook-bridge-hookshot.md
there was a user that missed the hint to look at some yaml previously in there so I made it slightly more obvious
> add detailed docs about hookshot's URLs

- roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml
Have been running 0.3.0 for 5 days I think, zero issues.
> Update mautrix-whatsapp 0.2.4 -> 0.3.0

- roles/matrix-synapse/defaults/main.yml
Changed the commit hash in matrix_synapse_ext_spam_checker_mjolnir_antispam_git_version to latest. Fixes a python ImportError in Synapse with mjolnir v1.4.1 leading to a Synapse crash-loop.
> Update mjolnir antispam commit hash

- roles/matrix-synapse/defaults/main.yml
This is a minor hotfix, needs to be bumped though or new deploys will break (existing deploys not affected by bug).
> Synapse 1.55.0 -> Synapse 1.55.2

- roles/matrix-bridge-hookshot/defaults/main.yml
Release notes: https://github.com/matrix-org/matrix-hookshot/releases/tag/1.3.0
> Upgrade Hookshot (1.2.0 -> 1.3.0)

- group_vars/matrix_servers
- roles/matrix-dendrite/defaults/main.yml
- roles/matrix-dendrite/tasks/setup_dendrite.yml
- roles/matrix-dendrite/templates/dendrite/dendrite.yaml.j2
- roles/matrix-dendrite/templates/dendrite/systemd/matrix-dendrite.service.j2
An initial pass at dendrite 0.7.0 support
> Dendrite 0.7.0

- docs/configuring-playbook-bridge-mautrix-telegram.md
More info: https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1699
> Improved documentation about Mautrix-telegram-bot permissions

- roles/matrix-jitsi/defaults/main.yml
Tested, works without any configuration changes.
> Update jitsi to version 7001

- roles/matrix-bot-honoroit/defaults/main.yml
This update brings stable threads support
> Update honoroit 0.9.5 -> 0.9.6

- docs/configuring-playbook-backup-borg.md
I set up borg backup using the instructions and BorgBase as a hosted provider, but I found the documentation a bit unclear and incomplete.
This PR adds more context and explanation.
> Improve borg backup instructions

- roles/matrix-bridge-mautrix-telegram/defaults/main.yml
Release notes: https://github.com/mautrix/telegram/releases/tag/v0.11.3
> Upgrade Telegrame bridge to 0.11.3

- roles/matrix-backup-borg/tasks/init.yml
> matrix-backup-borg - cleanup the .service from the systemd list

- roles/matrix-bridge-mautrix-signal/defaults/main.yml
https://github.com/mautrix/signal/releases/tag/v0.3.0
> Updated: mautrix-signal to v0.3.0 & signald to 0.18.0

- docs/faq.md
The old link returned a 404 so I thought I throw in joinmatrix.org :)
> Change list of public servers, old as not functional

- roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.12.0
https://github.com/hifi/heisenbridge/releases/tag/v1.11.0
I forgot to update v1.11.0 :scream:
> Upgrade Heisenbridge (1.10.1 -> 1.12.0)

- roles/matrix-bridge-mautrix-signal/tasks/setup_install.yml
Fixes permissions bug for arm64.
> Update path to signald Dockerfile

- README.md
- docs/configuring-dns.md
- docs/configuring-playbook-bot-buscarron.md
- group_vars/matrix_servers
- roles/matrix-base/defaults/main.yml
- roles/matrix-bot-buscarron/defaults/main.yml
- roles/matrix-bot-buscarron/tasks/init.yml
- roles/matrix-bot-buscarron/tasks/main.yml
- roles/matrix-bot-buscarron/tasks/setup_install.yml
- roles/matrix-bot-buscarron/tasks/setup_uninstall.yml
- roles/matrix-bot-buscarron/tasks/validate_config.yml
- roles/matrix-bot-buscarron/templates/env.j2
- roles/matrix-bot-buscarron/templates/systemd/matrix-bot-buscarron.service.j2
- roles/matrix-nginx-proxy/defaults/main.yml
- roles/matrix-nginx-proxy/tasks/setup_nginx_proxy.yml
- roles/matrix-nginx-proxy/templates/nginx/conf.d/matrix-bot-buscarron.conf.j2
- setup.yml
That bot can receive any HTTP POST/HTML form and send it into a (encrypted) matrix room.
> add matrix-bot-buscarron

- roles/matrix-grafana/defaults/main.yml
https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-5-1/
https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-5-0/
https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-4-7/
https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-4-6/
https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-4-5/
https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-4-4/
https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-4-3/
https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-4-2/
> Upgrade to Grafana 8.5.1

- roles/matrix-bridge-hookshot/defaults/main.yml
- roles/matrix-bridge-hookshot/templates/config.yml.j2
I actually missed adding this config in #1803 so here we go
> Add hookshot feeds config support

- roles/matrix-bridge-mx-puppet-discord/defaults/main.yml
- roles/matrix-bridge-mx-puppet-slack/defaults/main.yml
> Change back to original mx-puppet-slack

- docs/configuring-well-known.md
Link to issue https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1815
> Suggested fix to docs for reverse proxy for well-known file

- roles/matrix-client-cinny/defaults/main.yml
> Update Cinny v2.0.2 -> v2.0.3

- docs/prerequisites.md
Fixes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1792
> Document `git` as a potential prereq

- roles/matrix-bridge-heisenbridge/defaults/main.yml
https://github.com/hifi/heisenbridge/releases/tag/v1.13.0 :bow:
> Upgrade Heisenbridge (1.12.0 -> 1.13.0)

- roles/matrix-bot-mjolnir/defaults/main.yml
Updated: mjolnir to v1.4.2
https://github.com/matrix-org/mjolnir/releases/tag/v1.4.2
> Updated: mjolnir to v1.4.2

- roles/matrix-bridge-mautrix-twitter/defaults/main.yml
Updated: mautrix-twitter to v0.1.4
> Updated: mautrix-twitter to v0.1.4

- roles/matrix-bridge-mx-puppet-skype/defaults/main.yml
- roles/matrix-client-hydrogen/defaults/main.yml
Updated: hydrogen-web to v0.2.29
> Updated: hydrogen-web to v0.2.29

- roles/matrix-dynamic-dns/defaults/main.yml
Updated: ddclient to v3.9.1-ls89
> Updated: ddclient to v3.9.1-ls89

- roles/matrix-etherpad/defaults/main.yml
> Updated: etherpad to 1.8.18

- roles/matrix-grafana/defaults/main.yml
> Updated: grafana to 8.5.3

- roles/matrix-bridge-mautrix-googlechat/defaults/main.yml
Updated: mautrix-googlechat to v0.3.2
> Updated: mautrix-googlechat to v0.3.2

- roles/matrix-bot-matrix-registration-bot/defaults/main.yml
No changes since the v1.1.5 release
> Set version to v1.1.5

- roles/matrix-bot-honoroit/defaults/main.yml
- roles/matrix-bot-honoroit/templates/env.j2
* fix `!ho start` command with `HONOROIT_NOENCRYPTION` option
* add `matrix_bot_honoroit_noencryption` var
> update Honoroit 0.9.8 -> 0.9.9

- roles/matrix-bridge-mautrix-googlechat/defaults/main.yml
Updates the Mautrix Google Chat bridge.
> Updated mautrix-googlechat to v0.3.3

- roles/matrix-bridge-mautrix-whatsapp/defaults/main.yml
- roles/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2
As discussed in #1873 
Feel free to cherry-pick.
> Whatsapp bridge: Logging improvements

- docs/configuring-playbook-bridge-go-skype-bridge.md
> Doc fixups for go-skype-bridge

- roles/matrix-synapse/defaults/main.yml
- roles/matrix-synapse/templates/synapse/homeserver.yaml.j2
Ref: https://matrix-org.github.io/synapse/develop/usage/configuration/config_documentation.html#media_retention
PS: Not tested yet
> add synapse media_retention

- CHANGELOG.md
- docs/configuring-playbook-prometheus-grafana.md
Hello,
Following a bug I had on setting up my instance, I wrote down the issue I faced so that people don't suffer it. 
Cheers,
> Added a note on managing the basic_auth password on external prometheus

- roles/matrix-prometheus/defaults/main.yml
- roles/matrix-prometheus/templates/systemd/matrix-prometheus.service.j2
the predefined list copied from prometheus docker image's `CMD`
> expose prometheus process args

- roles/matrix-client-hydrogen/tasks/main.yml
- roles/matrix-client-hydrogen/tasks/self_check.yml
Thanks to Julian for pointing this out
> Fix Hydrogen self check

- roles/matrix-bot-mjolnir/defaults/main.yml
https://github.com/matrix-org/mjolnir/releases/tag/v1.5.0
> mjolnir: v1.5.0

- docs/configuring-dns.md
project doesn't exist on github anymore
> update buscarron from github -> gitlab

- roles/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2
> fix mautrix-whatsapp config

- inventory/scripts/jitsi-generate-passwords.sh
[SC2086](https://www.shellcheck.net/wiki/SC2086)
> Double quote to prevent globbing and word splitting.

- roles/matrix-bot-honoroit/defaults/main.yml
- roles/matrix-bot-honoroit/templates/env.j2
* add `HONOROIT_IGNOREDROOMS` config var
* add customers' display names on membership and request events
> Update Honoroit 0.9.10 -> 0.9.11

- roles/matrix-bot-honoroit/defaults/main.yml
- roles/matrix-bot-honoroit/templates/env.j2
* add `!ho note` command
* add `HONOROIT_IGNORENOTHREAD` config var
[CI job is in progress](https://gitlab.com/etke.cc/honoroit/-/jobs/2816018913)
> Update Honoroit 0.9.11 -> 0.9.12

- README.md
Add Mautrix/Discord to the Supported services of the Readme
> Add Mautrix/Discord to the Readme

- roles/matrix-bridge-appservice-discord/defaults/main.yml
Ref: https://github.com/matrix-org/matrix-appservice-discord/pull/826
```
docker pull ghcr.io/matrix-org/matrix-appservice-discord:v3.0.0
v3.0.0: Pulling from matrix-org/matrix-appservice-discord
751ef25978b2: Pull complete 
16af4ec8b188: Pull complete 
8c8f56f7dc53: Pull complete 
afa016f2f989: Pull complete 
683e2bbbda4e: Pull complete 
fb056adbb1d6: Pull complete 
716f59a72dc7: Pull complete 
d52c94fc1da3: Pull complete 
b7b9cd5ddbeb: Pull complete 
Digest: sha256:1009697517bfe07a0d2192cf3b982bc2dbe40829cedc82c100aef61f8a43e3de
Status: Downloaded newer image for ghcr.io/matrix-org/matrix-appservice-discord:v3.0.0
ghcr.io/matrix-org/matrix-appservice-discord:v3.0.0
```
> Update Appservice Discord 1.0.0 -> 3.0.0

- roles/matrix-nginx-proxy/defaults/main.yml
Hello,
a new version of nginx proxy was published hours ago.
> Update nginx-proxy: 1.23.0 -> 1.23.1

- group_vars/matrix_servers
- roles/matrix-dendrite/defaults/main.yml
- roles/matrix-dendrite/templates/dendrite/dendrite.yaml.j2
Remove appservice database setup/config as the latest update no longer requires it.
> Update dendrite 0.9.5 -> 0.9.6

- README.md
- docs/configuring-playbook-cactus-comments.md
- docs/configuring-playbook.md
- docs/container-images.md
- group_vars/matrix_servers
- roles/matrix-bridge-hookshot/defaults/main.yml
- roles/matrix-cactus-comments/defaults/main.yml
- roles/matrix-cactus-comments/tasks/init.yml
- roles/matrix-cactus-comments/tasks/main.yml
- roles/matrix-cactus-comments/tasks/setup_install.yml
- roles/matrix-cactus-comments/tasks/setup_uninstall.yml
- roles/matrix-cactus-comments/tasks/validate_config.yml
- roles/matrix-cactus-comments/templates/cactus_appservice.yaml.j2
- roles/matrix-cactus-comments/templates/env.j2
- roles/matrix-cactus-comments/templates/systemd/matrix-cactus-comments.service.j2
- setup.yml
As mentioned in #2024 I worked on adding the cactus comments server.
This role is tested but not extensively.
> Cactus comments

- roles/matrix-bot-postmoogle/defaults/main.yml
**Warning**: [CI is in progress](https://gitlab.com/etke.cc/postmoogle/-/jobs/3026086969)
> Update Postmoogle 0.9.1 -> 0.9.2

- CHANGELOG.md
> fix: typo in changelog.md

- docs/configuring-playbook-ntfy.md
I updated the settings for the Element messenger to work with ntfy push.
> Updated the Element settings.

- roles/matrix-bot-honoroit/defaults/main.yml
**Warning**: [CI job is in progress](https://gitlab.com/etke.cc/honoroit/-/jobs/3059982196)
> Update Honoroit 0.9.14 -> 0.9.15

- roles/matrix-bot-postmoogle/defaults/main.yml
**Warning**: [CI job is in progress](https://gitlab.com/etke.cc/postmoogle/-/jobs/3060051912)
> Update Postmoogle 0.9.2 -> 0.9.3

- roles/matrix-dendrite/defaults/main.yml
- 0.9.9 (https://github.com/matrix-org/dendrite/releases/tag/v0.9.9)
> dendrite: update image tag version

- roles/matrix-bot-postmoogle/defaults/main.yml
* send emails in UTF-8 👋
* fix options descriptions
* add SMTP auth
* allow sending emails from your apps and scripts using postmoogle as email provider
**Warning**: [CI job is in progress](https://gitlab.com/etke.cc/postmoogle/-/jobs/3073586472)
> Update Postmoogle 0.9.3 -> 0.9.4

- roles/matrix-bot-mjolnir/templates/production.yaml.j2
This PR is not fully ready as far as i am concerned. Someone should take a second pass and give all options not commented out a way to be modified. I dont know if overides is that way or not. If its deemed that no changes are needed because you can change all the options then this PR should be in a merge ready state. 
I edited the data path since we use the data/ path instead of data/storage/ in our current config and this is supposed to be able to merge clean.
> Update Mjolnir Config from its #962 state to todays template.

- roles/matrix-bot-postmoogle/defaults/main.yml
* show recipient's email (header `TO`)
* add `norecipient` option
* add anti-spam options (`spamcheck:` and `spamlist:`)
* fix bugs
**Warning**: [CI job is in progress](https://gitlab.com/etke.cc/postmoogle/-/jobs/3156823895)
> Update postmoogle 0.9.5 -> 0.9.6

- roles/matrix-bot-postmoogle/defaults/main.yml
* fix room account data retrieving
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/postmoogle/-/pipelines/664750086)
> Update postmoogle 0.9.6 -> 0.9.7

- docs/configuring-well-known.md
the word "both" would refer to only 2 urls in this context
> grammar correction

- docs/configuring-playbook-ssl-certificates.md
in my environment i see the matrix. conf in that file: /matrix/nginx-proxy/conf.d/matrix-domain.conf
> update link to example

- docs/configuring-playbook-backup-borg.md
was a litte confusing for me, so i added the link to the syntax-descr.
> update remote-repo-infos with link to doc

- docs/configuring-playbook-backup-borg.md
Signed-off-by: Julian-Samuel Gebühr <julian-samuel@gebuehr.net>
> Add information on how to manually run the backup

- group_vars/matrix_servers
- roles/matrix-bot-honoroit/defaults/main.yml
* refactor events cache
* fix failure on empty command
* update deps
* drop arm32 support (docker images)
**Warning**: [CI job is in progress](https://gitlab.com/etke.cc/honoroit/-/jobs/3225082463)
> update honoroit 0.9.15 -> 0.9.16

- roles/matrix-client-element/defaults/main.yml
> update element v1.11.11 -> v1.11.12

- roles/matrix-bridge-mautrix-signal/defaults/main.yml
ref: https://gitlab.com/signald/signald/-/issues/343
> Update signald 0.22.2 -> 0.23.0

- roles/custom/matrix-dendrite/defaults/main.yml
- https://github.com/matrix-org/dendrite/releases/tag/v0.10.7
> dendrite: update image tag to latest release (0.10.7)

- docs/configuring-captcha.md
- group_vars/matrix_servers
- roles/custom/matrix-dendrite/defaults/main.yml
- roles/custom/matrix-dendrite/tasks/validate_config.yml
- roles/custom/matrix-dendrite/templates/dendrite/dendrite.yaml.j2
Dendrite has support for Google's reCAPTCHA.
> Add dendrite captcha config to doc and hCaptcha

- docs/configuring-playbook-synapse.md
Use up-to-date example from synapse docs
Add link to keycloak website
Add link to synapse docs on OIDC
> Update docs on how to use synapse & keycloak OIDC

- roles/custom/matrix-dendrite/defaults/main.yml
https://github.com/matrix-org/dendrite/releases/tag/v0.10.8
> update dendrite to v0.10.8

- roles/custom/matrix-synapse/defaults/main.yml
- roles/custom/matrix-synapse/tasks/ext/s3-storage-provider/setup_install.yml
- roles/custom/matrix-synapse/tasks/setup_install.yml
- roles/custom/matrix-synapse/templates/synapse/ext/s3-storage-provider/bin/migrate.j2
- roles/custom/matrix-synapse/templates/synapse/ext/s3-storage-provider/bin/shell.j2
This path is accessed by the s3 storage provider stuff and needs to be ensured.
Broken by 7c5c3aedc
> fix s3 storage provider not ensuring data dir

- group_vars/matrix_servers
sorry, apparently didn't completely reset my test setup and missed these two bugs.
> fix: nginxlog prometheus config port

- roles/custom/matrix-bot-mjolnir/defaults/main.yml
Please note that This Mjolnir version bump technnically is missing some extra stuff that mjolnir claims we should do but it didnt work when i tried it and well my mjolnir deployment has been running this since release day almost and its fine. No errors in log that are unexpected. (Mjolnir throws errors in the log for anyone who wonders for various things that are fine. Like if a protection is off that is an error. Its due to how matrix-bot-lib works.)
Issue #2296 is relevant for this PR because the problems disussed in that issue are the ones im talking about in this PR.
> Update Mjolnir from 1.5.0 to 1.6.1

- roles/custom/matrix-synapse/defaults/main.yml
I made sure the docker image is there this time.
Signed-off-by: Joe Kappus <joe@wt.gd>
> Upgrade Synapse (1.73.0 -> 1.74.0)

- group_vars/matrix_servers
- roles/custom/matrix-bridge-mautrix-discord/defaults/main.yml
- roles/custom/matrix-conduit/defaults/main.yml
Also reverts the conduit workaround from #2161
> Update conduit to 0.5.0

- roles/custom/matrix-bridge-beeper-linkedin/defaults/main.yml
- roles/custom/matrix-bridge-beeper-linkedin/templates/config.yaml.j2
> update beeper-linkedin 0.5.3 -> 0.5.4

- roles/custom/matrix-bot-maubot/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-telegram/defaults/main.yml
- roles/custom/matrix-prometheus-postgres-exporter/defaults/main.yml
- roles/custom/matrix-synapse/defaults/main.yml
all docker image urls in the mdad use prefixes, this PR adds missing prefixes
> unify docker images urls

- roles/custom/matrix-bot-buscarron/defaults/main.yml
* Shared rate limit across forms
* Do not ban internal IPs
* Updated deps
* Enabled vendoring
> Update buscarron v1.3.0 -> v1.3.1

- docs/installing.md
> Fixed broken links to justfile

- roles/custom/matrix-bot-chatgpt/defaults/main.yml
- roles/custom/matrix-bot-chatgpt/templates/env.j2
Adds support for ChatGPT pro subscriptions.
> Upgrade matrix-chatgpt-bot to latest

- roles/custom/matrix-bot-chatgpt/defaults/main.yml
- roles/custom/matrix-bot-chatgpt/templates/env.j2
Add support for configurable context level.
> Bump Matrix Bot ChatGPT from 1.3.2 --> 1.4.1

- roles/custom/matrix-bot-postmoogle/defaults/main.yml
* fix uploads from incoming emails into matrix threads
* fix emails dequeue (account data cleanup)
* rewrite recipients handling (Cc, To, etc.)
**WARNING**: [CI pipeline is in progress](https://gitlab.com/etke.cc/postmoogle/-/pipelines/772965293)
> Update postmoogle 0.9.11 -> 0.9.12

- roles/custom/matrix-dendrite/defaults/main.yml
https://github.com/matrix-org/dendrite/releases/tag/v0.11.1
> updated dendrite

- roles/custom/matrix-base/templates/static-files/well-known/matrix-client.j2
meep @spantaleev   that last MR kinda broke setup :p
> fix: missing endif

- roles/custom/matrix-client-element/defaults/main.yml
Signed-off-by: Julian-Samuel Gebühr <julian-samuel@gebuehr.net>
> Bump element version

- docs/configuring-playbook-ssl-certificates.md
Feel free to comment/test/edit...
> Added doc for self-signed certificates

- roles/custom/matrix-bot-draupnir/templates/production.yaml.j2
Config was accidently changed when importing upstream changes causing a regression.
> Resolve Draupnir regression caused in #2508

- requirements.yml
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/borgmatic/-/pipelines/794965213)
> update borgmatic 1.7.7 -> 1.7.8

- roles/custom/matrix-bot-honoroit/defaults/main.yml
* healthchecks.io integration
* mutex on forwarding messages into thread
* fix in prefixes handling
* send error messages as thread reply when possible
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/honoroit/-/pipelines/796575543)
> update honoroit 0.9.16 -> 0.9.17

- docs/configuring-playbook-cactus-comments.md
> fix incomplete config line

- CHANGELOG.md
- README.md
- docs/configuring-playbook-synapse-auto-compressor.md
- docs/configuring-playbook.md
- docs/maintenance-synapse.md
- group_vars/matrix_servers
- playbooks/matrix.yml
- roles/custom/matrix-synapse-auto-compressor/defaults/main.yml
- roles/custom/matrix-synapse-auto-compressor/tasks/install.yml
- roles/custom/matrix-synapse-auto-compressor/tasks/main.yml
- roles/custom/matrix-synapse-auto-compressor/tasks/uninstall.yml
- roles/custom/matrix-synapse-auto-compressor/tasks/validate_config.yml
- roles/custom/matrix-synapse-auto-compressor/templates/env.j2
- roles/custom/matrix-synapse-auto-compressor/templates/matrix-synapse-auto-compressor.service.j2
- roles/custom/matrix-synapse-auto-compressor/templates/matrix-synapse-auto-compressor.timer.j2
> add synapse_auto_compressor

- roles/custom/matrix-dendrite/defaults/main.yml
https://github.com/matrix-org/dendrite/releases/tag/v0.12.0
> Update dendrite to v0.12.0

- roles/custom/matrix-synapse/defaults/main.yml
Check for Arm images = Succeeded
> Upgrade Synapse from 1.78.0 to 1.79.0

- requirements.yml
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/borgmatic/-/pipelines/809185799)
> Update borgmatic 1.7.8 -> 1.7.9

- roles/custom/matrix-bridge-hookshot/defaults/main.yml
Warning! Potentially breaking change: https://github.com/matrix-org/matrix-hookshot/releases/tag/3.0.0
> Update hookshot 2.7.0 -> 3.0.0

- roles/custom/matrix-sliding-sync/defaults/main.yml
> fix(sliding-sync): Use external syncv3 server URL

- docs/configuring-playbook-sliding-sync-proxy.md
This fixes #2586 by pointing hapless use cases like myself in the right direction!
> Update sliding sync doc for external DB users

- CHANGELOG.md
- docs/configuring-playbook-ntfy.md
> Describe disabled ntfy web app in documentation & changelog

- group_vars/matrix_servers
- roles/custom/matrix-bot-honoroit/defaults/main.yml
- roles/custom/matrix-bot-honoroit/tasks/setup_install.yml
- roles/custom/matrix-bot-honoroit/templates/labels.j2
- roles/custom/matrix-bot-honoroit/templates/systemd/matrix-bot-honoroit.service.j2
preparations for prometheus metrics
> honoroit - add proper networking configuration and traefik labels

- requirements.yml
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/borgmatic/-/pipelines/816588337)
> Update borg 1.2.3 -> 1.2.4

- roles/custom/matrix-bot-maubot/defaults/main.yml
> Updating maubot to the latest version 0.4.0 -> 0.4.1

- .envrc
- .gitignore
- flake.nix
I added a small flake for use with the Nix package manager. Also a .direnv file, which allows anyone that has nix installed to immediately run the tools in this repo without having to install any tools manually.
> Added a nix flake

- requirements.yml
> update grafana (9.4.7 -> 9.5.1); update ntfy (2.3.1 -> 2.4.0)

- roles/custom/matrix-bridge-appservice-irc/defaults/main.yml
https://github.com/matrix-org/matrix-appservice-irc/releases/tag/0.38.0
> Update IRC appservice to 0.38.0

- requirements.yml
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/borgmatic/-/pipelines/869359609)
> update borgmatic 1.7.12 -> 1.7.13

- docs/configuring-playbook-bot-chatgpt.md
added an extra step to creating the chatgpt bot so it can read encrypted messages
> Document how to use chatgpt-bot in encrypted rooms

- requirements.yml
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/borgmatic/-/pipelines/891531179)
> Update borgmatic 1.7.13 -> 1.7.14

- roles/custom/matrix-synapse/defaults/main.yml
> Update synapse 1.85.2 -> 1.86.0

- docs/howto-server-delegation.md
- docs/howto-srv-server-delegation.md
This PR resolves #2555 and lists all necessary steps to federate using SRV delegation under traefik.
> Add documentation to detail the steps needed to federate using SRV delegation

- roles/custom/matrix-synapse-reverse-proxy-companion/defaults/main.yml
> Update synapse reverse proxy companion

- requirements.yml
**WARNING**: [CI pipleine is in progress](https://gitlab.com/etke.cc/borgmatic/-/pipelines/911009212)
> Update borgmatic 1.7.14 -> 1.7.15

- roles/custom/matrix-bridge-hookshot/defaults/main.yml
**Warning**: potentially problematic release - https://github.com/matrix-org/matrix-hookshot/releases/tag/4.4.0
> Update hookshot 4.3.0 -> 4.4.0

- examples/hosts
Maybe this is something that everyone is supposed to know, but I didn't.
> Add note for -K flag to Ansible

- roles/custom/matrix-bridge-beeper-linkedin/defaults/main.yml
> fix(linkedin): mismatched appservice id

- group_vars/matrix_servers
The salt needs to be 16 characters or less.
> Shortening the salt

- docs/configuring-playbook-bot-chatgpt.md
Added the system promt variable and added a bit information for beginners
> Add system promt variable to docs

- roles/custom/matrix-bot-honoroit/defaults/main.yml
**Warning**: [CI job is in progress](https://gitlab.com/etke.cc/honoroit/-/jobs/4793063656)
> Update honoroit 0.9.17 -> 0.9.18

- requirements.yml
> Update borg role v1.2.4-1.7.15-1 -> v1.2.4-1.7.15-2

- docs/configuring-playbook-jitsi.md
- group_vars/matrix_servers
- roles/custom/matrix-nginx-proxy/defaults/main.yml
- roles/custom/matrix-nginx-proxy/templates/nginx/conf.d/matrix-jitsi.conf.j2
Two commits - one of them simplifies the configuration for nginx.
> Proxy additional JVBs through traefik (fixes #2721)

- roles/custom/matrix-synapse/defaults/main.yml
fixes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/2853
> make synapse even more quiet

- requirements.yml
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/borgmatic/-/pipelines/988351783)
> Update borg v1.2.4 -> v1.2.5

- README.md
Specifically edited client and bridge descriptions.
> Improved README descriptions

- roles/custom/matrix-client-element/defaults/main.yml
> Update element 1.11.42 -> 1.11.43

- roles/custom/matrix-bot-postmoogle/defaults/main.yml
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/postmoogle/-/pipelines/1020113789)
> Update postmoogle 0.9.15 -> 0.9.16

- requirements.yml
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/borgmatic/-/pipelines/1023207214)
> Update borg 1.2.5 -> 1.2.6

- docs/maintenance-postgres.md
no postgres 16 support with borg, 15 works.
> Warning Borg users before upgrading to Postgres 16

- requirements.yml
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/borgmatic/-/pipelines/1038099105)
> Update borgmatic 1.8.2 -> 1.8.3

- roles/custom/matrix-base/templates/static-files/well-known/matrix-support.j2
ref: https://github.com/matrix-org/matrix-spec-proposals/blob/7f68d57be2ccb01c9ac99fb10b9c9a3e895e27a1/proposals/1929-admin-contact.md#proposal
> Update MSC1929 integration

- requirements.yml
**Warning**: [CI pipeline is in progress](https://gitlab.com/etke.cc/borgmatic/-/pipelines/1051522115)
> Update borgmatic 1.8.3 -> 1.8.4

- roles/custom/matrix-user-verification-service/templates/systemd/matrix-user-verification-service.service.j2
Fixes #2375, #2975, and #2847
Credit should go to @crapo9000 as solved here https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2375#issuecomment-1655758296 . I've just created the PR according to their solution
> Fix matrix-user-verification-service service file

- roles/custom/matrix-synapse/defaults/main.yml
security fix: https://github.com/matrix-org/synapse/releases/tag/v1.95.1
> Update synapse 1.95.0 -> 1.95.1

- requirements.yml
**Warning**: [CI pipleline is in progress](https://gitlab.com/etke.cc/borgmatic/-/pipelines/1078387782)
> Update borgmatic 1.8.4 -> 1.8.5

- roles/custom/matrix-bridge-mautrix-discord/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-facebook/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-gmessages/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-instagram/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-slack/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-telegram/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-whatsapp/defaults/main.yml
checked all mautrix bridges, not all of them have relay mode
> mautrix: allow relay access by default, closes #3014

- docs/configuring-playbook-matrix-media-repo.md
- roles/custom/matrix-media-repo/defaults/main.yml
Most of the changes are self-explanatory. The one thing I'm not 100% confident on are the changes to `roles/custom/matrix-media-repo/defaults/main.yml`, as I'm far from an expert on jinja2 syntax.
> Update MMR docs for dendrite and importing existing media

- roles/custom/matrix-synapse/defaults/main.yml
- roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
Removed the hard-coded connection pool min and max arguments to using playbook variables.
> Added Synapse connection pool config variables

- roles/custom/matrix-bridge-mautrix-signal/defaults/main.yml
Here is a fix proposal for issue: https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3074
> [#3074] Docker tag follows the version properly

- roles/custom/matrix-media-repo/templates/grafana/media-repo.json
Updated to current version in https://github.com/turt2live/matrix-media-repo/blob/master/docs/grafana.json
> Updated Grafana dashboard for MMR

- examples/reverse-proxies/apache/matrix-domain.conf
otherwise it won't work. just tested this for you :grin:
> fix ProxyPass directive by adding mandatory trailing slash

- group_vars/matrix_servers
- roles/custom/matrix-bridge-mautrix-telegram/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-telegram/templates/config.yaml.j2
After reviewing the configuration of the Mautrix-Telegram bridge, I noticed that a lot of improvements were missing... Here there are!
> Mautrix-Telegram bridge config update

- docs/configuring-playbook-bot-matrix-registration-bot.md
changed "loook like" to "Tokens look like"
> Fix typo in configuring-playbook-bot-matrix-registration-bot.md

- docs/configuring-playbook.md
`mkdir` with multiple subdirs needs `-p`
> Small doc fix

- roles/custom/matrix-bridge-mautrix-whatsapp/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-whatsapp/templates/config.yaml.j2
currently extev_polls parameter is hardcoded to false.
This change allows to overwrite it via custom variable. Would be great, if that change could be merged into the master/main branch.
Thank you
> allow to configure whatsapp polls via extev_polls parameter.

- roles/custom/matrix-client-schildichat/defaults/main.yml
See: https://github.com/SchildiChat/schildichat-desktop/releases/tag/v1.11.36-sc.3
> Update SchildiChat to `v1.11.36-sc.3`

- docs/configuring-playbook-bridge-appservice-slack.md
- roles/custom/matrix-bridge-appservice-slack/defaults/main.yml
- roles/custom/matrix-bridge-appservice-slack/templates/config.yaml.j2
> Add puppeting option to matrix-bridge-appservice-slack

- group_vars/matrix_servers
- roles/custom/matrix-media-repo/defaults/main.yml
- roles/custom/matrix-media-repo/templates/grafana/media-repo.json
- roles/custom/matrix-media-repo/templates/media-repo/labels.j2
* Additionally fixed the somewhat broken Grafana dashboard that had an invalid data source and panel queries.
* Removed duplicate media-repo dashboard file from the grafana provisioning directory.
> Added MMR metrics proxying support

- docs/configuring-playbook-matrix-media-repo.md
- group_vars/matrix_servers
- roles/custom/matrix-media-repo/defaults/main.yml
- roles/custom/matrix-media-repo/templates/media-repo/media-repo.yaml.j2
Updated config template with new fields added in recent MMR releases. MMR key signing setup is manual for now, but could be automated in the future.
> Added new fields to MMR config template

- docs/maintenance-upgrading-services.md
improves readability of rendered file
> docs/maintenance-upgrading: indent "either" commands

- group_vars/matrix_servers
- roles/custom/matrix-synapse-auto-compressor/defaults/main.yml
- roles/custom/matrix-synapse-auto-compressor/tasks/install.yml
- roles/custom/matrix-synapse-auto-compressor/templates/env.j2
- roles/custom/matrix-synapse-auto-compressor/templates/matrix-synapse-auto-compressor-fix.sh.j2
- roles/custom/matrix-synapse-auto-compressor/templates/matrix-synapse-auto-compressor.service.j2
> add synapse-auto-compressor workaround, fixes #3397

- docs/installing.md
> update agru url in installing.md

- docs/configuring-playbook-synapse-admin.md
- roles/custom/matrix-synapse-admin/defaults/main.yml
[That's why](https://github.com/etkecc/synapse-admin#fork-differences)
> Switch Synapse-Admin to etke.cc fork

- roles/custom/matrix-synapse-admin/defaults/main.yml
**Warning**: wait for [CI job](https://github.com/etkecc/synapse-admin/actions/runs/10860804986/job/30141878358) to finish before merging
> Synapse-Admin: Add UI option to block deleted rooms from being rejoined

- roles/custom/matrix_playbook_migration/tasks/validate_config.yml
`devture_postgres_*` -> `postgres_*`
> Fix validate_config.yml

- docs/configuring-playbook-bot-draupnir.md
- docs/configuring-playbook-bot-mjolnir.md
Working on my personal project based on the repository, I read through and check every documentation file, and found several stuff to be fixed and improved. This is one of the PRs which will be created hereafter.
> Fix typos on configuring-playbook-bot-draupnir.md and configuring-playbook-bot-mjolnir.md

- docs/container-images.md
Closes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3588
> Replace reference to nginx container image with one to Traefik container image on docs/container-images.md

- docs/prerequisites.md
This PR intends to fix indentation of the first item for server architecture on prerequisites.md.
> Fixes indentation on prerequisites.md

- docs/configuring-playbook-bot-draupnir.md
- docs/configuring-playbook-bot-mjolnir.md
- docs/container-images.md
Fixes capitalization: mjolnir → Mjolnir
> Fixes capitalization: mjolnir → Mjolnir

- docs/configuring-playbook-client-schildichat.md
- roles/custom/matrix-base/defaults/main.yml
- roles/custom/matrix-client-schildichat/defaults/main.yml
- roles/custom/matrix-client-schildichat/tasks/prepare_themes.yml
- roles/custom/matrix-client-schildichat/tasks/self_check.yml
- roles/custom/matrix-client-schildichat/tasks/setup_install.yml
- roles/custom/matrix-client-schildichat/tasks/setup_uninstall.yml
- roles/custom/matrix-client-schildichat/tasks/validate_config.yml
- roles/custom/matrix-client-schildichat/templates/systemd/matrix-client-schildichat.service.j2
This PR intends to fix capitalization: schildichat → SchildiChat
> Fix capitalization: schildichat → SchildiChat

- docs/configuring-dns.md
- docs/configuring-playbook-bot-baibot.md
- docs/configuring-playbook-bot-buscarron.md
- docs/configuring-playbook-bridge-appservice-discord.md
- docs/configuring-playbook-bridge-appservice-kakaotalk.md
- docs/configuring-playbook-bridge-appservice-slack.md
- docs/configuring-playbook-bridge-appservice-webhooks.md
- docs/configuring-playbook-conduit.md
- docs/configuring-playbook-dendrite.md
- docs/configuring-playbook-external-postgres.md
- docs/configuring-playbook-jitsi.md
- docs/configuring-playbook-matrix-ldap-registration-proxy.md
- docs/configuring-playbook-prometheus-nginxlog.md
- docs/configuring-playbook-s3.md
- docs/configuring-playbook-sliding-sync-proxy.md
- docs/configuring-playbook-synapse-auto-accept-invite.md
- docs/howto-server-delegation.md
- docs/howto-srv-server-delegation.md
- docs/installing.md
- examples/reverse-proxies/caddy2-in-container/README.md
- roles/custom/matrix-bridge-appservice-irc/tasks/migrate_nedb_to_postgres.yml
- roles/custom/matrix-bridge-appservice-slack/tasks/migrate_nedb_to_postgres.yml
- roles/custom/matrix-bridge-mautrix-facebook/tasks/validate_config.yml
- roles/custom/matrix-coturn/tasks/setup_install.yml
- roles/custom/matrix-prometheus-nginxlog-exporter/defaults/main.yml
- roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
This PR intends to make expression related to "Note" consistent (NOTE → Note, Note → `**Note**`, etc.)
> Make expression related to "Note" consistent

- CHANGELOG.md
- docs/configuring-playbook-alertmanager-receiver.md
- docs/configuring-playbook-bridge-appservice-slack.md
- docs/configuring-playbook-bridge-matrix-bridge-sms.md
- docs/configuring-playbook-email2matrix.md
- docs/configuring-playbook-jitsi.md
- docs/configuring-playbook-matrix-corporal.md
- docs/configuring-playbook-matrix-media-repo.md
- docs/configuring-playbook-prometheus-grafana.md
- docs/configuring-playbook-synapse-s3-storage-provider.md
- docs/configuring-playbook-user-verification-service.md
- docs/configuring-well-known.md
- docs/maintenance-migrating.md
- roles/custom/matrix-appservice-draupnir-for-all/templates/production-appservice.yaml.j2
- roles/custom/matrix-base/defaults/main.yml
- roles/custom/matrix-bot-honoroit/defaults/main.yml
- roles/custom/matrix-bridge-appservice-irc/defaults/main.yml
- roles/custom/matrix-bridge-mautrix-meta-instagram/templates/config.yaml.j2
- roles/custom/matrix-bridge-mautrix-meta-messenger/templates/config.yaml.j2
- roles/custom/matrix-cactus-comments/templates/cactus_appservice.yaml.j2
- roles/custom/matrix-conduit/templates/conduit.toml.j2
- roles/custom/matrix-dimension/defaults/main.yml
- roles/custom/matrix-synapse/defaults/main.yml
- roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
- roles/custom/matrix-synapse/vars/main.yml
This PR intends to fix capitalization: id → ID
> Fix capitalization: id → ID

- docs/configuring-playbook-bot-baibot.md
- docs/configuring-playbook-bot-honoroit.md
- docs/configuring-playbook-cactus-comments.md
- docs/configuring-playbook-etherpad.md
- docs/configuring-playbook-jitsi.md
- docs/configuring-playbook-ntfy.md
- docs/configuring-playbook-own-webserver.md
- docs/configuring-playbook-synapse-auto-accept-invite.md
It seems to be that `Uncomment and adjust this part if you'd like to…` is a common expression to suggest uncommenting a line below it and adjust the configuration. Having the same pattern will surely help us in some way :-)
> Use a common expression for suggesting to uncomment and adjust configuration

- docs/configuring-playbook-external-postgres.md
Update docs/configuring-playbook-external-postgres.md: remove a duplicate sentence
> Update docs/configuring-playbook-external-postgres.md: remove a duplicate sentence

- docs/configuring-playbook-bot-postmoogle.md
This follows the sentence here: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/57e2fb291dfe1b4cb0b363e5c5f1d864add98f85/docs/configuring-playbook-bot-baibot.md?plain=1#L94
> Update docs/configuring-playbook-bot-postmoogle.md: add "bots" to the comment

- docs/configuring-playbook-client-element.md
- docs/configuring-playbook-external-postgres.md
- docs/configuring-playbook-own-webserver.md
- docs/configuring-playbook-s3.md
- docs/configuring-playbook-synapse.md
This updates documentation to use the common expression to suggest to skip document: "If that's okay, you can skip this document."
> Use a common expression to suggest to skip the document

- docs/configuring-playbook-email2matrix.md
- roles/custom/matrix-email2matrix/defaults/main.yml
- Sync list of mailbox to Matrix mappings
- Add explanation for each variable
> Update Email2Matrix documentation and its default configuration file

- docs/configuring-playbook-cactus-comments.md
- docs/configuring-playbook-client-cinny.md
- docs/configuring-playbook-client-hydrogen.md
- docs/configuring-playbook-client-schildichat.md
- docs/configuring-playbook-external-postgres.md
- Remove whitespace characters from the comment block
- Update docs/configuring-playbook-external-postgres.md: minor changes
- Update docs/configuring-playbook-cactus-comments.md: add line breaks
> Add minor updates to documentation

- CHANGELOG.md
- docs/configuring-playbook-s3-goofys.md
- docs/configuring-well-known.md
- docs/obtaining-access-tokens.md
This should reduce the possibility of confusion :-)
> Fix list numbering

- docs/configuring-playbook-conduit.md
- docs/configuring-playbook-dendrite.md
- Have docs/configuring-playbook-dendrite.md follow docs/configuring-playbook-synapse.md
- Add `Adjusting the playbook configuration` after the `**Notes:**`
> Update docs/configuring-playbook-conduit.md and docs/configuring-playbook-dendrite.md

- docs/configuring-dns.md
Follow-up to https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3646
> Update docs/configuring-dns: fix an incorrect anchor link

- roles/custom/matrix-synapse-admin/defaults/main.yml
- roles/custom/matrix-synapse-admin/templates/config.json.j2
> synapse-admin v0.10.3-etke22

- docs/configuring-playbook-bridge-mautrix-discord.md
- docs/configuring-playbook-bridge-mautrix-facebook.md
- Fix listing: docs/configuring-playbook-bridge-mautrix-discord.md
- Add parentheses: docs/configuring-playbook-bridge-mautrix-facebook.md
> Update docs/configuring-playbook-bridge-mautrix-discord.md and docs/configuring-playbook-bridge-mautrix-facebook.md

- CHANGELOG.md
- docs/configuring-playbook-backup-borg.md
- docs/configuring-playbook-bridge-appservice-discord.md
- docs/configuring-playbook-bridge-appservice-webhooks.md
- docs/configuring-playbook-matrix-authentication-service.md
- docs/configuring-playbook-s3-goofys.md
- docs/configuring-playbook-synapse-s3-storage-provider.md
by adjusting tabs with whitespace characters
> Fix indentations of list items

- docs/configuring-playbook.md
The section should help us somewhat to know which service to be installed/avoided (for new installation) or to be removed/replaced (for managing a running homeserver).
> Create a section for deprecated, unmaintained, or removed services on docs/configuring-playbook.md

- roles/custom/matrix-synapse-admin/defaults/main.yml
* [Logo and icon!](https://github.com/etkecc/synapse-admin/commit/132ea6f97f4fef8b507c89578646c93f89840be1)
* [Community room: #synapse-admin:etke.cc](https://matrix.to/#/#synapse-admin:etke.cc)
* [Sanitize CSV on import](https://github.com/etkecc/synapse-admin/pull/101)
* [Generate extended manifest.json on build](https://github.com/etkecc/synapse-admin/commit/fa79fecc9d8f5109f02b90800fd5f91ba7b81e04)
**ProTip!** Do you know that [you can drag/move the customization window](https://github.com/etkecc/synapse-admin/issues/110#issuecomment-2447669053)?
> synapse-admin: v0.10.3-etke26

- README.md
- docs/container-images.md
- matrix-alertmanager-receiver
- Matrix Authentication Service
- mautrix-meta
- mautrix-wsproxy
- matrix-wechat
> Add several components to README.md and docs/container-images.md

- README.md
- docs/configuring-playbook-dynamic-dns.md
- docs/configuring-playbook.md
- docs/container-images.md
- Update README.md
- Update docs/configuring-playbook-dynamic-dns.md: remove reference to deceased Google Domains etc.
- Update docs/configuring-playbook.md: move documentation to server connectivity section
- Update docs/container-images.md: add linuxserver/ddclient
ddclient makes it possible to set up dynamic DNS: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/5ebdc0c48d268351c554560439e55de90caceb48/CHANGELOG.md?plain=1#L2419
> Add ddclient to documentation

- docs/configuring-playbook-s3.md
- docs/configuring-playbook.md
- docs/importing-synapse-media-store.md
Please see https://www.storj.io/pricing (https://storj.dev/dcs/pricing) and https://www.backblaze.com/cloud-storage/pricing for details about pricing.
> Update docs/configuring-playbook-s3.md about object storage providers

- CHANGELOG.md
- docs/configuring-playbook-bot-chatgpt.md
- docs/configuring-playbook-bot-go-neb.md
- docs/configuring-playbook-bridge-appservice-webhooks.md
- docs/configuring-playbook-bridge-mautrix-facebook.md
- docs/configuring-playbook-bridge-mautrix-hangouts.md
- docs/configuring-playbook-bridge-mautrix-instagram.md
- docs/configuring-playbook-bridge-mx-puppet-skype.md
- docs/configuring-playbook-dimension.md
> Update documentation titles of deprecated or unmaintained services

- docs/configuring-playbook-bridge-mautrix-meta-instagram.md
- docs/configuring-playbook-bridge-mautrix-meta-messenger.md
For https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3396
> Update docs/configuring-playbook-bridge-mautrix-meta-messenger.md: add a note about user ID of the new bridge's bot

- .github/ISSUE_TEMPLATE/config.yml
- .github/renovate.json
- Add .github/ISSUE_TEMPLATE/config.yml: disable blank issue, add a contact link to the issue type selection page
- Update .github/renovate.json: add "dependencies" label (get the label added automatically to PRs by renovate)
> Update files related to repository management

- README.md
- docs/configuring-playbook.md
- docs/container-images.md
Also:
- Update README.md and docs/container-images.md: move Sygnal and ntfy to the proper category
- Update docs/container-images.md: copy explanation sentences from README.md to each category
> Update docs/configuring-playbook.md: adopt the same structure and order for entries as ones on README.md

- docs/configuring-dns.md
- docs/configuring-playbook.md
- docs/getting-the-playbook.md
- docs/installing.md
- docs/prerequisites.md
Please see: https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3744#discussion_r1829003610 and the commit comment.
> Add hard-coded breadcrumbs to documentation files about installation procedure for easier navigation

- docs/README.md
- docs/configuring-playbook.md
Closes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3770
> Make hierarchy among documentation pages related to installation

- docs/faq.md
- docs/installing.md
- docs/just.md
- docs/maintenance-upgrading-services.md
- docs/playbook-tags.md
- docs/prerequisites.md
Closes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3741
> Add docs/just.md

- docs/maintenance-migrating.md
This PR intends to improve migration guide. While the current instructions do work (I've followed the instruction to migrate successfully), I think the numbering list can be improved by replacing it with sections.
> Edit docs/maintenance-migrating.md

- README.md
Closes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3812
> Update README.md: edit "Getting started" section to introduce two installation guides

- docs/configuring-playbook-bridge-appservice-discord.md
- docs/configuring-playbook-bridge-appservice-slack.md
- docs/configuring-playbook-bridge-appservice-webhooks.md
Apply the common documentation style and structure to make them native by fixing the instructions being loosely based on foreign documentation
> Apply the common documentation style

- README.md
Closes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3847
> Edit README.md: add links to docs/FAQ.md and to the support section

- .github/ISSUE_TEMPLATE/feature_request.md
- CHANGELOG.md
- docs/README.md
- docs/ansible.md
- docs/configuring-playbook-appservice-draupnir-for-all.md
- docs/configuring-playbook-bot-chatgpt.md
- docs/configuring-playbook-bot-draupnir.md
- docs/configuring-playbook-bot-matrix-registration-bot.md
- docs/configuring-playbook-bot-mjolnir.md
- docs/configuring-playbook-bridge-mautrix-discord.md
- docs/configuring-playbook-pantalaimon.md
- docs/configuring-playbook-user-verification-service.md
- docs/faq.md
- docs/importing-postgres.md
- examples/reverse-proxies/caddy2-in-container/docker-compose.yaml
- justfile
- roles/custom/matrix-base/templates/bin/remove-all.j2
- roles/custom/matrix-bridge-appservice-irc/defaults/main.yml
- roles/custom/matrix-bridge-hookshot/defaults/main.yml
- roles/custom/matrix-dendrite/templates/dendrite.yaml.j2
- roles/custom/matrix-synapse-reverse-proxy-companion/defaults/main.yml
- roles/custom/matrix-synapse/defaults/main.yml
- roles/custom/matrix-synapse/templates/synapse/homeserver.yaml.j2
- roles/custom/matrix-synapse/vars/main.yml
Since Weblate outputs warnings about three dots (`...`) used as horizontal ellipsis (`…`), a commit of this PR replaces the former with the latter.
> Housekeeping: preparation for l10n with Weblate

- README.md
Element has taken over Dendrite as per the github.com/matrix repo.
> Update readme Dendrite link to new maintainer

- docs/configuring-playbook-conduit.md
- docs/configuring-playbook-dendrite.md
- docs/configuring-playbook-synapse-admin.md
- docs/configuring-playbook-synapse.md
- docs/configuring-playbook-telemetry.md
This PR intends to adopt the common description for homeserver implementations.
> Update docs for homeserver implementations (Conduit, Dendrite, and Synapse)

- docs/configuring-dns.md
Follow-up to https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3936
> Update docs/configuring-dns.md: move down the section about DNS setting for optional server delegation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- docs/faq.md
Closes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3948
> Mentions mash-playbook on feature_request.md and faq.md

- docs/configuring-playbook-jitsi.md
For https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/2707
I've not tested the configuration so I'm not perfectly sure if it is indeed supposed to be so.
> Update docs/configuring-playbook-jitsi.md: add instructions to create vars.yml files for each additional JVB (Jitsi VideoBridge)

- CHANGELOG.md
- README.md
- docs/configuring-playbook-conduit.md
- docs/configuring-playbook-conduwuit.md
- docs/configuring-playbook.md
- docs/container-images.md
- docs/howto-srv-server-delegation.md
- roles/custom/matrix-conduwuit/tasks/self_check_client_api.yml
- roles/custom/matrix-conduwuit/templates/conduwuit.toml.j2
- roles/custom/matrix-conduwuit/templates/labels.j2
- roles/custom/matrix-user-creator/tasks/util/ensure_user_registered_conduwuit.yml
See: https://github.com/girlbossceo/conduwuit/commit/e8508d16e1f5686881c40ba5b54f7a1a87cbe7e9
> Both, but I prefer conduwuit.
> Change capitalization per author's preference: Conduwuit → conduwuit

- docs/configuring-playbook-appservice-draupnir-for-all.md
- docs/configuring-playbook-bot-draupnir.md
- docs/configuring-playbook-bot-mjolnir.md
For https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3966
> Update docs for Draupnir, D4A, and Mjolnir: adopt the common section "Extending the configuration"

- docs/configuring-playbook-bot-draupnir.md
- docs/configuring-playbook-bot-mjolnir.md
For https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3966
> Update docs/configuring-playbook-bot-draupnir.md and docs/configuring-playbook-bot-mjolnir.md

- docs/configuring-playbook-bot-draupnir.md
Fixes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3979
Please check the context here: https://matrix.to/#/!cNSQwPqhHKkIZdBnvt:devture.com/$TgchFhTnv_qA7sRG9MLDo3Y4E06nwNcJNXJqIuQtDGM?via=devture.com&via=matrix.org&via=tchncs.de
> Update docs/configuring-playbook-bot-draupnir.md: create and invite the bot before starting

- docs/configuring-playbook-bot-draupnir.md
- docs/configuring-playbook-bot-mjolnir.md
For https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/3966
> Update docs for Draupnir and Mjolnir: improve the instructions for running the curl command to disable rate limiting

- CHANGELOG.md
- README.md
- YEAR-IN-REVIEW.md
- docs/configuring-playbook-bridge-postmoogle.md
- docs/configuring-playbook-email2matrix.md
- docs/configuring-playbook.md
- docs/container-images.md
- roles/custom/matrix-email2matrix/tasks/validate_config.yml
Thank you @spantaleev for having maintained the component since its inception!
> Update files for Email2Matrix

- docs/faq.md
- docs/maintenance-and-troubleshooting.md
This PR intends to move entries related to maintenance and troubleshooting from the general FAQ page to the dedicated page to improve the docs by addressing fragmentation.
> Update faq.md and maintenance-and-troubleshooting.md: 

- README.md
- docs/configuring-playbook-client-fluffychat-web.md
- group_vars/matrix_servers
- roles/custom/matrix-base/defaults/main.yml
- roles/custom/matrix-client-fluffychat/defaults/main.yml
- roles/custom/matrix-client-fluffychat/tasks/main.yml
- roles/custom/matrix-client-fluffychat/tasks/self_check.yml
- roles/custom/matrix-client-fluffychat/tasks/setup_install.yml
- roles/custom/matrix-client-fluffychat/tasks/setup_uninstall.yml
- roles/custom/matrix-client-fluffychat/tasks/validate_config.yml
- roles/custom/matrix-client-fluffychat/templates/labels.j2
- roles/custom/matrix-client-fluffychat/templates/systemd/matrix-client-fluffychat.service.j2
- setup.yml
Closes https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/783
> add FluffyChat

- docs/README.md
- docs/ansible.md
This commit changes ansible.md title and adds a link to the page on docs/README.md to improve discoverability of the guide a little bit.
> Update docs for Ansible

- README.md
- roles/custom/matrix-bot-buscarron/tasks/validate_config.yml
- roles/custom/matrix-bridge-go-skype-bridge/tasks/validate_config.yml
- roles/custom/matrix-bridge-mautrix-instagram/tasks/validate_config.yml
- roles/custom/matrix-cactus-comments/tasks/validate_config.yml
The placement of the badge does not seem to be aesthetically appropriate... (height of the badges is uneven)
> Add REUSE compliant badge on README.md

- docs/configuring-playbook-own-webserver.md
> Typo in configuring-playbook-own-webserver.md
